- region/brinstar/green.json
- tech.json
Fix Morph req for far missile from the left side of the room, and replace canBrinstarReserveHoleInOne with less specific tech.
> Changes to green Brinstar Reserve 

- enemies/brinstar/main.json
- enemies/maridia/main.json
- enemies/norfair/main.json
- enemies/wreckedship/main.json
Lots of duplicated enemy definitions, remove the dupes. Leave notes in commit messages for knowing where the dupes were so that we can document them later.
> Enemy weeds

- region/brinstar/blue.json
- region/brinstar/green.json
- region/brinstar/red.json
- region/crateria/central.json
- region/lowernorfair/east.json
- region/lowernorfair/west.json
- region/maridia/inner-green.json
- region/maridia/inner-pink.json
- region/maridia/outer.json
- region/norfair/east.json
- region/norfair/west.json
- tech.json
This should be all the left wall X-Ray climbs that can be set up with a simple stationary spin jump.  Exceptions: 1)The door on the crumble blocks in Big Pink. 2)Wrecked Ship Bowling Alley climb that goes up through the spike floor.  Part of #164
> Add the easy X-Ray climbs to logic 

- region/tourian/main.json
- tech.json
Each room of Metroids is killable with only 3 Power Bombs but they need a great deal of tricky avoidance so I created canMetroidAvoid either for going in reverse or for killing Metroids with Power Bombs.
Fitting the Missile & Super ammo into this goes together with the rest of the issues surrounding enemies so leaving it alone for now.
> Metroid Rooms logic

- region/lowernorfair/east.json
> Fix Fast Pillars Setup Room runway resets, since the ice clip from below is not possible. Resolves # 211.

- region/brinstar/pink.json
- region/lowernorfair/east.json
- region/lowernorfair/west.json
- region/maridia/inner-yellow.json
- region/tourian/main.json
- schema/m3-region.schema.json
Also:
- `note` definition has been centralized
- the schema now rejects properties it doesn't know
- more logical requirement properties use the `logicalRequirements` definition
> Schema improvements + prepare to define locks' `unlock` and `bypass` requirements as strats

- region/brinstar/green.json
- region/lowernorfair/east.json
- region/norfair/crocomire.json
- region/norfair/east.json
- region/region-readme.md
- schema/m3-region.schema.json
Farming should be inferred from the presence of respawning enemies
> Remove farming utility 

- logicalRequirements.md
- region/brinstar/green.json
- region/brinstar/pink.json
- schema/m3-region.schema.json
This element indicates that a strat can only be executed if coming directly from a specific node. Fixes #321.
> Add a `previousNode` logical element

- region/brinstar/green.json
- region/brinstar/kraid.json
- region/crateria/central.json
- region/maridia/inner-yellow.json
- region/maridia/outer.json
- region/norfair/west.json
- region/region-readme.md
- schema/m3-region.schema.json
This is sometimes needed when shinesparking out of a door.
> Add a property to canLeaveCharged, to indicate the need to previously open the door

- region/brinstar/pink.json
The chute from the top goes to the Supers, not to the bottom door.
> Fix a link in Spore Spawn Super

- logicalRequirements.md
- region/norfair/east.json
- schema/m3-requirements.schema.json
This will indicate that Gravity Suit's damage reduction shouldn't be applied when it's turned off.
> Add a `lavaPhysicsFrames` logical element for lava gravJumps

- region/crateria/central.json
The existing logic from location 7 to 1 only requires h_canDestroyBombWalls, but it should require abilities to get up to those blocks. A shinespark can also be used to get from 5 to 1 bypassing 7 (this uses less energy than shinesparking from 4 to 1, but only breaks the first set of blocks).
> Add requirements to get to door 1 in Landing Site

- region/crateria/east.json
- tech.json
Added 3 new Tech that were needed while working on East Crateria:
- canDoubleSpringBallJumpMidAir
- canCrouchJump
- canDownGrab
Currently crouch jump and down grab are assumed to be free, but adding these as tech could make the game more accessible. I made canDownGrab require canCrouchJump, as canCrouchJump is easier and these two are typically performed together, since a down grab alone wouldn't give more height than a spin jump.
Added canDoubleSpringBallJumpMidAir strat to get out of the right side of The Moat (3 -> 2).
Expanded strats in several rooms to no longer assume canWallJump:
- The Moat (2 -> 3) - the gravity strat needs wall jump
- West Ocean (5 -> 4) - this expansion adds alternate strats (without requiring wall jump): space jump, gravity+ibj, or gravity+vertical shinespark
- …
> Add to East Crateria: reqs, strats, 3 new tech

- helpers.json
The helper h_canOpenYellowDoors references h_canUsePowerBombs which is not defined until later in the list of helpers. It will be easier to process the helpers if we can avoid forward references like this. This is the only case of a forward reference in the helpers. This pull request resolves this by moving up the definition of h_canUsePowerBombs.
> Move up definition of h_canUsePowerBombs to avoid forward reference

- region/brinstar/green.json
- region/maridia/inner-pink.json
In Green Shaft two doors in this room were described with the same nodeAddress (a copy-paste error?). And in the Maridia Missile Refill room the nodeAddress for the (exiting) door was (incorrectly) given as the same as the door entering this room. I checked SMILE to get the correct nodeAddress for both of these.
> Fix door pointers in Green Shaft and Maridia Missile Refill

- region/crateria/central.json
The Pit Room requires both Morph and Missiles in order for the enemies to spawn.
Also added a note to clarify what seems to be a common misconception that entering the Pit Room with the required items is what sets the Zebes Awake flag. In fact the flag is set by opening any gray door locked by an enemy kill count. In the vanilla game this naturally happens in the Pit Room, but more generally it can happen in other places. So we should probably follow this up with a more systematic fix to address that. This change is enough for now to make the Map Randomizer work properly since it eliminates all gray doors in the game except for the ones in the Pit Room (with the result that the Pit Room is the only possible room where the Zebes Awake flag can become set).
> Fix the requirement for Zebes Awake in the Pit Room.

- region/brinstar/green.json
- region/wreckedship/main.json
Replace enemyKill strats for Phantoon and Spore Spawn. 
Reasons:
- enemyKill is more complicated to follow, requiring processing a lot of information in order to determine the possible strats (e.g., enemy JSON, weapons JSON, and the modifiers in the strat such as farmableAmmo, explicitWeapons, excludedWeapons).
- Because of this, it will be easier for us to use in the randomizer we are designing as we haven't fully implemented enemyKill. It may also make it easier for a player to see all of the possible strats in logic which can be used to kill the bosses.
- This more explicit structure is already used for most of the other bosses/minibosses (BT, Kraid, Crocomire, GT, Back-Side Botwoon, and the other Spore Spawn strats).
> Replace boss enemyKill strats with explicit strats

- region/wreckedship/main.json
Added canWalljump requirements to sponge bath and the Wrecked Ship Energy Tank Room.
Fixed a minor typo in a note.
> Add canWallJump requirements to Wrecked Ship

- region/norfair/west.json
Moving from right to left from node 2 to 1:
- Samus can shoot Ice Beam through the morph tunnel to freeze the Boyon, avoiding a hit. 
- With the addition of Heat and Lava Proof to the base strat, Samus can move slower to avoid the Boyon hit, taking no damage in the room.
> Fix Ice Beam Tutorial Room

- region/norfair/west.json
Getting up to the item (to escape):
- Reordered the strats so the easiest ones are first to match most other places in the data. I hadn't realized how messy this was going to look. I can separate these and split this into two pull requests if necessary.
- Added canWallJump tech to the Speedjump strat.
- Added canDownGrab tech to the Springball bomb boost, as indicated by its note. This was only recently added as a tech.
Getting back out to the right after getting the item:
- Added a note to identify where to execute two strats: Speedjump and HiJump.
- Also added canWallJump to the HiJump strat.
> Fix Crocomire Escape Room

- region/norfair/east.json
Getting to the left door of the Cathedral Entrance:
- Added a wall jump requirement to the base strat, then renamed it to Up from Below.
- Added two other strats which go through the morph tunnel and are easier to execute but have more heat frames.
> Add Strats to Cathedral Entrance

- region/brinstar/blue.json
- region/brinstar/green.json
- region/brinstar/kraid.json
- region/brinstar/pink.json
- region/brinstar/red.json
Most changes are simple wall jump additions throughout. Additionally there are a couple other changes:
- Switched to using the helper function "h_canDestroyBombWalls" in Blue Brinstar E-Tank Room to make the code simpler.
- Added a Space Jump strat to get to the top of Red Tower, as the previous Space Jump strat now requires a wall jump.
> Add canWalljump checks throughout Brinstar

- helpers.json
- region/brinstar/green.json
- region/brinstar/kraid.json
- region/lowernorfair/west.json
- region/maridia/outer.json
- region/norfair/crocomire.json
- region/norfair/east.json
- region/norfair/west.json
- tech.json
- Removed duplicate gate glitch tech and converted them into one tech: canGateGlitch, and 4 helpers, which include ammo used. Propagated these helpers throughout the codebase.
- Removed canDownGrab dependency of canCrouchJump and made a helper which combines both. Propagated this helpers throughout the codebase.
- Removed canMachball and put a note about the alternate spelling into canMockball.
- Removed the helper h_canOpenWrongFacingBlueGateFromRight and replaced its uses with two separate strats: Wave and the new helper h_canBlueGateGlitch
> Clean GateGlitch, DownGrab, Mockball tech

- region/maridia/inner-pink.json
It's no longer valid because the Botwoon enemy was split into two phases.
> Fix broken reference to enemy "Botwoon"

- logicalRequirements.md
- region/brinstar/red.json
- schema/m3-requirements.schema.json
- tech.json
-Samus eaters as a damage source
-Using them to build shinesparks in hellway and alpha pbs.  Beta pbs has a runway already.
> Samus Eater Logic for #488

- region/lowernorfair/west.json
- tech.json
Add a new tech that is used in all existing GT strats: canSafeSpotGT.
Add strats that no longer assume the player knows how to use the safe spot.
Add canBePatient for weak charge beams, as the fight would take 2-5 minutes. (~5 min for charge, down to ~2 min for charge + wave)
> Update GT Logic - No longer assume safe spot

- region/lowernorfair/east.json
Removed h_heatProof requirements from Ridley's Room. The boss scenario for the actual fight still requires Varia. In the future, other strats could be added to the boss scenario, including suitless variants. This could also be useful in randomizers that have changes like the following:
- Those that remove grey doors from boss fights, allowing Samus to run through the room.
- Those that already have some bosses defeated, or that don't spawn until something happens.
- Those that use custom Ridley logic instead of the boss scenario, like Map Rando.
> Remove Heatproof Reqs from Ridley's Room

- logicalRequirements.md
- region/norfair/crocomire.json
- schema/m3-requirements.schema.json
An object that requires you have a maximum value of health or ammo.  For situations where you are currently equal to or under capacity but can regain resources to a threshold amount for some obstacle.
-croc allows farming in random cycles so you need enough ammo to survive the cycle, but could enter with no missiles.
> Resource Capacity Object for #504

- region/norfair/crocomire.json
Crocomire's Room:
- Add wall jump requirements to strats
- Reduce the acid frames needed to get the item (it's still somewhat lenient)
Post Crocomire Farming Room
- Add wall jump requirements
- Split the tricky hi jump strat to its own
- Add notes to clarify some of the less obvious strats
- Add damage to the d-boost
> Fix Crocomire Room and Post Croc Farm Room

- region/lowernorfair/east.json
Moved strats to kill metal pirates from the obstacle to a 2->2 link. 
- This allows individual strats to be organized, named, and have notes. 
Added kill strats
- Missiles, shinespark echoes, charged spazer combos, weaker charge beams, and uncharged spazer
> Add Metal Pirates Kill Strats and Move to Link

- region/crateria/east.json
This relies on #496 and should fix #311 - An easier version of the suggested 1st and 3rd strats are already implemented and this adds the 2nd strat.
Changed the moat double spring ball jump to no longer be notable
> Add Moat Ceiling Bomb Jump

- region/brinstar/blue.json
- region/brinstar/green.json
- region/brinstar/kraid.json
- region/brinstar/pink.json
- region/brinstar/red.json
- region/lowernorfair/east.json
- region/maridia/inner-yellow.json
- region/tourian/main.json
- region/wreckedship/main.json
This should fix #457.
Add f_ZebesAwake to all rooms except:
- Pit Room - Already had it
- Morph Ball Room - The flag can only be given here if the flag is already set, making it useless. A devNote was added to explain this.
Move f_KilledMetroidRoom1-4 from the node to the lock. Making it actually require killing the metroids. Technically this could still be a problem if a hack both ignores grey door locks and requires the metroid flags. However, this should be in a much better place than it was before.
> Add Zebes Awake Flag Throughout

- tech.json
Morph cannot be included on canTunnelCrawl, because canMorphlessTunnelCrawl is an extension tech and would then also require morph. Instead morph should be included on all strats that require canTunnelCrawl. Fortunately the only place this tech was used already required morph.
- Removed morph here and added a devNote explaining to include it on the strats.
> Remove Morph from canMorphlessTunnelCrawl

- region/brinstar/blue.json
- region/brinstar/green.json
- region/brinstar/red.json
- region/crateria/central.json
- region/lowernorfair/east.json
- region/maridia/inner-green.json
- region/maridia/inner-pink.json
- region/maridia/inner-yellow.json
- region/norfair/crocomire.json
- region/norfair/east.json
- region/norfair/west.json
- tech.json
- Update the description to be anywhere that requires 3+ consecutive wall jumps.
- It is now required for canSunkenDualWallClimb and canInsaneWalljump.
> Add canConsecutiveWalljump throughout Zebes

- region/brinstar/kraid.json
This can be prevented by both being prepared and having space jump
> Add a Thorn Hit to Reverse Kraid

- region/maridia/outer.json
Bottom right door freeze crab strat. Part of #306 
It takes some effecient shooting, but there is enough leeway to miss once :)
Technically 2 crouch downgrabs can reach the upper ledge without a refreeze.
> Everest Crab step ladder

- region/brinstar/green.json
The strats were named backwards
> Fix Etecoon Beetom Strat Names Left/Right

- region/norfair/west.json
- Make notes more clear and tech more accurate.
- Add strats to get to the item on the left side.
> Add Strats in Crumble Shaft

- schema/m3-requirements.schema.json
Sometimes we want to be able to represent a requirement for an obstacle to already be cleared. In strats we have been doing this by having an "obstacles" field with `requires: ["never"]`, but this doesn't work in some other places where logical requirements may appear (such as in "farmCycles"). By adding obstaclesCleared as a first-class requirement type, we can use it anywhere.
> Add obstaclesCleared requirement

- region/brinstar/green.json
- region/lowernorfair/east.json
Add canPreciseWalljump:
- Green Hill Zone: 1->2
- Fast Pillars Setup Room: 5->1
Modernize some of the code in these two files (LN East, Green Brinstar):
- h_canPassBombPassages -> h_canBombThings
- Replace obstacles with "never" with requires with "obstaclesCleared"
- Ensure bombs and power bomb usage is replaced with their helpers, where applicable.
> Add precise wall jumps and modernize logic

- logicalRequirements.md
- region/crateria/central.json
- schema/m3-requirements.schema.json
- tech.json
-excessShinesparkFrames: How far  a shinespark goes past the desctructable blocks / ledge / other where it is ok if you stop early due to running out of health.  If you do not run out of health, the full shinesparkFrames value is used.
-canConserveShinesparkHealthComplex: Charging a shinespark then moving into a better position to spark that costs less health.
The Landingsite gauntlet door `canLeaveCharged` can be fulfilled with no `framesRemaining` and no `shinesparkFrames`.  This `should` result in a logical shinespark that accomplishes nothing, or an invalid way of entering with blue suit.
For #559
> Shine schema update

- region/crateria/central.json
- tech.json
- canConserveShinesparkHealth -> canShinechargeMovement
- canConserveShinesparkHealthComplex -> canShinechargeMovementComplex
- Add canShinesparkWithReserve
- canShinechargeMovement no longer requires canMidairShinespark
> Update Shinespark tech names and descriptions

- region/maridia/inner-pink.json
- region/maridia/outer.json
- Fix new coss room jumps to require air physics in Outer Maridia, since they were added at the same time as the physics changes
- Clarify how precise tricky cross room strats are
> Cross room jump physics and notes changes

- region/crateria/central.json
- region/crateria/east.json
- region/crateria/west.json
Remove strats that are notable that shouldn't be because:
- They're intuitive and not too difficult,
- They are well represented by their tech, and not harder than it,
- Or, they are one of the primary examples of the given tech, and the place where/why you would likely learn the tech.
Updated h_canPassBombPassages -> h_canBombThings
Add energy and strat requirements to the gauntlet, resolving FIXME's
> Crateria removing some notable strats

- region/crateria/east.json
- region/maridia/outer.json
- tech.json
- Hijump is no longer required on canDoubleSpringBallJumpMidAir, as it is not always needed in lava
- Add Hijump to the places that use the tech that require it.
> Remove Hijump from canDoubleSpringBallJumpMidAir

- region/maridia/inner-pink.json
This matters because an X-ray climb can get you to node 8 (the right item) and with that you should also be able to reach node 7 (the left item).
> Add missing free strat between Aqueduct items

- helpers.json
- tech.json
- Reformatted the tech file to be a bit more clean looking, as this is likely the main file people will look at.
- Removed `canQuickLowTideWalljumpWaterEscape`
- Removed `h_canPassBombPassages`. Use `h_canBombThings` instead, resolving #551 
- Add `canWalljump` to `canCWJ`
> Tech Cleanup

- region/maridia/inner-green.json
- region/maridia/inner-pink.json
- region/norfair/east.json
- tech.json
This ended up becoming 5 tech. Most of them are simply extensions of other tech, used only in very rare circumstances, and should simply be notable
- `canLavaGravityJump`: only used in 1 room, fundamentally the same thing as `canGravityJump`
- `canSunkenDualWallClimb`: only used in 2 rooms, uses are replaced as notable
- `canWaterBreakFree`: only used in 1 room, replaced as notable
- `canGravityWalljump`: kind of a silly tech and only used in 1 room, replaced as notable
- `canShotBlockOverload`: only used in 1 room, replaced as notable
- Update description and requirements of `canIframeSpikeJump`
> Remove Three Tech

- region/norfair/east.json
I noticed in a recent Croakomire video that he was able to get through here with no ETanks: https://clips.twitch.tv/DignifiedAbstruseClamPeteZaroll-mvUHUTWl73LfxhXt
The logic currently has this as requiring 400 heat frames (100 energy), which seems like too large a gap from what is actually doable without much difficulty. In this case it resulted in an ETank being easily obtainable out of logic. We fix this by reducing the heatFrames from 400 to 360.
> Reduce heatFrames in Speed Booster Hall

- region/lowernorfair/east.json
I tested this and found that a suitless trip on Main Hall elevator takes exactly 109 energy in either direction (with no fast elevator patch).
> Correct Main Hall elevator heat damage

- helpers.json
- logicalRequirements.md
- region/crateria/central.json
- region/region-readme.md
- schema/m3-region.schema.json
- schema/m3-requirements.schema.json
- tech.json
This includes the following:
- New tech:
- canEnterRMode
- canEnterGMode
- canEnterGModeImmobile
- canArtificialMorph
- New node properties:
- leaveWithGModeSetup
- leaveWithGMode
- New logical requirements:
- comeInWithRMode
- comeInWithGMode
- New helper:
- h_canArtificialMorphMovement
- Example strats in Landing Site, Flyway, and Crateria Tube.
The new node properties and logical requirements follow a pattern similar to "canLeaveCharged" and "canComeInCharged" (except without the "can" to avoid confusion with tech: we may later rename "canLeaveCharged" and "canComeInCharged" to "leaveCharged" and "comeInCharged"). 
The node property "leaveWithGModeSetup" is for describing how to leave a door node while taking enemy damage, in a way that can be used to set up R-mode or G-mode in the …
> Add G-mode tech, requirements, and node properties

- region/brinstar/red.json
#625 
HiJump strat, that jumps from spikes to cross the gaps.
Ice strats are harder than they seemed.
There's potential here for adding a junction on the left side spike stairs to separate the single damage boost as a general way across the first gap.
> Xray firefleas strats

- helpers.json
- region/brinstar/blue.json
- region/brinstar/green.json
- region/brinstar/pink.json
- region/brinstar/red.json
- region/crateria/central.json
- region/crateria/east.json
- region/crateria/west.json
- region/lowernorfair/east.json
- region/lowernorfair/west.json
- region/maridia/inner-green.json
- region/maridia/inner-pink.json
- region/maridia/inner-yellow.json
- region/maridia/outer.json
- region/norfair/crocomire.json
- region/norfair/east.json
- region/norfair/west.json
- region/wreckedship/main.json
- tech.json
This will require double checking currently open PRs to not be using tech assuming they include morph
> Gmode helpers - Split tech to no longer require morph

- region/crateria/central.json
- region/crateria/east.json
- region/crateria/west.json
Elevators can be used while in G-mode (unlike normal doors which cannot be shot open), so they are a way to bring G-mode into a third room.
> Add leaveWithGMode for Crateria elevators

- region/norfair/east.json
When coming from the right door, it's possible to get to the item and back using SpaceJump or Grapple without any tanks.
> Double Chamber heat frames getting to & from the item

- region/lowernorfair/east.json
This is the strat that is used in the top part of the room to just reach the platform. The name does not include the room name as it should if it were notable, and it doesn't seem important enough to be notable (it's only useful for avoiding wall jumps).
> Make 'X-Ray Climb' in Fast Pillars Setup Room not notable

- region/tourian/main.json
The acidFrames for the Fearless Dive here were overly lenient.
This is why, for example, the logic thought SpeedBooster was needed for progression at the start of cheesyboatride's recent seed (https://maprando.com/seed/6m8Q6m2UMFjlzpbTu-57lg/).
> Tighten acidFrames in Metroid Room 1

- region/lowernorfair/west.json
Coming up from the bottom of acid chozo statue with a CF grapple clip will enable Samus to get to the right door without needing `f_UsedAcidChozoStatue`. It may be possible to go to the statue to save some heat frames, but the CF grapple clip currently requires being `heatproof`
> Update Acid Chozo Statue

- helpers.json
- region/lowernorfair/east.json
- region/lowernorfair/west.json
- region/maridia/inner-green.json
- region/maridia/inner-pink.json
- region/wreckedship/main.json
- tech.json
Changed the techs for CF clip so there is 1)on ground 2)bomb jump up to clip and 3) jump morph up to clip.  Breaking crumbles or grapple trick can be used from any of them.
I left the ground CF clips as notable mostly for being easier tech, but its also not a specified CF clip tech.  Removed notables from the rest because the difficult part is now in the tech.  The places you can CF are not too well known, plus the botwoon/shaktool clips are known well enough you would want to toggle them as notables.  But the difficulty is all in the tech and we don't want to make every instance of a tech also notable.  A way to list the uses elsewhere would be nice.
I put the leniency power bombs in the helpers now.  It is the same difficulty everywhere the tricks show up.
> CF clip rework

- helpers.json
A second shot is not much, but it could be a problem to increase this much more, as the player could easily go out of logic if the leniency is too large.
I kept the original and secondary shots separate, so it is more clear what is going on, and which number to increase if the leniency was increased or removed.
Note that in Map Rando, these will still be multiplied by the user's resource multiplier.
> Add a leniency shot for gate glitches

- region/maridia/inner-pink.json
This may be possible without a wall jump (space jump into spring ball midair) or without space jump (precise wall jump), but the careful jump is easier.
> East Cac Space Jump Water Bounce

- region/brinstar/green.json
I wonder if this should be notable? Because people keep asking about it.
It is a little harder than most precise wall jumps, because of the spawning bugs, and because it feels doable without the pipe.
> Make Green Hill Zone Wall Jump Notable

- region/brinstar/pink.json
- region/crateria/central.json
- region/crateria/east.json
- region/lowernorfair/east.json
- region/maridia/inner-pink.json
- region/maridia/inner-yellow.json
- region/maridia/outer.json
- region/wreckedship/main.json
Add a bunch more X-ray climbs:
- Landing Site, right side (deep stuck)
- Spore Spawn Supers
- Glass Tunnel, to get from bottom right door to inside tube (deep stuck)
- Colosseum, right side
- Bowling Alley, from Gravity Suit door up through spikes
- East Cactus Alley, to get above water surface
- Plasma Spark Room, bottom right door to middle right door (deep stuck)
- Fast Pillars Setup Room, either bottom door to top left door (deep stuck)
- Main Street, bottom right door to middle right door
> More X-ray climbs (including deep stucks)

- region/maridia/inner-yellow.json
Updating this low wall jump strat to include canMomentumConservingTurnaround as an alternative to canInsaneWalljump. As insomniaspeed found, it's much easier with the turnaround:
https://discord.com/channels/1053421401354285129/1053434704180805744/1113636325057380382
> Update low jump strat into Pseudo Plasma Spark Room

- region/maridia/inner-pink.json
Shinesparks can do a lot towards reaching the items.  
Removed the bootsless suitless notable, and merged it into the HiJump strat.
> Sand Pits update

- region/tourian/main.json
Taking damage during the shaft climb is super punishing.  And especially on first attempts you won't plan ahead with the right side pirates.
> Easier reverse leodox option

- region/lowernorfair/west.json
In vanilla, the only way to activate the statue is with Space Jump, so strats from 1->3 required space jump or the statue to have already been activated. 
A randomizer may wish to remove this space jump requirement (located on the statue lock), so common non-space jump strats from 1->3 are added.
> Acid Chozo Statue Partial Update

- helpers.json
- region/maridia/inner-green.json
- region/tourian/main.json
- tech.json
- weapons/main.json
These are the assumed techs we've been using.  Most are very widespread or don't make sense to add to specific strats. Pseudo screw and SBA were easy enough to add where used.  canUseGrapple and canCameraManip could be added to strats still.  canDraygonEscape wouldn't be put in logic.
The very low level techs of #745 would be added for a different purpose so I'm not worrying about them now.
> Add low level tech

- tech.json
We have canSpringBallJumpMidAir in "Medium" in Map Rando now, and it's one of the trickier ones in that level. It can be helpful to players to have a little more detail explaining how to buffer the jump, which is generally the easiest way to do it (i.e. assuming a max jump height or other precise positioning isn't needed, which would require some harder tech on top of canSpringBallJumpMidAir).
> Add note about buffering the jump in canSpringBallJumpMidAir

- helpers.json
- region/maridia/outer.json
In order to put in `leaveWithGMode`, you need to include strats to go to the door node that sets up the gmode and return. This ended up being a pain for Everest.
> G-Mode Main Street/Everest Morph Tunnel

- region/wreckedship/main.json
I swapped the order of these strats, as the easier one should be earlier. Otherwise if the player can do a 25 tile short charge, it would say use `Basement Speedball (Phantoon Alive)` regardless of if it was dead or alive.
> Remove Notable from Basement Speedball

- region/maridia/inner-pink.json
This seems relatively useless, since the Motchroid clip is easier in every way
> Delete Botwoon Hallway Puyo Ice Clip

- logicalRequirements.md
- schema/m3-requirements.schema.json
@kjbranch mentioned that some G-mode strats may not work when entering immobile, as the delay to get hit can result in enemies no longer being in the position needed to execute the strat. To support being able to properly express requirements in cases like this, we add a "mobility" property which can be set to "mobile" if it is required that Samus enter mobile. 
For completeness, we also support an "immobile" requirement though it is not clear yet if this will have any applications. Entering with immobile can allow Samus to stand suspended in the air, which conceivably could have some use. Regardless of the amount of reserve energy, for direct G-mode I think it should always be possible to enter immobile by doing an early turnaround, earlier than what would result in artificial morph.
> Add 'mobility' property to comeInWithGMode requirement

- helpers.json
- region/brinstar/green.json
- region/brinstar/red.json
- region/crateria/central.json
- region/crateria/east.json
- region/crateria/west.json
- region/lowernorfair/east.json
- region/maridia/inner-green.json
- region/maridia/inner-pink.json
- region/maridia/inner-yellow.json
- region/norfair/crocomire.json
- region/norfair/east.json
- tech.json
This addresses #817 
What are your thoughts on this? 
There are currently only two different ceiling clip tech, one for low level strats (`canMochtroidIceClip`) and then it can be paired with other tech to increase its difficulty (`canPartialFloorClip`). Then actual tricky strats are all notable, so they could be increased in difficulty. Then the `canPreciseCeilingClip` is for the very precise stuff, which would be able to be used on all of the lower difficulty notables without Morph+XRayTurnAround. 
Alternatively, we could make a mid level clip for standard wall crawlers and snails, and make those no longer notable.
> Ceiling and Ice Clip Rework

- region/lowernorfair/east.json
This is more appropriate for how the strat works.  I saw someone try to ice bridge this because canUseFrozenEnemies is an option here.
> LN Firefleas Spike pit

- region/maridia/inner-pink.json
I went back and forth on ways to bypass snail climbs, and eventually settled on ignoring them. It ended up making way too many things far too complex. 
I doubt it would ever come up that a player can do these g-mode strats without the snail climb, but could be a problem in an enemizer (along with many other things)
> G-Mode Aqueduct, Crab Shaft

- region/maridia/inner-pink.json
- tests/asserts/keywords.py
Rooms that are still missing: 
- East Cac Alley, 
- Crossing the Colosseum with artificial morph IBJ (If it's possible, it sounds like a huge pain)
- Going down the sand pits in Botwoon E-Tank Room (currently a huge pain to represent and it can't work with this schema)
> Add Majority of Missing G-Mode in Pink Maridia

- logicalRequirements.md
- region/tourian/main.json
- schema/m3-requirements.schema.json
Enemy hits are generally not needing to be multiplied by a leniency factor as the number of enemy hits is typically fixed based on the strat. Heat, acid, and lava frames do need a leniency factor because it is dependent on how fast the player can platform through the environment. 
Metroid hits are more like environmental damage than discrete hits, and the damage they deal is heavily dependent on the player's platforming ability going through a room. 
Additionally, the number of energy loss which was chosen for the enemy damage was 16 frames (12 damage). Each of these damages are given on an individual frame, not 12 at once. Because of this, strats with precise timing are forced to deal damage with a multiple of 12, which can be a problem (g-mode immobile).
Because of this, metroid damage …
> Convert Metroid Hits to Frames

- helpers.json
- logicalRequirements.md
- schema/m3-requirements.schema.json
This adds a new logical requirement type to represent a process that refills certain resource types, potentially in the middle of a strat. This is proposed as a generic, flexible building block applicable to many situations, for example:
- farming in the middle of a boss fight (e.g. GT)
- using a Crystal Flash in the middle of a heat run (or lava/acid dive)
- non-infinitely spawning enemy farms (in conjunction with some other requirement to indicate ability to reset the room through an accessible door)
This would also allow us to represent re-spawning farms (and uses of the Ship or recharge stations) as normal strats, e.g. in a link from a node to itself, eliminating the need for some special handling.
With refills being combined with other resource requirements, it matters what order …
> Add 'refill' logical requirement to schema & docs

- region/brinstar/blue.json
- region/brinstar/green.json
- region/brinstar/kraid.json
- region/brinstar/pink.json
- region/brinstar/red.json
- region/crateria/central.json
- region/crateria/east.json
- region/crateria/west.json
- region/lowernorfair/east.json
- region/lowernorfair/west.json
- region/maridia/inner-green.json
- region/maridia/inner-pink.json
- region/maridia/inner-yellow.json
- region/maridia/outer.json
- region/norfair/crocomire.json
- region/norfair/east.json
- region/norfair/west.json
- region/tourian/main.json
- tech.json
The definitions are roughly
canBePatient: >1.5 minutes, translating to >2 screens of X-ray climbing
canBeVeryPatient: >3 minutes, translating to >4 screens of X-ray climbing
For Map Rando, the plan is to have canBePatient in Extreme and canBeVeryPatient in Insane. And then X-ray climbs of 2 or fewer screens can be put back into logic on Expert settings.
The wording in the definitions of canBe(Very)Patient is deliberately made a little more vague, to allow us some wiggle room for certain strats, particularly non-respawning enemy farms, where the amount of time required is variable and we don't intend to model it exactly.
This is intended only as a starting point to introduce the new patience tech split. It is expected that follow-up pull requests will be needed to add "canBePatient" in …
> Split off canBeVeryPatient and add patience on X-ray climb strats

- region/crateria/central.json
- tests/asserts/keywords.py
This PR starts with a small number of rooms, to get feedback on the approach before doing more.
To decide which patience tech (if any) to require for a farm, I try to estimate roughly the expected amount of time to collect a certain amount of the given resource, and compare that with thresholds of 1.5 minutes (canBePatient), 3 minutes (canBeVeryPatient), and 12 minutes (not in logic):
Energy: 100 (a full ETank)
Missile: 2
Super: 2
Power Bomb: 2
For Missiles they come in units of 2 anyway, while for Supers it's possible they will be for a gate glitch so a second one is for leniency. For Power Bombs it's because there's a significant possibility of needing two to break blocks in two different places. It's all a little arbitrary but the goal is just to get things roughly on the right scale …
> Farms in Central Crateria

- region/lowernorfair/east.json
- region/norfair/east.json
- tech.json
This adds a new tech canPauseAbuse for pausing to prevent death just before collecting an energy drop. (For the moment at least, manual reserve usage is out of scope of the tech.)
Farming strats are added for heated rooms, using the new tech. I took the opportunity to tighten some of the heat frames as well. Bat Room could still use some tightening for the walljumpless strats.
Closes issue #952.
> Add canPauseAbuse tech, refine heated farms

- region/brinstar/green.json
- region/brinstar/kraid.json
- region/brinstar/red.json
- region/norfair/east.json
This is to handle the situation where you may come into the room with low energy, where health bomb would prevent you from getting Power Bomb drops from Beetoms initially. We could refine this further if we had a requirement type to check for a minimal amount of a resource (energy), i.e. >= 30 energy, without consuming it. In practice, 4 Missiles will probably be available anyway, so not much is lost by doing it this way, by assuming you just need to reload the room a few times to get your health up first.
We also change the "PowerBomb" requirement to a "resourceCapacity" requirement: this will be more clear for readers of the logic; the meaning of a "PowerBomb" requirement is not intuitive and kyleb is working on phasing it out.
> Fix Beetom farms

- region/brinstar/blue.json
The Power Bomb option in this Speedball strat (for breaking the PB blocks to open the runway to the right) doesn't seem useful. With the ability to use a power bomb, you could just use it to break the left blocks directly, which is already covered under a different strat.
> Simplify Morph Ball Room Speedball (Right to Left)

- region/lowernorfair/east.json
- region/lowernorfair/west.json
- region/maridia/inner-pink.json
- region/maridia/inner-yellow.json
- region/maridia/outer.json
- region/norfair/crocomire.json
- region/norfair/east.json
- region/norfair/west.json
- region/wreckedship/main.json
- Double checked and fixed some minor things with Maridia Obstacles
- Reduced the number of places where bombs are called morph bombs
- Removed places where opening a green gate required `h_canOpenGreenDoors`, replaced it with a super
- Removed duplicate super requirements in Fast Ripper Room. It looks like L->R always required 2 supers to open the gate
- Add `canBeVeryPatient` to the Bowling Ceiling Bomb Jump
> Random Cleanup

- helpers.json
- region/lowernorfair/east.json
- region/norfair/east.json
The energy loss I measured:
top going down 14-15
top going up 26-27
bottom going down 108
bottom going up 109-110
vanilla combined, slow elevators:
going down 123
going up 136
The energy loss measured with Map Rando's fast elevators:
top going down 7-8
top going up 11-12
bottom going down 46
bottom going up 47
So Map Rando would be able to change the heat frame values to these:
`h_LowerNorfairElevatorDownwardFrames`: 32
`h_LowerNorfairElevatorUpwardFrames`: 48
`h_MainHallElevatorFrames`: 188
> Heated Elevator Helpers

- region/brinstar/blue.json
- region/brinstar/green.json
- region/brinstar/kraid.json
- region/brinstar/pink.json
- region/brinstar/red.json
- region/crateria/central.json
- region/crateria/east.json
- region/lowernorfair/east.json
- region/lowernorfair/west.json
- region/maridia/inner-green.json
- region/maridia/inner-pink.json
- region/maridia/inner-yellow.json
- region/maridia/outer.json
- region/norfair/crocomire.json
- region/norfair/east.json
- region/norfair/west.json
- region/wreckedship/main.json
- tech.json
Split damage boost tech into two: `canNeutralDamageBoost` and `canHorizontalDamageBoost`. Remove `canContinuousDboost`, as its 3 uses were notable horizontal ones.
Looking for help with the `canHorizontalDamageBoost` description
> Damage Boost Rework

- region/maridia/inner-yellow.json
This upgrades the `canUseFrozenEnemies` requirement to `canTrickyUseFrozenEnemies` and adds more details to the description of the strat. This only affects the 3 -> 1 link, the one that requires killing all the pirates, which is what makes the strat tricky.
> Bump up requirement for Frozen Pirate Plasma Escape

- region/norfair/east.json
I know this doesn't address all of the concerns in #988, but this is how I would write the strat.
- It's still in `Basic` with HiJump, but with ~50% more frames. 
- It's also still in `Medium` without HiJump, but now requires `canPreciseWalljump` in addition to `canConsecutiveWalljump`, and either more than 2x the frames or `canCarefulJump` and 1.5x the frames.
- It's now tighter with `canDelayedWalljump`
I wouldn't be opposed to moving `canPreciseWalljump` into `Hard`
> Double Chamber Wall Jump

- region/lowernorfair/east.json
I think heat frame scaling gets around the intended strat being not obvious.  Since you are just taking longer to do the same thing.
Fixes #1005
> Add requirements for WRITG top pirate

- region/crateria/east.json
I found an easier way to do the remaining east ocean strat -- 1) fully in room 2)no Choot damage 3)Turning off springball at the end makes it much easier.
It is equivalently difficult to the `walljump + frame perfect spacejumpwaterbounce` strat.  But you can probably get this more consistent.
> East Ocean Springball Hops + Spacejump strat

- region/brinstar/green.json
- region/maridia/inner-green.json
- region/maridia/inner-yellow.json
I went through all the notes for `pseudo` and went through all the uses of `"Charge"` to look for missing uses of `canPseudoScrew`. I think it can be used as a full tech instead of a minor tech.
> Add more uses of canPseudoScrew

- region/maridia/inner-yellow.json
Make it a little more lenient for lower difficulties by adding `canDodgeWhileShooting`, or other ways to dodge or kill the enemies. 
It's assumed that some of the enemies can be killed easily (mostly the Choots) and can be used to refill missiles enough for the trickier enemies in the middle of the room.
> Update Thread The Needle Room

- region/brinstar/blue.json
- region/brinstar/green.json
- region/brinstar/kraid.json
- region/brinstar/pink.json
- region/brinstar/red.json
- region/crateria/central.json
- region/crateria/west.json
- region/lowernorfair/east.json
- region/norfair/east.json
- region/norfair/west.json
- region/wreckedship/main.json
- tech.json
It was hard to decide if `canSpeedball` was different from `canMockball`+SpeedBooster.  But its a named maneuver and I want a slight requirement to jump height and run speed control.
Fixes #939 
It was hard to test the `fast` through door speedballs before, but after testing 14 unused tiles feels like a better number.
> Speed ball revisit

- region/brinstar/kraid.json
- region/crateria/east.json
- region/maridia/inner-pink.json
- region/maridia/outer.json
- region/norfair/crocomire.json
- region/norfair/east.json
- region/wreckedship/main.json
- tech.json
PCJR mellas were too chaotic so they were left out.
Touching the transition on the Left side vs Right side was possible from all doors except extra requirements were required in some rooms.
-Crab maze can get left side but needs morph for right side
-Crab shaft can use supers for left side but needs to travel to the bottom to touch right side
-Aqueduct is harder to get left side when itemless but it can be done
So much easier with custom portals.  And all the transitions are in a list for me.
> Upward G-Mode

- region/maridia/inner-green.json
- region/maridia/inner-pink.json
- tech.json
Removed canBombJumpOnSand.  It and canSandIBJ were the same thing.  Their approach to west sand hall insane bomb jump was different, but that was specific to that one strat.
I wanted to expect more enemy hits when crossing the sand halls.  West sand hall has some tricky platforming and its sort of written where crossing the room in Basic takes two hits, careful jump reduces it to one hit, and at VeryHard you can expect to dodge.  Then east sandhall already had most of that logic already there.  
In East the enemies were more exposed so I was more ok using weapons to kill them.  In West it felt like you needed to know enemy spawns to kill them and that would be VeryHard level knowledge.
Writing the sandjump room entry, in the center of the room, didn't work out since it depends on the room …
> Sand halls Update

- logicalRequirements.md
- region/brinstar/green.json
- region/brinstar/pink.json
- region/norfair/east.json
- region/norfair/west.json
- schema/m3-region.schema.json
- schema/m3-requirements.schema.json
Previous nodes are not really practical to use when interpreting the data, as the number of nodes and links is too large. Fortunately these are no longer required due to the new encoding methods we have developed. 
Removed: `previousNode`, `clearsPreviousNode`, and `previousStratProperty`
> Remove All Previous Node Objects

- region/crateria/central.json
- region/lowernorfair/east.json
- region/region-readme.md
- schema/m3-region.schema.json
- tests/asserts/keywords.py
- Remove deprecated strat property "obstacles" from schema (All occurrences were previously removed).
- Remove deprecated property "requires" on obstacles from the schema and from the last two places where they occurred.
- Clean up the docs to remove references to the now-removed properties.
- Remove the tests corresponding to the now-removed properties (and also to a strat property "clearedObstacles" which doesn't exist). I checked that the remaining tests do cover the strat property "clearsObstacles" and logical requirements "obstaclesCleared" and "obstaclesNotCleared".
> Wrap-up obstacles clean-up

- schema/m3-region.schema.json
- strats.md
- Remove the obsolete description of `obstacles` strat property and its occurrence in the example.
- Remove the `stratProperties` strat property from the docs and schema. There were never very many occurrences of this in the data, and by now they have all been removed as we've settled on using abstract nodes or obstacles to handle such scenarios.
- In the strat docs, move the "Structure" section to the top. We will soon be adding more strat properties, and it can be helpful to have the overview at the beginning rather than the end of the page.
> Update strats.md and schema

- region/brinstar/pink.json
Adds several g-mode strats in Pink Brinstar. The remaining strats that are not included in this PR:
- Big Pink uses
- Big Pink leave with g-mode from door 4
- Pink Hoppers: Left to Right
> G-Mode: Pink Brinstar part 2

- helpers.json
- region/brinstar/kraid.json
Not overly impactful, but in addition to one less thorn hit on low skill settings, the list of helper functions could help game devs quickly see some odd quirks they may want to edit out in their game.
> Add h_KraidCameraFix

- logicalRequirements.md
- region/brinstar/blue.json
- region/brinstar/green.json
- region/brinstar/kraid.json
- region/brinstar/pink.json
- region/brinstar/red.json
- region/crateria/central.json
- region/crateria/east.json
- region/crateria/west.json
- region/lowernorfair/east.json
- region/lowernorfair/west.json
- region/maridia/inner-green.json
- region/maridia/inner-pink.json
- region/maridia/inner-yellow.json
- region/maridia/outer.json
- region/norfair/crocomire.json
- region/norfair/east.json
- region/norfair/west.json
- region/region-readme.md
- region/tourian/main.json
- region/wreckedship/main.json
- schema/m3-region.schema.json
- schema/m3-requirements.schema.json
Currently `shinesparkFrames` occurs in several places in the schema, namely in `canShineCharge`, `canLeaveCharged`, and `canComeInCharged`. Also `excessShinesparkFrames` occurs in both `canShineCharge` and `canComeInCharged`.
This PR simplifies the schemas by pulling `shinesparkFrames` and `excessShinesparkFrames` into stand-alone logical requirements (similar to `heatFrames`, `metroidFrames`, etc.), and removing them from `canShineCharge`, `canLeaveCharged`, and `canComeInCharged`.
I believe this is cleaner for a few reasons: 
- `canShineCharge` is primarily a tech/skill requirement (a measure of short-charging ability). It is used in many places where there are no shinespark frames required (e.g. if only blue speed is needed). So it makes sense to split off any shinespark frame …
> Split (excess)shinesparkFrames into separate requirements

- region/crateria/west.json
It's not possible to exit G-mode by using x-ray after using a CF. Exiting by having the reserves trigger is not useful in these instances, because your reserves would then need to have energy in them, and there is no farm in this room.
> Remove G-Mode Strats That CF and Exit G-Mode

- region/maridia/outer.json
The other variations on this strat looked ok.  Requiring either PBs or h_canUseBombs or h_canArtificialMorphIBJ to climb from the bottom of the room.
> Add Bombs requirement to Main Street strat

- region/crateria/central.json
- region/crateria/west.json
- schema/m3-region.schema.json
Things of note:
- I kept the strats that had more unusable tiles than their in-room runway had. And I kept their node's runways. This is not yet representable.
- I deleted some strats in the Climb that climb with temporary blue that come from a doorway. I think the 28 tiles in room should be plenty for strats this complex.
- There are 3 strats in Crateria Supers that I had to split, called `SpeedKeep for Temporary Blue`. I'm not I properly renamed them and edited their notes.
> Cross Room Runways in Central Crateria, Pt 3

- region/brinstar/blue.json
- region/crateria/central.json
- region/crateria/west.json
Converted references from `Charged` to `Shinecharged`
Added old `unusable tiles` as a dev note, because I think they're still somewhat useful to be able to see
There was a strat in the climb that used to just say 19 tiles. I wasnt sure if that was including the the door already unlocked or not, so I included the opposite option now, not sure which is correct.
> New Runway Cleanup - Misc Changes

- region/crateria/east.json
- region/crateria/west.json
- tests/asserts/keywords.py
The new cross-room strat schema has specific requirements on node types of the `from` and `to` nodes:
- In strats with an entrance condition, the `from` node must have `nodeType` either `door` or `entrance`.
- In strats with an entrance condition, the `to` node must have `nodeType` either `door` or `exit`. 
In the old style, cross-room strats often started at junctions instead of a door node, which makes it easy to violate the new constaints by forgetting to change the `from` node as part of the migration. To prevent problems like this, this PR adds tests that will fail if the new constraints are not satisfied.
This PR also fixes all the existing strats that were caught failing the new tests.
> Check node types

- helpers.json
- region/brinstar/green.json
- region/brinstar/pink.json
- region/brinstar/red.json
- region/crateria/central.json
- region/lowernorfair/east.json
- region/lowernorfair/west.json
- region/maridia/inner-green.json
- region/maridia/inner-pink.json
- region/maridia/outer.json
- region/norfair/east.json
- region/norfair/west.json
This was prioritized because currently new and old x-ray climbs have different leniency factors.
I did get rid of some `canNavigateUnderwater` (not really affecting x-ray movement and wont matter at this difficulty) and `canHeatRun` (implied by the heat frames and wont matter at this difficulty).
> Update Cross-Room X-Ray Climbs

- helpers.json
- logicalRequirements.md
The helper `h_canNavigateHeatRooms` can be deleted after its uses are removed. This PR doesn't try to remove them yet, as there are >900 occurrences, making it not straightforward to do manually. This could probably be done quickly as an automated large-scale change if auto-formatting is accepted (PR #1114 and PR #1115).
Note: The implicit requirement `{"or": ["h_heatProof", "canHeatRun"]}` within heat frames (from `heatFrames` logical requirements as well as from implicit requirements in cross-room strats) is already implemented in Map Rando.
> Update docs to clarify that h_canNavigateHeatRooms is no longer needed

- helpers.json
- region/brinstar/green.json
- region/brinstar/pink.json
- region/brinstar/red.json
- region/crateria/central.json
- region/lowernorfair/east.json
- region/maridia/inner-pink.json
- region/norfair/east.json
- region/wreckedship/main.json
This standardizes all the X-mode strats to have a leniency of 1 extra spike hit, easily adjustable by being centralized to leniency helpers.
I'm the assuming the varying amount of hits in the existing logic were just representing different amounts of lenience and had no significance. If some of these strats actually have a required second (or third) hit for some reason, these will need to be added back.
This PR also removes the leniency from the Upper Norfair Farming Room gate glitch strat, due to the availability of the good farm right next to the gate.
> Add helpers for X-mode leniency

- .gitignore
- scripts/autoformat.py
- scripts/format_json.py
This PR adds a script (and library) that can be used to automatically format all the region JSON files in a standardized way.
The main goal of this is to prepare the way to making large-scale changes using tools that operate on the JSON data abstractly, such as splitting apart the region files into separate room files. A secondary purpose is that it cleans up our formatting, ironing out inconsistencies in the use of whitespace.
Note that the script includes a validation to ensure the reformatting is correct: each output parses to an object equivalent to the input.
To run the auto-formatting locally, run "python autoformat.py" from a working directory of `sm-json-data/scripts`.
This PR includes the script only. Afterward a separate PR will apply the output of the script (PR #1115). By …
> Create script for auto-formatting the JSON

- region/brinstar/green.json
The slash in the name was going to create a problem when we split region files into room files. Also, this way the room name now matches the name in the Wiki (https://wiki.supermetroid.run/Green_Brinstar_Main_Shaft).
> Change room name of green brin main shaft

- region/maridia/inner-green/Oasis.json
I was working on Oasis, when we realized that a `reusableRoomwideNotable` needed to be added to one of the strats, so it's a very small PR with a bit of the runway migration included
> A Couple Quick Changes to Oasis

- region/brinstar/green/Etecoon Energy Tank Room.json
This room had a bug (which has come up in at least a couple seeds reported in the Map Rando Discord) where there were "canLeaveCharged" strat on the bottom left door using the runway on the top, but without an "initiateRemotely". So that gets fixed in this PR.
> Runway migration: Etecoon ETank Room

- region/brinstar/green/Etecoon Save Room.json
- region/brinstar/green/Etecoon Super Room.json
- region/brinstar/green/Green Brinstar Beetom Room.json
- region/brinstar/green/Green Brinstar Fireflea Room.json
Green Brinstar Beetom Room had the runways as free, which was unsound. Added an obstacle to track the Beetoms being dead or frozen.
In Green Brinstar Fireflea Room, I migrated the left-side X-mode leaveShinecharged, but skipped the right-side one, because it seems like short-charging using the 17-tile runway connected to the door would be easier?
> Runway migration: a few more Green Brin rooms

- scripts/rename_room_diagrams.py
This implements @kjbranch's proposal to put the room ID at the end of the room diagram filename, so that the order of these filenames (when sorted alphabetically) will be consistent with that of the room JSON files.
Run it locally by executing `python rename_room_diagrams.py` from a working directory of `scripts/`. The output should be committed in a separate PR.
> Add script to rename room diagrams

- region/brinstar/red/Red Tower.json
- region/maridia/inner-yellow/Butterfly Room.json
- region/region-readme.md
- schema/m3-room.schema.json
- strats.md
As part of the cross-room strat migration, this PR makes the necessary schema changes to allow converting "bypassStrats" (in of `node/locks`) into regular strats. This also allows more types of door-lock bypass strats to be expressed, since a bypass strat could now start at any node, not necessarily only at the door node that it exits through. A couple examples are included: one for migrating the Butterfly Room gray lock bypass strat, and another for a Very Deep Stuck X-Ray climb in Red Tower that wouldn't have been expressible before.
At some point we will also want to migrate "unlockStrats", e.g. to help us more accurately represent requirements to unlock doors where heat, lava, acid, and/or enemies are a factor; this is more complicated, because it can depend on the door color, meaning …
> Schema change for migrating door-lock bypass strats

- region/norfair/east/Bubble Mountain.json
Odd that the tests didn't catch this. I guess the tests would see "Wave+Spazer" in weapons.json and assume it would be a valid logical requirement.
> Fix malformed 'Wave+Spazer' req in Bubble Mountain

- schema/m3-room.schema.json
- scripts/gmode_migration.py
This script will not migrate strats with "comeInWithGMode" in a few cases:
- if there are multiple in the same strat
- if there are multiple fromNodes
- if it is not at the top level of "requires" (e.g. inside an "or")
Those cases will generally need to be manually migrated, splitting the strat into multiple strats.
Aside from that, everything should be covered: "leaveWithGModeSetup", "leaveWithGMode", "gModeImmobile", and occurrences of "comeInWithGMode" other than those exceptional cases.
This PR also makes "morphed" be a required property of "leaveWithGMode"; it was required in the old schema, and I think we want to keep it that way. Often "leaveWithGMode" strats should come in pairs, one with "morphed" false and one with "morphed" true, and it would be easy to make a mistake by …
> Create script to mostly automate the G-mode cross-room migration

- schema/m3-room.schema.json
- scripts/remove_notable_false.py
This changes the room schema to make "notable" an optional property which only needs to be specified if it is "true". A script is created which can then strip out `"notable": false` from all the strats.
> Make notable false by default, create script to remove notable false

- region/tourian/main/Big Boy Room.json
- region/tourian/main/Blue Hopper Room.json
- region/tourian/main/Dust Torizo Room.json
- region/tourian/main/Lower Tourian Save Room.json
- region/tourian/main/Metroid Room 1.json
- region/tourian/main/Metroid Room 2.json
- region/tourian/main/Metroid Room 3.json
- region/tourian/main/Metroid Room 4.json
- region/tourian/main/Rinka Shaft.json
- region/tourian/main/Seaweed Room.json
- region/tourian/main/Tourian Escape Room 1.json
- region/tourian/main/Tourian Escape Room 2.json
- region/tourian/main/Tourian Escape Room 3.json
- region/tourian/main/Tourian Escape Room 4.json
- region/tourian/main/Tourian Eye Door Room.json
- region/tourian/main/Tourian First Room.json
- region/tourian/main/Upper Tourian Save Room.json
For Tourian Blue Hopper Room, I was experimenting for a while with a strat to lure both Hoppers to the right when entering from the top, to be able to do a Crystal Flash safely on the left. It works a lot of the time but I wasn't able to find a consistent setup yet so I didn't add that one. The one entering from the left though seems very reliable.
> Tourian Crystal Flash strats

- region/brinstar/green/Etecoon Energy Tank Room.json
This is the strat that just falls down through the crumble blocks. Somehow I accidentally deleted it during the runway migration.
> Adding missing Base strat in Etecoon ETank Room

- region/crateria/west/Gauntlet Entrance.json
- region/maridia/outer/Mt. Everest.json
- schema/m3-room.schema.json
- strats.md
This addresses issue #1185 by adding a new property `position` to the exit/entrance conditions `leaveWithSpark`/`comeInWithSpark`. Only horizontal sparks are considered for now, and the new `position` property indicates the vertical position in the doorway during the transition. Just having two positions `top` and `bottom` appears to be precise enough to model everything that we need (for now).
The new property is applied in Gauntlet Entrance and Mt. Everest, fixing the example of unsound logic mentioned in the issue.
> Schema changes to represent cross-room spark position

- logicalRequirements.md
- region/tourian/main/Metroid Room 2.json
- region/tourian/main/Rinka Shaft.json
- region/wreckedship/main/Electric Death Room.json
- region/wreckedship/main/Wrecked Ship Main Shaft.json
- schema/m3-requirements.schema.json
This also makes a schema change to add a "autoReserveTrigger" logical requirement, which is necessary to represent some of the strats. This should also be useful in other places, e.g. to allow us to represent double damage boost strats.
After using Crystal Flash in direct G-mode, X-Ray no longer works, so the auto-reserve trigger is used as an alternative way to cancel G-mode and allow X-Ray to be used.
> Rest of Very Deep Stuck strats

- scripts/autoformat.py
It was set up to work on region files, which no longer exist.
> Update auto-formatting script to work on room files

- region/crateria/central/Climb.json
- region/crateria/central/Crateria Super Room.json
- region/crateria/central/Crateria Tube.json
- region/crateria/central/Final Missile Bombway.json
- region/crateria/central/Flyway.json
- region/crateria/central/Landing Site.json
- region/crateria/central/Parlor and Alcatraz.json
- region/crateria/central/Pit Room.json
- region/crateria/central/Pre-Map Flyway.json
This PR was based off of #1212. It contains the output of the g-mode migration script with a thorough review and a few small edits. Only errors in the migration itself are included, not errors in the strats (unless severe), new strats, nor strats from non-door nodes. Those will be included in a follow up PR.
Edits included in this PR:
- Strats with a leave with g-mode have problems in that their `requires` is before the `entrance condition` instead of after it. (Crateria Tube)
- Places with multiple strats in a `leave with gmode setup` with a devnote are split and the note is duplicated. This is expected, but not ideal. (Parlor)
- There was a major error in one strat which included a `{"not": "f_ZebesAwake"}`, but neglected `canRiskPermanentLossOfAccess`.
Edits that will be included in a …
> G-Mode Migration: Crateria Central Pt. 1

- region/brinstar/kraid/Kraid Room.json
Without being able to wall jump, the fight is much harder. Using the platforms can be particularly annoying without being able to dodge while shooting. A crouch jump + down grab is possible, but at low difficulties it doesnt really seem easier than using the platforms (at higher difficulties it seems easier).
> Update Kraid Fight

- region/brinstar/green/Spore Spawn Kihunter Room.json
Using the full 32 tiles of runway to get a shinecharge makes it not really practical to get up the steps with any frames remaining (technically possible, but hard and pointless). So this PR rewrites the strat to require a 25-tile charge, to leave room to gain run speed to jump up the steps. 
I think the movement here goes beyond expectations of "canShinechargeMovement", so this PR changes it to "canShinechargeMovementComplex". And the frames remaining are increased significantly, which for example will put it in logic to be used with Reverse Croc Speedway.
> Refine leaveShinecharged in Spore Spawn Kihunter Room

- region/crateria/central/Crateria Tube.json
- schema/m3-room.schema.json
- strats.md
- tests/asserts/keywords.py
This PR updates the schema and docs to support representing strats that enter a room with a shinecharge and leave with a shinecharge. This is done by putting both a `comeInShinecharged` entrance condition and a `leaveShinecharged` exit condition on the strat, where a new "auto" value is used on the `framesRemaining` of the `leaveShinecharged` to indicate that the final frames remaining should be inferred by subtracting the amount of frames required in the `comeInShinecharged` from the amount of frames remaining on entry.
I also added some details on expectations for Samus' position and momentum during the door transition in strats with `comeInShinecharged` and `leaveShinecharged`. Hopefully it aligns reasonably well with what we have already been doing; if not it could probably be …
> Add support for carrying a shinecharge between 3 rooms

- region/norfair/west/Crocomire Speedway.json
Tightening the shinecharge frames here since they were fairly loose, and this seemed like an important strat. 
Increased the shinespark frames by a couple since we're no longer assuming you have to get all the way next to the speed blocks before sparking.
I'm planning on implementing leniency for cross-room shinecharge frames probably in the next release of Map Rando, so this is part of why I'm thinking it can a good time to start moving toward tighter shinecharge frames where possible.
> Tighten Reverse Croc Speedway shinecharge frames

- region/brinstar/red/Red Tower.json
This adds alternative, easier shinespark strats for getting up the top of Red Tower without the hero shot. These need Ice in order to get the rest of the way up, but they have lower requirements in terms of tech, energy, and shinecharge frames. In particular they allow getting up without a tank, whereas the hero shot method requires a tank.
> Red Tower top: easier shinespark strats

- region/maridia/inner-green/Shaktool Room.json
Newer players are often unaware that it is possible to do Shaktool Room in reverse. So this seems like a knowledge check belonging as a Medium notable, similar to reverse Botwoon (with Wave+Charge)
> Make reverse Shaktool strat notable (for Medium)

- region/lowernorfair/west/Screw Attack Room.json
Can be done with as low as 1.4375 tiles. It may also be doable with shorter runways with a `canMidairWiggle`, but I figure these can be added when this room is migrated.
> Update Screw Attack Transition Jump

- region/brinstar/blue/Blue Brinstar Boulder Room.json
- region/brinstar/blue/Construction Zone.json
- region/brinstar/kraid/Warehouse Entrance.json
- region/brinstar/kraid/Warehouse Kihunter Room.json
- region/brinstar/pink/Big Pink.json
- region/brinstar/pink/Dachora Room.json
- region/brinstar/pink/Waterway Energy Tank Room.json
- region/brinstar/red/Red Brinstar Fireflea Room.json
- region/brinstar/red/Red Tower.json
In addition to adding `unlocksDoors` there are a couple more little things:
- A new "Speedy Airball" strat in "Blue Brinstar Boulder Room" (pointed out by insomniaspeed).
- Fix to Red Tower 1 -> 5 "Leave with Moondance" strats; it seemed to be missing requirements for how to get to the top of the room; freezing the Rippers alone is not enough.
> Brinstar unlocksDoors

- region/maridia/outer/Glass Tunnel.json
- region/maridia/outer/Mt. Everest.json
Everest
- Reduce unnecessary requirements from the old schema which were used to leave at 6
- Reduce duplication by adding a g-mode node at 6
- Add more options for setting up g-mode out the top 3 doors
- Fix some errors and add some strats
Glass Tunnel
- Migrate strats with multiple fromNodes
- This was difficult, as g-mode strats must start at a door, but flag yielding strats must start at event nodes
- Add an obstacle to fix these and remove a now unnecessary node (still need to update the room diagram)
> Add G-Mode Strats to Everest and Glass Tunnel, Update Glass Tunnel

- region/maridia/outer/Main Street.json
Simply migrated the strats with multiple `fromNodes`, without making other edits besides a missing gravity jump to enable traversing the whole room with Gravity alone.
> Simple G-Mode Migration: Main Street

- region/lowernorfair/east/Pillar Room.json
The acidless way of crossing the room with Power Bombs were put in a FIXME since I want to attach a harder version of `canTrickyJump` to them.
3PBs was made not notable and Gravity or suitlesslavadive seems fair.  Numbers are a little bit lenient.
2PBs still requires knowing where to put the Power Bombs, `Very Hard` seems wasteful since it can be done with less, but at `Hard` it overlaps with 3PBs a lot.
> Lower Norfair Pillar Room

- region/crateria/central/Landing Site.json
- region/norfair/west/Crocomire Speedway.json
This came up in a seed today that Eddie and others raced: the logic thought sparking from Landing Site into Reverse Croc Speedway was possible, when it's not. Probably we need to take a close look at all the cross-room shinespark strats to see if there are others that need position constraints.
> Add position constraints to a few shinesparks

- region/tourian/main/Tourian Escape Room 4.json
- strats.md
This also adds item requirements (Morph + Bombs) that appear to have been missing in the right-to-left strat "Tourian Escape Room 4 IBJ and Acid Bath".
Also adds a shinespark strat (coming in shinecharged) for getting up left->right walljumpless.
> Add spring ball jump and IBJ options for Tourian Escape 4 L->R

- region/maridia/inner-yellow/Watering Hole.json
- Added a frozen Choot strat.
- Split off crouch-jump down-grab into its own strat, and upgraded the "canCarefulJump" requirement to "canTrickyJump". The positioning has a few pixels of leniency, but the required precision in timing the forward press and down grab seems more difficult than "Medium". It could maybe be "Hard" if there were a suitable tech for it.
> Refine Base strat for getting out of Watering Hole

- region/brinstar/green/Green Brinstar Main Shaft.json
- tests/asserts/keywords.py
This cleans up the remaining two "missing unlocksDoors" warnings, and upgrades the warnings to errors going forward.
Using a "bypassesDoorShell" in the these "Carry G-mode Back through the Door" strats is a little awkward, since this comes with an implicit "canSkipDoorLock" tech requirement which doesn't make sense, since the door not closing means the lock simply does not come into play. But putting an "unlocksDoors" here wouldn't be valid since in fact there is no opportunity to unlock the door while passing through the room. Possibly the solution could be to remove "canSkipDoorLock" from being an implicit tech on "bypassesDoorShell" strats, and instead add it explicitly in the cases where it makes sense; alternatively, we could provide some way to override it in strats like these to …
> Use errors in tests for missing unlocksDoors

- region/maridia/inner-pink/Botwoon Energy Tank Room.json
Funny that this one went uncaught for so long. It didn't affect Map Rando before, because of how both exits went to the same room (Botwoon Quicksand Room), but that will no longer be the case with the new upcoming map pools.
> Fix Botwoon ETank sand transition addresses which were swapped

- region/maridia/outer/Mt. Everest.json
Getting up with a Gravity jump is already in logic, so this strat doesn't add a lot. But in some applications Gravity jump might not be possible (e.g. if using vanilla equipment screen). This crouch jump down-grab is also faster than a Gravity jump, so it doesn't hurt to have it documented.
> Add tricky crouch jump down-grab in Everest

- region/wreckedship/main/Attic.json
- region/wreckedship/main/Basement.json
- region/wreckedship/main/Wrecked Ship East Super Room.json
- region/wreckedship/main/Wrecked Ship Main Shaft.json
- region/wreckedship/main/Wrecked Ship Map Room.json
- region/wreckedship/main/Wrecked Ship Save Room.json
I was using `canInsaneJump` as a proxy for annoying positioning of Coverns. I wonder if we should instead have a second tech `canTrickyEnemyExtendRunway`?
> Wrecked Ship Enemy Extend Runways

- region/crateria/central/Parlor and Alcatraz.json
This is based on bobbob's recent set of videos: https://www.youtube.com/playlist?list=PLUMF22jq7du3IWFXDwoBa3Tdw10kFUjQ2.
I tested all of these to figure out tech requirements. The G-mode forced stand-up clip seemed particularly tough, given the potentially lengthy setup required for a single attempt (which requires a frame perfect jump?), though it could just be I'm not practiced at it.
The HiJump ceiling clip was interesting; it's different from a normal frozen enemy ceiling clip, and it turned out to be more forgiving than I was expecting.
> Add/refine Alcatraz Escape strats

- region/brinstar/pink/Pink Brinstar Power Bomb Room.json
This also adds more detail to the description of the existing strat.
I tried for a while to get the moonfall with frozen Hoppers here, but I couldn't get it. So I'm not adding that one here. Bobbob had mentioned it is possible to get down to the item that way (without Supers), and even possible to get into the tunnel below (bypassing the bomb blocks): https://discord.com/channels/1053421401354285129/1053436236628496454/1160249351512268820.
> Add more Mission Impossible strats

- region/brinstar/green/Spore Spawn Kihunter Room.json
- region/crateria/east/Crateria Kihunter Room.json
- region/lowernorfair/east/Red Kihunter Shaft.json
- region/lowernorfair/east/Three Musketeers' Room.json
- LN KiHunters didn't seem to get all drops rolled into missiles once everything else was full.  It was like 25% missile rate.
- Kraid Kis is a good good missile farm if your health stays full and with a strong weapon
> Remove some kihunter farms

- region/maridia/inner-green/East Sand Hall.json
This adds a spring ball jump option (in combination with Ice) to get from right to left. Also adds an option to avoid Evir damage and Power Bomb usage going from the center to left. See insomniaspeed's video: https://discord.com/channels/1053421401354285129/1053436236628496454/1189600996469514340. I also tested that avoiding Evir damage and PB usage is possible when entering from the sandfall above, by entering the room with a jump, freezing the first Evir on the way down, and avoiding bringing the second Evir on camera until after landing.
Similar to how other 2->4 strats are done in this room, the new Spring Ball strat mainly only includes the requirements to get to the first pillar, since getting from there to the center is considered to be free relative to the requirements to get from …
> East Sand Hall Spring Ball jump right-to-left

- logicalRequirements.md
- schema/m3-requirements.schema.json
This adds a new logical requirement `resourceAvailable` analagous to `resourceCapacity` but based on the current amount of resources not capacity.
I was thinking this could be useful to refine the logic in Metal Pirates Room, i.e. to add strats for killing both pirates with only 5 Supers, based on the assumption that you get at least one Super dropped (given enough energy to be out of health bomb range), or tankless with shinespark echoes, based on the assumption that you will get enough health drops to survive. I don't think I'm experienced enough with the room to be able to add the strats, but @osse101 maybe sometime you could? It seems like this room is currently one of the most common sources of "easy" sequence breaks on Challenge seeds.
> Add resourceAvailable to schema

- logicalRequirements.md
- schema/m3-requirements.schema.json
This is following up on your idea @osse101 about a `resourceFull` requirement. I think this generalization `resourceMissingAtMost` can be useful in a other situations too. For example we could use it to refine some of the farming strats, e.g. their patience requirements based on how long the refill would take. It's still limited by the fact that we're still only representing full refills, but it could allow quite a bit of improvement by putting limits on it, e.g. so you don't end up needing to spend 10 minutes refilling energy in LN Firefleas on vanilla map.
> resourceMissingAtMost requirement

- region/norfair/crocomire/Post Crocomire Jump Room.json
The walljump requirement here isn't needed; somerando figured this out a while ago: https://youtu.be/9t2AWPOJNYQ?list=PLMfL5HDn1Tf6wtTlVNGcwCUMdUYDWUbLd&t=3818.
> Remove walljump req from Indy Jones Long Mella

- region/norfair/west/Business Center.json
This was already a complicated room for cross-room shinecharge strats, but there was quite a bit of opportunity to add more strats:
- Carry Shinecharge strats (i.e. comeInShinecharged/leaveShinecharged), which couldn't be represented before
- More variations based on different movement options (HiJump/walljump)
- Some more options which spark out rather than leave shinecharged
- In-room shortcharge strats (which are basically variations of the the full-runway comeInShinecharging strats from node 3; the strats and their requirements correspond exactly, aside from how unlocked doors affect the runway length).
I had trouble with the [6, 2] strats where the note said to down-back and shoot the Sova to delay its movement. Sometimes I could manage to down-back to squeeze past the Sova (with or …
> Business Center shinecharges

- region/crateria/central/Climb.json
This is for a cross-room spark right-to-left to break the bomb blocks at the bottom of Climb. It needs to be done in bottom position since otherwise you would bonk a floating platform. This fixes a bug reported by Anozilla from a recent seed: https://discord.com/channels/1053421401354285129/1053434704180805744/1213965619452579931
> Add spark position constraint in Climb

- region/lowernorfair/east/Pillar Room.json
- region/lowernorfair/east/The Worst Room In The Game.json
This is just a quick attempt to address some of the hardest uses of Power Bombs in heated rooms with tight Reserve management. This would move these strats from `VH` to `Expert` in Map Rando if the player has no E-Tanks.
There are other heated rooms that require using Power Bombs, but I don't think they are on the same level of difficulty with precise movement while placing the PBs and triggering reserves:
Right side of Single Chamber, LN Springball Maze, Three Musketeers, Screw Attack, Mickey Mouse, LN Kihunter, Wasteland, Pillar Setup, GT right item
@osse101, what are your thoughts on something like this: is it useful, should it be included in more rooms, should there be a `canInsaneJump` alternative?
> Tricky Heated Power Bombs with Reserves Only

- helpers.json
- region/crateria/central/Bomb Torizo Room.json
By overriding this helper, we can make Chozos objective work more precisely in Map Rando, e.g. when using "Stop item placement early". Currently the logic would require placing Bombs.
> Add helper for Bomb Torizo activation

- region/maridia/outer/Main Street.json
This adds a simple strat that was missing: For height-6 platforms (like in Basement, Crab Maze, etc.), you can just spin-jump to make it up onto the ledge on the left at the bottom of Main Street.
The Frozen Fish strats here were a little messed up: their "height" requirements were swapped between the crouch-jump vs. no-crouch-jump versions. One of them (the height 6, no-crouch-jump one) gets obsoleted by the new strat. The other one (height 7) I fixed up a bit, relaxing its position requirements so that it now also applies to jumping from the PCJR Power Bomb blocks (in addition to Tourian Escape Room 2).
> Add missing cross-room jump up Main Street

- region/maridia/inner-yellow/Kassiuz Room.json
- region/maridia/inner-yellow/Maridia Elevator Room.json
Kewlan recently noticed these X-ray climb strats were missing in Maridia Elevator room. Then I checked and noticed that Kassiuz Room is missing one too (requiring deep stuck).
> X-Ray climbs in Maridia Elevator and Kassiuz Room

- region/lowernorfair/west/Screw Attack Room.json
This adds a strat for spring ball jumping from the doorway to the top of Screw Attack Room, with HiJump (where blocks are already broken). This was something that Kewlan recently noticed was missing. I also saw that the heat frames on the "Doorway Speedjump" strat were very lenient, so I tightened them up to some extent. 
Probably other strats in the room could also use another look at the heat frames; I also notice there's no canDoubleBombJump strat, but I'm not skilled enough to work that out.
> Screw Attack Room spring ball jump

- connection/norfair/east.json
This is the connection between Lower Norfair Elevator (ID 309) and Lower Norfair Elevator Save Room (ID 310), both in East Norfair.
> Fix an incorrect area in one specific connection

- region/maridia/outer/Mt. Everest.json
- schema/m3-room.schema.json
- strats.md
- tests/asserts/keywords.py
This PR sets up the schema to represent vertical cross-room strats (e.g. jumps, G-mode setups, etc.) that pass through the Toilet. For now it just adds one example strat, the Mt. Everest one that was discovered/shared this morning by 123456789you123456789 on the Discord (https://discord.com/channels/1053421401354285129/1053436236628496454/1220378509046841468).
> Add comesThroughToilet strat property

- region/maridia/inner-yellow/Plasma Spark Room.json
This adds a new unmorph bomb boost strat that I just noticed is possible here. Also splits the existing "Frozen Choot" strat into two separate strats, one for the walljump (Basic) and one for the speedy spring ball jump (Very Hard). The latter had a "canTrickyDashJump" requirement, but this seems unnecessary since essentially any speedy jump off the Choot works (as long as it's frozen reasonably high); so I replaced that "canTrickyDashJump" requirement with a "canTrickyJump".
> Plasma spark bomb boost

- region/lowernorfair/east/Lower Norfair Farming Room.json
- region/lowernorfair/east/Plowerhouse Room.json
There are very few here. 
I skipped only a couple:
- Left door of Plowerhouse is kind of a pain and it has so many different entrance behaviors. Generally it looks like you need to kill the first two and bring the third Holtz.
- ~~Bottom door of Acid Statue room can have a +4 pixel freeze, which could be useful for a cross room jump but not a shinecharge.~~ +4 is never useful
> Frozen Enemy Runways in Lower Norfair

- region/lowernorfair/east/Three Musketeers' Room.json
Some of the strats that killed Kihunters from top to bottom assumed the top would be left alive. This was a problem because these were clearing obstacle "A", which meant the strats going back from bottom to top would assume they were all three dead.
If we want to correctly model leaving the top one alive, we would probably need to add another obstacle and take it into account in the strats that go back up. But it wasn't clear if this would be useful. So I simplified the strats to assume you kill all 3 or none at all.
Also checked the heat frames for the top-to-bottom strats and tightened some of them. Removed an unnecessary "Morph" requirement from the dodging strat going down; Morph will be needed anyway to do anything at the bottom of the room but it's not used as part of this strat. …
> Refine some Three Musketeers strats

- region/lowernorfair/east/Mickey Mouse Room.json
This tightens the heat frames at the top of the room (between the top door and the item), some of which were pretty loose before.
Also removes node 5, which is no longer needed since obstacles "A" and "B" were added.
This needs a room diagram update, which @kjbranch mentioned he can do.
> Refine top of Mickey Mouse

- region/brinstar/red/Red Brinstar Fireflea Room.json
- region/crateria/central/Climb.json
- region/maridia/inner-pink/Botwoon's Room.json
- region/maridia/outer/Main Street.json
- region/tourian/main/Metroid Room 1.json
- region/wreckedship/main/Bowling Alley.json
- region/wreckedship/main/Wrecked Ship Energy Tank Room.json
- tech.json
I'm adding this in hopes that it will be used as a `Beyond` tech in Map Rando. 
Alternatively/additionally, I wouldnt be opposed to a `canLongCeilingBombJump`, which could be `Beyond` and have a lower threshold (i.e. 2 screens instead of 4).
> Add canBeExtremelyPatient, canLongCeilingBombJump, G-Mode in Red Firefleas

- region/brinstar/blue/Construction Zone.json
- region/brinstar/green/Early Supers Room.json
- region/brinstar/green/Etecoon Energy Tank Room.json
- region/brinstar/green/Green Brinstar Beetom Room.json
- region/brinstar/red/Red Brinstar Fireflea Room.json
- region/crateria/central/Crateria Super Room.json
- region/crateria/central/Crateria Tube.json
- region/crateria/central/Parlor and Alcatraz.json
- region/crateria/east/The Moat.json
- region/crateria/west/Green Pirates Shaft.json
- region/maridia/inner-green/West Sand Hall Tunnel.json
- region/maridia/inner-pink/Halfie Climb Room.json
- tech.json
This introduces a new tech "canGrappleBombHang", with a grapple teleport setup from the top right of Halfie Climb using it. It wasn't as bad as I was expecting. It's different but seems not necessarily harder than the Moat setup.
I'm planning on going through the rest of the rooms to add all the applications (from this door) but figured it could make sense to start with a smaller PR to get feedback.
This setup has a little more nuance because it looks like that there are multiple ways to enter the transition (e.g. by varying your momentum) which can slightly affect your position in the next room, so we'll have to be careful with that. Also this setup has the ability to bypass door shells and even chain the grapple teleport into subsequent rooms.
> Some grapple teleports from Halfie Climb

- region/brinstar/blue/Construction Zone.json
- region/brinstar/green/Green Brinstar Beetom Room.json
- region/brinstar/red/Red Tower.json
- region/crateria/central/Crateria Tube.json
- region/crateria/west/Green Pirates Shaft.json
- region/lowernorfair/east/Red Kihunter Shaft.json
- region/lowernorfair/west/Screw Attack Room.json
- region/maridia/inner-green/West Sand Hall Tunnel.json
- region/maridia/inner-pink/Draygon Save Room.json
- region/maridia/inner-pink/Halfie Climb Room.json
- region/maridia/inner-pink/West Cactus Alley Room.json
- region/maridia/inner-yellow/Bug Sand Hole.json
- region/maridia/inner-yellow/Butterfly Room.json
- region/maridia/inner-yellow/Plasma Tutorial Room.json
- region/maridia/outer/Crab Hole.json
- region/maridia/outer/West Glass Tube Tunnel.json
- region/norfair/east/Bat Cave.json
- region/norfair/east/Frog Savestation.json
- region/norfair/east/Lower Norfair Elevator.json
- region/norfair/east/Nutella Refill.json
- region/wreckedship/main/Gravity Suit Room.json
This adds strats for chaining grapple teleports across multiple rooms, starting from Halfie Climb Room top right door.
For Crab Hole and Crateria Tube, I put `bypassesDoorShell: true` because even though there is no door shell, these strats would bypass a door shell if one were there (e.g. in case a randomizer were to add one).
> Add 'Carry Grapple Teleport' strats

- region/wreckedship/main/Wrecked Ship Energy Tank Room.json
This came up in Oats' seed tonight where you had to use Grapple to get this item and get out without taking a hit. It was an Extreme seed but it could have happened in Hard.
I'm not sure if I completely understand this strat. For some reason, to me going left-to-right seems way easier than going right-to-left, even though the geometry is symmetric so I would have expected them to be basically the same. A lateral mid-air morph seems to help a lot with going right-to-left but not really with going left-to-right.
> Refine WS ETank grapple fling

- region/norfair/east/Frog Speedway.json
- region/norfair/west/Crocomire Speedway.json
- region/wreckedship/main/Bowling Alley.json
Pixel perfectly crystal flashing + counting to 175 is easier than the jump you had to do to break only the middle block in a Speed block wall.
> Revisit Crystal Flash Moondances

- region/maridia/inner-pink/Colosseum.json
Spiffy came up with this strat the other day in one of his seeds:
https://clips.twitch.tv/RepleteGeniusRabbitHassanChop-ng1dgYjhS-MVH-Il
Compared to the Insane "Colosseum with no Equipment" strat, this version uses one less spike hit, and it avoids the final spike jump which was the insanely difficult part. Escaping the water with the spring ball jump into IBJ is precise but can be retried as many times as needed. I put "canInsaneJump" on it since the frame-perfect bomb placement (2 frames before the spring ball jump) makes it probably take a while to get, given that you have to pause/unpause twice with every attempt.
> Colosseum bomb jump water escape by Spiffy

- region/tourian/main/Metroid Room 1.json
- region/tourian/main/Metroid Room 2.json
- region/tourian/main/Metroid Room 3.json
- region/tourian/main/Metroid Room 4.json
Some wacky `MetroidFrames` counts happened.  I treated metroids like they didn't exist when canMetroidAvoid wasn't there.
> Metroid Rooms

- region/crateria/central/Climb.json
- region/crateria/central/Crateria Super Room.json
- region/crateria/central/Crateria Tube.json
- region/crateria/central/Final Missile Bombway.json
- region/crateria/central/Flyway.json
- region/crateria/central/Landing Site.json
- region/crateria/central/Parlor and Alcatraz.json
- region/crateria/central/Pit Room.json
- region/crateria/central/Pre-Map Flyway.json
- region/crateria/east/Bowling Alley Path.json
- region/crateria/east/Crab Maze.json
- region/crateria/east/Crateria Kihunter Room.json
- region/crateria/east/East Ocean.json
- region/crateria/east/Forgotten Highway Elbow.json
- region/crateria/east/Forgotten Highway Kago Room.json
- region/crateria/east/Homing Geemer Room.json
- region/crateria/east/The Moat.json
- region/crateria/east/West Ocean.json
- region/crateria/west/Gauntlet Energy Tank Room.json
- region/crateria/west/Gauntlet Entrance.json
- region/crateria/west/Green Pirates Shaft.json
- region/crateria/west/Statues Hallway.json
- region/norfair/crocomire/Post Crocomire Farming Room.json
- schema/m3-room.schema.json
- strats.md
- tech.json
- tests/asserts/keywords.py
This adds some new stuff relating to cross-room temporary blue strats:
- A new exit condition `leaveWithTemporaryBlue`, in order to represent strats that leave a room with temporary blue using methods other than using a runway connected to the door (e.g. by chaining temporary blue from a runway elsewhere in the room).
- A new tech `canLongChainTemporaryBlue`.
- A new `direction` property in the `comeInWithTemporaryBlue` entrance condition, since for vertical transitions the direction that Samus is facing can be important (e.g. if X-Ray is not available to turn around).
- Applications in Crateria (and one random instance in Post Croc Farm Room).
Currently I'm not adding `comeInWithTemporaryBlue` + `leaveWithTemporaryBlue` strats, because that would allow arbitrarily long chains, which …
> Crateria temporary blue strats

- region/brinstar/pink/Waterway Energy Tank Room.json
Recently added obstacle "A" to this room but forgot to put "clearsObstacle" on the shinespark strat from the platform. So this has been making the logic think the item would only be one-way reachable that way.
Noticed it from the spoiler map on Andy's seed today.
> Waterway spark fix

- schema/m3-room.schema.json
- strats.md
- tests/asserts/keywords.py
This will resolve #1086.
Earlier I was resistant to add these because it requires adding extra nodes on the randomizer side to deal with them. But we're going to have to do that kind of thing anyway in order to handle door locks properly, so I no longer see a reason not to do this. Given that we have `unlocksDoors` on strats (and `clearsObstacles`, etc.), it only seems natural to have `collectsItems` and `setsFlags`. Eventually I would like if all the flags could be set using `setsFlags` in this way, and then we could remove flag nodes and their associated locks/yields (the way that flags are currently getting set), as part of the long-term goal of migrating strats away from being embedded inside "node" properties and into the room "strats" list instead.
> Add collectsItems and setsFlags

- region/brinstar/green/Spore Spawn Kihunter Room.json
- region/brinstar/kraid/Warehouse Zeela Room.json
- region/crateria/central/Climb.json
- region/crateria/east/Crab Maze.json
- region/crateria/east/Forgotten Highway Elevator.json
- region/crateria/east/Red Brinstar Elevator Room.json
- strats.md
Currently it is always assumed that you can return through a door in g-mode unless there is a spawn-at. After this, I want it to not implicitly assume that for the bottom of a vertical door.
This is for Crateria and Brinstar.
> G-Mode Bottom of Vertical Doors

- region/crateria/central/Crateria Super Room.json
I believe this is too long too low of an angle for `canDiagonalBombJump`. This was expected on Spiffy's recent seed, which caused some confusion. 
I also checked all other uses of `canDiagonalBombJump`, which looked fine. And added `canLongCeilingBombJump` here, as it is 2 screens wide.
>  Remove Diagonal IBJ from Crateria Supers

- region/brinstar/green/Green Brinstar Main Shaft.json
Looks like this was the only strat using the tech "canXRayCeilingClip" instead of the helper "h_canXRayCeilingClip".
> Fix X-Ray version of bottom Green Brin Main Shaft ice clip

- region/ceres/main/58 Escape.json
- region/ceres/main/Dead Scientist Room.json
- region/ceres/main/Falling Tile Room.json
- region/ceres/main/Magnet Stairs Room.json
I skipped the Ceres Ridley and Ceres Elevator rooms, as the practice hack wasn't working for them. These rooms are kind of cool and it would be fun to use them someday.
> Ceres: Add G-Mode, PB Doors

- region/norfair/east/Volcano Room.json
Took a full second off Base (best time is exactly 7 seconds), and nearly a second off space jump (best time 6seconds 42 frames) However I could not get the additional time for not mockballing below 34 frames. Taking 40 frames for the runway was accurate.
> Tightened Volcano Room Heat Frames

- region/lowernorfair/east/Amphitheatre.json
- region/tourian/main/Blue Hopper Room.json
- tests/asserts/keywords.py
- Add tests so we don't forget to add `unlocksDoors` on strats ending at door nodes with `"useImplicitDoorUnlocks": false`.
- Make these tests pass by adding at least rudimentary `unlocksDoors` in the places where it was missing.
- In Amphitheatre:
- Remove obsolete "h_canNavigateHeatRooms"
- Add `obstaclesCleared` or `obstaclesNotCleared` to more cleanly separate the acid vs. no-acid strats.
- Split off `gravitylessHeatFrames`/`gravitylessAcidFrames` in the Gravity jump strat. The total frame count seemed loose (even with Screw Attack, the slowest method of killing the Pirate), but I didn't try to tighten it because I wasn't confident about the intended starting position of the strat.
- Strats for unlocking the left door with Missiles or Power Bombs could be possible, but they are …
> Some clean-up in rooms with useImplicitDoorUnlocks false

- logicalRequirements.md
- readme.md
- schema/m3-requirements.schema.json
- schema/m3-tech.schema.json
- tech.json
This is the first step towards adding items back to tech (i.e. morph to canIBJ); then `h_canArtificialMorphIBJ` can be defined as `{"tech": "canIBJ"}`.
> Split tech requirements into two fields: tech and other

- region/lowernorfair/east/Metal Pirates Room.json
- tech.json
- tests/asserts/keywords.py
`canFarmWhileShooting` was intended more for other rooms where you shoot things that aren't on screen yet.  
The instances where you can heal all of the heat damage taken was split in two to allow for lower available energy.
> Metal Pirate Low Resource Strats

- region/brinstar/blue/Blue Brinstar Energy Tank Room.json
- region/brinstar/green/Green Hill Zone.json
- region/brinstar/pink/Big Pink.json
- region/crateria/central/Crateria Super Room.json
- region/crateria/central/Landing Site.json
- region/crateria/east/West Ocean.json
- region/crateria/west/Green Pirates Shaft.json
- region/maridia/inner-pink/Aqueduct.json
- region/maridia/inner-yellow/Maridia Elevator Room.json
- region/maridia/outer/Crab Hole.json
- region/maridia/outer/Mt. Everest.json
- region/norfair/crocomire/Post Crocomire Farming Room.json
- region/norfair/crocomire/Post Crocomire Jump Room.json
- region/norfair/crocomire/Post Crocomire Missile Room.json
- region/norfair/east/Bubble Mountain.json
- region/norfair/west/Hi Jump Energy Tank Room.json
This is to make it so that G-Mode strats that don't have an entrance condition no longer show in `Basic` in Map Rando.
> Add canEnterGMode to Strats that don't Start at a Door

- region/maridia/inner-green/East Sand Hall.json
- region/maridia/inner-green/West Sand Hall.json
- tech.json
- And rewrote the `canStationaryLateralMidAirMorph` note.  I'm not sure where the part about it giving equivalent to maximum walk momentum comes from, but it didn't seem right.
> Add insanejump to sandfall softlocky jumps

- region/brinstar/blue/Blue Brinstar Boulder Room.json
This adds some cross-room jump strats that were missing (as pointed out by zornor in the Discord). There are also cross-room spring ball bounce strats that should be considered; I figure we can come back to that after (or as part of) the pending Crateria remote runway PR. (**Edit**: On second thought, I guess spring ball bounce wouldn't necessarily be useful since if you have Morph then you can just do the airball instead, as that requires just the 1 tile of runway which is always available, assuming there's an air environment at all)
This room is currently a bit awkward because of not having a node to represent being in the water below the right door. I'm not sure if everything is logically sound if you were down there and not able to unlock the door (e.g. which could happen in Map Rando …
> Add more Blue Boulder cross-room jumps

- helpers.json
- region/brinstar/red/Red Brinstar Fireflea Room.json
- region/lowernorfair/east/The Worst Room In The Game.json
- region/lowernorfair/west/Golden Torizo's Room.json
- region/lowernorfair/west/Screw Attack Room.json
- region/maridia/inner-pink/Draygon's Room.json
- region/maridia/outer/Fish Tank.json
- region/maridia/outer/Main Street.json
- region/maridia/outer/Mama Turtle Room.json
- region/maridia/outer/Mt. Everest.json
- region/norfair/crocomire/Grapple Tutorial Room 3.json
- region/norfair/east/Lava Dive Room.json
- region/norfair/west/Crumble Shaft.json
- region/norfair/west/Ice Beam Tutorial Room.json
- region/tourian/main/Blue Hopper Room.json
- tech.json
- freezing crabs before they move too far
- Impressive damage boost
- Grapple tutorial gamet boost to vh
- Everest crossroomjumpintowater to veryhard
- Crumble Shaft Top Item Precise Walljump -- add trickyjump
- mama turtle grapple no hijump to precisegrapple
- Fish Tank standing next to pirates=tricky jump.  You can shoot the bottom one to avoid doing anything tricky.  Springballing to the fish from bottom left still seems fine as it was.
- canSpringwall moved to extension of canTrickySpringballJump
- Added heat and spike leniency helpers for canSpringwall.  They look different from the IBJ helpers since the initial walljump setup depends on the strat.  Sometimes there is a forced spikehit and sometimes there isn't.
> Add more leniencies and trickyjump requirements

- logicalRequirements.md
- region/brinstar/blue/Morph Ball Room.json
- region/crateria/central/Bomb Torizo Room.json
- region/crateria/central/Crateria Super Room.json
- region/crateria/central/Landing Site.json
- region/crateria/central/Pre-Map Flyway.json
- region/crateria/east/Crateria Kihunter Room.json
- region/crateria/east/East Ocean.json
- region/crateria/east/The Moat.json
- region/crateria/east/West Ocean.json
- region/crateria/west/Gauntlet Entrance.json
- region/crateria/west/Green Pirates Shaft.json
- region/crateria/west/Statues Hallway.json
- region/maridia/inner-green/East Sand Hall.json
- schema/m3-requirements.schema.json
- schema/m3-room.schema.json
- strats.md
- tech.json
- tests/asserts/keywords.py
- Setups and applications of remote runways in Crateria
- One application in East Sand Hall
- Update `comeInWithSpringBallBounce` docs to clarify it can also match with `leaveWithRunway`
- New entrance condition `comeInWithBlueSpringBallBounce` (like `comeInWithSpringBallJump` but with blue speed).
- Add `startingDownTiles` in (remote) runway schema.
> Crateria remote runway strats

- region/brinstar/kraid/Kraid Eye Door Room.json
- region/brinstar/red/Red Tower.json
- region/crateria/central/Crateria Super Room.json
- region/maridia/inner-yellow/Maridia Elevator Room.json
- region/maridia/inner-yellow/Plasma Room.json
- region/maridia/outer/Mt. Everest.json
- region/norfair/crocomire/Grapple Tutorial Room 3.json
- region/norfair/crocomire/Post Crocomire Jump Room.json
- region/norfair/east/Cathedral Entrance.json
- region/norfair/east/Norfair Reserve Tank Room.json
- region/norfair/east/Single Chamber.json
- region/norfair/west/Crocomire Escape.json
- region/norfair/west/Crumble Shaft.json
- region/norfair/west/Ice Beam Tutorial Room.json
- tech.json
I'm thinking this could be an implicit tech. It's just things youre basically required to do with ice in vanilla. And then I moved some `canUseFrozenEnemies` to `canTrickyUseFrozenEnemies`, although it didn't shift the difficulty of most of the strats.
> Add and use canTrivialUseFrozenEnemies

- region/brinstar/kraid/Warehouse Energy Tank Room.json
- region/lowernorfair/east/Fast Pillars Setup Room.json
- region/lowernorfair/east/Mickey Mouse Room.json
- region/maridia/inner-pink/Botwoon Hallway.json
- region/maridia/inner-pink/Colosseum.json
- region/maridia/inner-pink/Crab Shaft.json
- region/norfair/crocomire/Grapple Tutorial Room 3.json
- Remove Kraid Beetoms as energy farm
- Make Crab Shaft Ice+Supers notable
- Grapple3 springball bounce add version with more leniency
- Top of PrePillar room a little friendlier
- Colosseum add HiJump or Trickyjump to grapple strats
- Full halfie Notable
- Reverse Botwoon hall ice clip note 
Maybe its too early to put flashSuitChecked on non-trivial and grapple teleport strats?
> More Logic Updates

- region/crateria/central/Parlor and Alcatraz.json
- region/crateria/east/The Moat.json
- region/maridia/inner-pink/Botwoon Energy Tank Room.json
- region/maridia/inner-pink/West Sand Hole.json
- region/maridia/inner-yellow/Northwest Maridia Bug Room.json
- region/maridia/outer/Crab Hole.json
- region/maridia/outer/Crab Tunnel.json
- region/maridia/outer/Mt. Everest.json
- region/norfair/crocomire/Crocomire's Room.json
- region/norfair/west/Crocomire Escape.json
- region/tourian/main/Metroid Room 1.json
- region/tourian/main/Metroid Room 3.json
- tech.json
- 8 Super Croc is stressful on expert and takes practice to avoid hitbox scams; add another super pack for lower difficulties
- can4HighMidAirMorph is fair to move to very hard
- Maridia bug room left side bugs are still really hard to deal with
- Crab Tunnel GGG notable; give the option of turning it off and provide some visibility to it
- Everest gravity jump airball
- Some Metroid Rooms require 2nd PB pack
- parlor break top left blocks with speed
- Spacejump alcatraz escape/crab hole
- Croc escape reverse spark
- Botwoon Etank momentumConservingMorph to speedyjump entry
- Moat Springball Bounce add Bombs.  I'd like to keep the strat at Hard
> Various logic changes

- logicalRequirements.md
- region/crateria/central/Parlor and Alcatraz.json
- region/maridia/outer/Main Street.json
- region/maridia/outer/Mt. Everest.json
- region/norfair/east/Cathedral Entrance.json
- schema/m3-requirements.schema.json
- tech.json
- tests/asserts/keywords.py
autoReserveTrigger needed to account for heat damage during refill.  I don't think there are situations where you would trigger it in acid or lava, but maybe something will come up.  Like soaking a namihe hit in lava dive since that won't break spin.
I'm not aware of other uses for `canReserveDoubleDamageBoost` #1512 , but there are more `autoReserveTrigger` into bomb boost situations.
> Reserve Double Damage Boost

- region/crateria/central/Final Missile Bombway.json
Normally a temporary blue into spring ball bounce could be used here instead. By bouncing all the way instead of using temporary blue, it allows keeping a flash suit, so it seemed worth adding.
> Add comeInWithBlueSpringBallBounce in Final Missile Bombway

- logicalRequirements.md
- region/crateria/east/The Moat.json
- schema/m3-requirements.schema.json
- schema/m3-room.schema.json
- strats.md
This PR was prompted by insomniaspeed mentioning a strat where you come in from the right of Moat with a shinecharge, jump across, grab the item, and spark back to the right: https://discord.com/channels/1053421401354285129/1053436236628496454/1247939732776812565. It turns out to be fairly complicated in that there are a lot of possible combinations of whether you carry the shinecharge into the room vs. gain it while running in, and whether you spark back to the door vs. spark through the door (left or right door). Also you can enter from either the left or right side of the room; the left-side entry is less significant but could still be useful as a way to grab the item on the way while sparking right, rather than having to make another trip back into the left room (which might be …
> Refine Moat shinespark strats and item collection

- region/crateria/central/Crateria Super Room.json
- tech.json
I'm envisioning "canTrickySpringBallBounce" here as maybe an Expert tech, for cases requiring a high degree of precision like bouncing into morph tunnels? We could put canInsaneJump on ones that are even more difficult, e.g. where you have to do it while moving with significant speed and possibly from another room (vs. doing it from a stop in temporary blue)? For cases that aren't too precise but are tricky I assume we can use "canTrickyJump" (combined with "canSpringBallBounce") to put them in Very Hard, an example being bouncing across a whole room like the bottom of West Ocean?
> Refine some Crateria Supers cross-room strats

- region/crateria/east/The Moat.json
These both have a 2-frame window for the jump.
> Add canTrickyJump reqs to Moat speedy jump and airball

- region/tourian/main/Big Boy Room.json
- region/tourian/main/Blue Hopper Room.json
- region/tourian/main/Dust Torizo Room.json
- region/tourian/main/Metroid Room 1.json
- region/tourian/main/Metroid Room 2.json
- region/tourian/main/Metroid Room 3.json
- region/tourian/main/Metroid Room 4.json
- region/tourian/main/Rinka Shaft.json
- region/tourian/main/Seaweed Room.json
- region/tourian/main/Tourian Escape Room 1.json
- region/tourian/main/Tourian Escape Room 2.json
- region/tourian/main/Tourian Escape Room 3.json
- region/tourian/main/Tourian Escape Room 4.json
- region/tourian/main/Tourian Eye Door Room.json
- region/tourian/main/Tourian First Room.json
Some changes worth nothing:
- In Tourian Escape Room 3: Added an obstacle representing the Space Pirates being cleared, in order to be able to use the runway near the top-right door. This avoids duplicating a bunch of requirements.
- In Tourian Escape Room 4: Added a node for being at the top of the room without the acid being triggered. This again is to avoid duplicating a bunch of strats. The runway up there is used to get temporary blue to carry out the left door.
> Tourian remote runways

- region/maridia/inner-pink/Below Botwoon Energy Tank.json
- region/maridia/inner-pink/Botwoon Energy Tank Room.json
- region/maridia/inner-pink/Botwoon Hallway.json
- region/maridia/inner-pink/Botwoon's Room.json
A few noteworthy changes:
- Added `collectsItems` to strats in Botwoon Energy Tank Room, as collecting the item is unavoidable when passing through the Morph maze (except while in G-mode if PLMs are already overloaded, though this doesn't really matter since taking the bottom path through the speed blocks would also be an option in that case).
- Clarified details about the "Speedy Jump" strat to get on top of the ledge on the right side of Botwoon Energy Tank Room using run speed from the previous room. Disabling Speed Booster as a way to get a normalized extra run speed of $2.0 seems unnecessary as a logical requirement, since higher speeds also work fine.
- Added an obstacle in Below Botwoon Energy Tank Room for the Owtch being killed. This reduces duplication since many strats need the …
> More Pink Maridia remote runways

- region/maridia/inner-pink/Colosseum.json
- tech.json
Some things worth noting:
- Updated the "Colosseum Bomb Jump Water Escape" notable to take into account that it can also be used in the middle and right side of the room.
- There's an application of some tech of using a pause buffer to continue chaining temporary blue after unmorphing in the air (i.e. an unmorph other than the soft landing type). I remembered seeing this in a bobbob video a while back but forgot about it until recently. It could probably be made into its own "tech", will start keeping an eye out for other applications.
> Colosseum remote runways

- schema/m3-room.schema.json
After this I can add a script to auto-assign strat IDs.
The purpose of tracking a "nextStratId" is to ensure that a strat ID isn't ever reassigned to a different strat, in case the strat with the largest ID in the room gets deleted.
> Add schema for strat IDs

- region/norfair/east/Acid Snakes Tunnel.json
- tech.json
For these strats, the amount of heat damage would depend on the amount of run speed, which depends in a complicated way on the amount of runway available in the other room and on shortcharge skill. The heat frames that I put in are based on a conservative assumption of very low run speed. At some point we could add variant strats with lower heat frames by assuming a higher run speed, but I don't think that's too important right now.
Someday I still think it would be neat to add schema support for interpolating heat frames in a continuous way based on runway length, which could be useful in many situations in heated rooms. But that's a problem for another day.
> Acid Snakes Tunnel carry temp blue

- region/brinstar/pink/Pink Brinstar Hopper Room.json
- region/crateria/central/Crateria Super Room.json
- region/maridia/inner-green/East Sand Hall.json
- region/maridia/inner-pink/Crab Shaft.json
- region/maridia/inner-pink/Halfie Climb Room.json
- region/maridia/inner-pink/The Precious Room.json
- region/maridia/inner-pink/West Cactus Alley Room.json
- region/maridia/inner-yellow/Plasma Spark Room.json
- region/maridia/outer/Crab Hole.json
- region/maridia/outer/Main Street.json
- region/maridia/outer/Mt. Everest.json
- region/norfair/west/Ice Beam Gate Room.json
- schema/m3-room.schema.json
- strats.md
When I was first setting up the schema for these, I was thinking that any Speedbooster requirement could just go in the `requires`. But seeing how this is playing out, it seems too error-prone because it's too easy to forget about it. So this adds `speedBooster` as a required property to `comeInSpinning`, `comeInWithMockball`, and `comeInWithSpringBallBounce` entrance conditions, similar to what we already have for `comeInRunning`, `comeInJumping`, and `comeInSpaceJumping`.
> Add speedBooster to comeInSpinning, comeInWithMockball, comeInWithSpringBallBounce

- region/maridia/inner-green/East Sand Hall.json
These had wrong names (didn't include the room name) and needed to be grouped into reusables. The left-to-right vs. right-to-left strats seem different enough to keep separate from each other, but the temp blue chain variants should be ok not being separate notables.
> Fix East Sand Hall blue spring ball bounce notables

- region/norfair/east/Bat Cave.json
The `canXRayCancelShinecharge` doesn't help quite as much going from bottom to top, since you have the wait a bit anyway for the path to become clear of Skree projectiles. Videos for these are up already on https://videos.maprando.com. I can associate them to the new strats after strat IDs are added; going to work on a GitHub Action workflow for that soon.
> Bat Cave temporary blue

- region/wreckedship/main/Bowling Alley.json
Video for this strat: https://videos.maprando.com/video/308. The ability to retain temporary blue while falling through crumbles could maybe be a separate tech, but it's same kind of soft unmorph as in `canChainTemporaryBlue` so it may be ok to just be assumed as part of that?
This also adds a `canHeroShot` requirement to the existing notable strat "Bowling Alley Missile Chozo Camera Unlock". This won't affect the difficulty level of the strat in Map Rando, since it's already a Very Hard notable.
> Bowling Alley temp blue break bomb blocks

- scripts/check_runways.py
This is just a standalone script to list horizontal door nodes that are lacking a leaveWithRunway strat at the door (i.e. from the door node to itself). If we wanted to enforce this as a check, it could be added to the tests after fixing the existing cases.
> Check horizontal doors without leaveWithRunway

- .github/workflows/run_scripts.yml
This adds a GitHub Action workflow to help us apply autoformatting and to populate strat IDs.
The workflow won't run automatically; it is run by going into the "Actions" tab on GitHub, selecting the "Run Scripts" workflow, and clicking "Run workflow". Within a few seconds, the workflow should open a PR to apply the automated changes. That PR can then be manually reviewed and merged.
> Add GitHub Actions workflow to run scripts

- region/lowernorfair/east/Lower Norfair Spring Ball Maze Room.json
Fix this strat name to match strat 28, `Leave Shinesparking - Open Door First`.
> NorfairSpringBallMazeRoom - strat 28 name: Leave Shinesparking Through Top of Door - Open Door First

- .github/workflows/run_scripts.yml
- schema/m3-tech.schema.json
- scripts/format_json.py
- scripts/populate_tech_ids.py
This also sets up autoformatting on `tech.json`.
Having IDs on tech will be useful in Map Rando in at least a couple ways:
- preserving tech settings (and exporting/importing them) in a more robust way, e.g. so that it can keep working if a tech is renamed.
- associating videos to tech on the new video site, with the same kind of robustness.
> Add script to populate tech IDs

- region/norfair/east/Cathedral.json
Videos:
- left-to-right: https://videos.maprando.com/video/236
- right-to-left: https://videos.maprando.com/video/305
- right-to-left with X-ray: https://videos.maprando.com/video/306
The right-to-left strat is deceptively tricky, took a lot of practice to work out a consistent method. Not completely sure if the canBeVeryPatient requirement is needed, as the strat might not be as hard to learn by watching the video or if the player has a better understanding of the Geruta AI. 
At some point I would like if we had a different tech that we could use for strats like this, since it's technically an abuse of canBeVeryPatient, which is likely to create problems later.
Right-to-left might be possible with X-ray and mid-air Spring Ball jumps instead of HiJump, but I didn't want to go there right …
> Cathedral temporary blue

- region/crateria/central/Final Missile Bombway.json
- schema/m3-room.schema.json
- strats.md
This adds some `leaveWithTemporaryBlue` strats that were missed on the first pass.
Videos:
- left-to-right speedball: https://videos.maprando.com/video/622
- right-to-left speedball: https://videos.maprando.com/video/621
- left-to-right bounce: https://videos.maprando.com/video/343
- right-to-left bounce: https://videos.maprando.com/video/344
> Bombway temp blue

- region/brinstar/blue/Construction Zone.json
This adds a few strats that were missed on the first pass, because we didn't know about unmorphing coming out of spring ball bounce through a morph tunnel. Do you think we should add a tech for this?
Videos:
- Bottom to top left: https://videos.maprando.com/video/614
- Bottom to top right: https://videos.maprando.com/video/615
- Top left to bottom: https://videos.maprando.com/video/616
- Top right to bottom: https://videos.maprando.com/video/624
The top-right to bottom is the only one that works without X-Ray.
> Construction Zone more temp blue

- region/wreckedship/main/Bowling Alley.json
Videos:
- Power on: https://videos.maprando.com/video/696
- Power off: https://videos.maprando.com/video/697
This also touches up the way that the existing in-room strat "Temporary Blue Spring Ball Bounce" is written, though none of the changes should be significant.
> Add lower Bowling Alley leave with temp blue

- region/maridia/outer/Crab Hole.json
Strats for taking temporary blue from the top of Crab Hole (either door) to the bottom (either door). These can be done either with Gravity (neutral bounce) or suitless (with a spring ball bounce), with every case using a pause remorph.
Videos:
- suitless top-left to bottom-right: https://videos.maprando.com/video/670
- suitless top-left to bottom-left: https://videos.maprando.com/video/671
- Gravity top-left to bottom-right: https://videos.maprando.com/video/672
- Gravity top-left to bottom-left: https://videos.maprando.com/video/673
- suitless top-right to bottom-left: https://videos.maprando.com/video/674
- suitless top-right to bottom-right: https://videos.maprando.com/video/675
- Gravity top-right to bottom-left: https://videos.maprando.com/video/676
- Gravity top-right to …
> Crab Hole temp blue

- region/maridia/inner-green/Pants Room.json
- region/maridia/inner-pink/Colosseum.json
- region/maridia/inner-pink/East Cactus Alley Room.json
- region/maridia/inner-pink/Halfie Climb Room.json
- region/maridia/inner-pink/West Cactus Alley Room.json
- region/maridia/inner-yellow/Plasma Spark Room.json
- region/norfair/crocomire/Grapple Tutorial Room 3.json
- tech.json
I never actually tested any of these, other than seeing how close I could jump to the water line (they were all reasonable, within ~1 tile).
There are ~~three~~ *two* tidal ones, which I would think would be easier, but I'm not sure: ~~West Cac Alley,~~ Pants, Grapple Tutorial 3
~~I am especially unsure about West Cac, as the wall doesnt go above the water line.~~ Also unsure on the lenience needed in East Cac above the spikes.
~~I could also ask Eddie to test the tidal difficulty and West Cac specifically if you think that would be worthwhile.~~
Edit: @blkerby tested it with tidal water in Pants Room, also let me know that West Cac can be done without Break Free, and is already in logic.
> Underwater Wall Jump Break Free

- region/brinstar/blue/Construction Zone.json
- region/brinstar/green/Brinstar Pre-Map Room.json
- region/crateria/east/West Ocean.json
- region/maridia/inner-green/East Sand Hall.json
- region/maridia/inner-green/West Sand Hall Tunnel.json
- region/maridia/inner-pink/Below Botwoon Energy Tank.json
- region/maridia/inner-pink/Botwoon Energy Tank Room.json
- region/maridia/inner-pink/Botwoon's Room.json
- region/maridia/inner-pink/Draygon Save Room.json
- region/maridia/inner-pink/Halfie Climb Room.json
- region/maridia/inner-yellow/Plasma Room.json
- region/tourian/main/Big Boy Room.json
- region/tourian/main/Dust Torizo Room.json
- region/wreckedship/main/Sponge Bath.json
This fixes up several strats that either were missing a needed `canChainTemporaryBlue` requirement or had an unnecessary one. The most important reason this can matter is because `canChainTemporaryBlue` has a Morph requirement while `canTemporaryBlue`, `leaveWithTemporaryBlue`, and `comeInWithTemporaryBlue` do not. There are some cases where you can gain temporary blue near a door and jump through it with temporary blue without morphing; and then, if entering the bottom right of Screw Attack Room, you can use the temporary blue to break the bomb blocks, again without morphing, so those strats don't need a `canChainTemporaryBlue` requirement. But in every other case of cross-room temporary blue, Morph is needed, so we have to make sure those `canChainTemporaryBlue` requirements are there. …
> Fix up canChainTemporaryBlue reqs

- region/maridia/inner-yellow/Plasma Spark Room.json
Videos:
- vertical door on the left: https://videos.maprando.com/video/715
- middle right door (long chain from bottom of room): https://videos.maprando.com/video/717
- middle right door (existing strat, killing the Owtches): https://videos.maprando.com/video/718
This also fixes the existing strat that should have had `leaveWithTemporaryBlue` but accidentally had `leaveWithSpark` (a copy-paste error).
> Plasma Spark Room temp blue

- region/norfair/east/Frog Savestation.json
Videos:
- left-to-right: https://videos.maprando.com/video/807
- right-to-left: https://videos.maprando.com/video/808
One detail I hadn't noticed before is that there is a half-tile overhang on the right side, which makes it so that when going right-to-left it doesn't work as well to try to go over the top: assuming you catch on the overhang, you won't get enough downward momentum to get a bounce.
> Frog Savestation temp blue

- region/brinstar/green/Etecoon Energy Tank Room.json
There is no purpose to the 1->3 temp blue strat, as the 2->3 strat already covers it, using the in-room runway and without needing X-Ray. The 2->3 strat was missing a shinecharge requirement though, which is added here.
In theory, alternatives like 1->3 this could still matter for speed purposes (e.g. in case the room becomes heated) but I don't think we're at a point of caring about that yet.
> Etecoon ETank small fixes

- region/norfair/east/Lower Norfair Elevator.json
Videos:
- left-to-right: https://videos.maprando.com/video/822
- left-to-right with X-Ray: https://videos.maprando.com/video/823
- right-to-left: https://videos.maprando.com/video/824
- right-to-left with X-Ray: https://videos.maprando.com/video/825
The heat frames here may look a little lenient based on the videos, but they're made to account for the worst-case scenario where entering with lower speed, e.g. where the shortcharge is essentially all done in-room.
> LN Elevator temp blue

- region/brinstar/pink/Big Pink.json
- region/crateria/central/Climb.json
- region/norfair/west/Ice Beam Gate Room.json
- Climb temp blue from bottom to the top: This strat was somehow only in Extreme. Added a "canLongChainTemporaryBlue" requirement now which will put it into Insane. We could consider making it notable? Breaking the bomb block at the top is the hardest part, and it's exhausting to retry since you have to start from the bottom of the room every time. Also added some notes and made a video for it here: https://videos.maprando.com/video/839
- Climb temp blue from top through upper bomb blocks: Breaking the bomb blocks is hard enough that I think this deserves to be Extreme, especially given that you have to do a cross-room setup on each attempt and it might not be trivial. So added a "canInsaneJump".
- Climb temp blue from top through lower bomb blocks: This had a "canLongChainTemporaryBlue" …
> A few temp blue strat adjustments

- region/norfair/east/Magdollite Tunnel.json
Videos:
- left to right: https://videos.maprando.com/video/826
- right to left: https://videos.maprando.com/video/827
Heat frames account for the possibility of entering with very low speed (e.g. with a TAS-level shortcharge), though this isn't shown in the videos.
> Magdollite Tunnel temp blue

- region/maridia/outer/Main Street.json
- region/maridia/outer/Mt. Everest.json
This trick seems much more difficult without Morph. I'm not sure if "canOffScreenMovement" captures the difficulty but wanted to at least put something there; it might belong more in Insane though? At least, my reaction time is not quick enough to do the forward input after hearing the hurt sound, so it instead has to be a timing based on knowing how long the reserve refill will last. It could also be my audio latency is not great with my emulator setup, so maybe for others it might not be as bad.
I tried the Cathedral Entrance one morphless too and couldn't get it at all; I think I don't understand how it's supposed to work, a video could probably help. It already had a note about it so I assume it's ok though
> Add Morph reqs to reserve double damage boosts

- region/norfair/crocomire/Post Crocomire Jump Room.json
https://dev.maprando.com/seed/kzDPKrrYC/data/visualizer/index.html
Step 7 / Grav in PCJR:
Strat: Break Speed Blocks, Broken Power Bomb Blocks
https://dev.maprando.com/logic/room/127/2/2/23
Strat: Leave with Shinecharge - Power Bomb Blocks Intact
https://dev.maprando.com/logic/room/127/2/2/28
I think the second strat is missing an `"obstaclesNotCleared": ["B"]`?
> Post Crocomire Jump Room - fix missing obstaclesNotCleared id 28

- region/norfair/crocomire/Post Crocomire Jump Room.json
Most of Norfair still needs another pass to refine cross-room shinecharge strats. I wanted to address this one now because it's affecting a notable, putting it in the wrong difficulty tier.
Video: https://videos.maprando.com/video/1091
> Tighten PCJR diagonal spark framesRequired

- region/maridia/inner-pink/Colosseum.json
I think we decided a while ago to not have the grapple clip strats on this door be notable, but the (reusable) notable itself wasn't removed. So this cleans that up. This will get rid of the warnings about the unused notable.
> Remove colosseum grapple clip notable

- region/norfair/east/Bubble Mountain.json
The strats with 4+ tile runway are in Medium, which doesn't really seem fair. I think you want to do 3 walljumps here, like in this video: https://videos.maprando.com/video/983. The version with 2 walljumps is more difficult, requiring more precise timing on the initial jump and wall jumps, and risks getting knocked down by a Cac spike. With 3 walljumps there's more leniency and it leaves room to adjust the walljumps to avoid Cac spikes. By adding a canConsecutiveWalljump it will put these into Hard, except for the shorter-runway version which is already Very Hard because of canTrickyJump.
> Add canStaggeredWalljump reqs to Bubble Mountain runway walljumps

- region/norfair/west/Crocomire Speedway.json
A minimum speed is needed here in order to jump across the gap.
In the case of a low-speed speedball, after breaking the speed blocks, heat frames are saved by unmorphing and running through the rest of the room. It can make a difference if the "heated blue speed" bug is patched, since if it's vanilla then you have to stop holding dash after getting blue, before reaching max speed, meaning more heat frames are required. We might eventually want to add a helper to model that.
I checked that the current heat frames in the strat are sound even with the vanilla mechanic; in the worst case (low-speed entry) it seems to need some arm pumping: https://videos.maprando.com/video/1102
> Add min speed for Croc Speedway Reverse Speedball

- region/brinstar/red/Below Spazer.json
The speedball requirement is especially important here because otherwise there is no Morph requirement.
> Add missing speedball req in Below Spazer

- region/brinstar/green/Brinstar Pre-Map Room.json
- region/brinstar/pink/Dachora Room.json
- region/brinstar/red/Below Spazer.json
- region/crateria/east/Crateria Kihunter Room.json
- region/crateria/east/Forgotten Highway Kago Room.json
- region/crateria/east/West Ocean.json
- region/crateria/west/Green Pirates Shaft.json
- region/crateria/west/Lower Mushrooms.json
- region/lowernorfair/east/Lower Norfair Fireflea Room.json
- region/lowernorfair/east/Metal Pirates Room.json
- region/lowernorfair/east/Red Kihunter Shaft.json
- region/lowernorfair/east/Three Musketeers' Room.json
- region/maridia/inner-green/East Pants Room.json
- region/maridia/inner-pink/Botwoon Hallway.json
- region/maridia/inner-pink/Colosseum.json
- region/maridia/inner-pink/Halfie Climb Room.json
- region/maridia/inner-pink/West Cactus Alley Room.json
- region/maridia/inner-yellow/Pseudo Plasma Spark Room.json
- region/maridia/outer/Main Street.json
- region/maridia/outer/Mt. Everest.json
- region/norfair/crocomire/Post Crocomire Jump Room.json
- region/norfair/east/Bubble Mountain.json
- region/norfair/east/Cathedral Entrance.json
- region/norfair/east/Double Chamber.json
- region/norfair/east/Rising Tide.json
- region/norfair/east/Single Chamber.json
- region/norfair/west/Business Center.json
The numbers are mostly arbitrary, but represent not spending an excessive amount of time reloading the room to farm.  
Writing it this way would make it more dependent on the player estimating farm rates to know when farm thresholds are logical.  
Every partialRefill location could spend more time farming than expected to refill more than the indicated numbers. CanBeXXXPatient could be added for more refill thresholds.
> Change enemy farms to use partialRefill throughout

- region/maridia/outer/Crab Hole.json
This fix won't generally have a logical impact, because this strat was already effectively covered by the airball variant. But it could matter if `canMomentumConservingMorph` were to be disabled while the tech in this strat is all enabled. 
Bug reported by Tilimorf in the Discord: https://discord.com/channels/1053421401354285129/1053434532973510748/1302952163995156511
> Fix speedbooster req in Crab Hole

- region/brinstar/blue/Blue Brinstar Boulder Room.json
This one leaves with 40 more frames remaining compared to the existing suitless strat.
Video: https://videos.maprando.com/video/1201
> Another Blue Boulder shinecharge strat

- region/crateria/east/Forgotten Highway Elbow.json
This room had a "Carry Shinecharge" strat but was missing a "Come in Shinecharging, Leave Shinecharged". It's a minor difference but allows logically using the extra runway and slightly reduced shinecharge frames.
The turnaround momentum conservation saves about 15 frames, so I was thinking it should be ok fitting within the Expert shinecharge leniency. We could add a separate case to model it explicitly though if wanted.
Video: https://videos.maprando.com/video/1241
> Forgotten Highway Elbow shinecharge

- region/crateria/east/Forgotten Highway Elevator.json
- region/crateria/east/Red Brinstar Elevator Room.json
This PR applies to both Red Brinstar Elevator Room and Forgotten Highway Elevator Room, which have identical layouts. Here there is an existing "Carry Shinecharge" strat, but it is useful to add a "Come In Shinecharged, Leave With Spark" strat since it requires fewer shinecharge frames.
Video: https://videos.maprando.com/video/1242
> Red Brin Elevator Room spark

- region/crateria/central/Parlor and Alcatraz.json
- Tighten shinecharge frames on several existing strats
- Add many new shinecharge/shinespark strats
- Add missing Morph requirements
- Remove a couple unnecessary `canWalljump` requirements.
- In one case (strat 18), convert "Come In Shinecharged" require to "Come in Shinecharging". This makes the strat a bit more useful since the extra runway can now logically be used. Because the strat required 170 frames remaining, it was always going to require a runway connected to the door in the other room, so there's no reason for it not to be "Come In Shinecharging".
> Parlor shinecharge updates & new strats

- region/crateria/east/West Ocean.json
This strat had a `comeInShinecharged` requirement with 170 frames required. Given the assumption of spending 10 frames in the previous room after getting the shinecharge, this leaves no room for leniency so this is currently in Insane. 
It makes more sense to slide through the transition while getting the shinecharge, which we represent by a `comeInShinecharging` entrance condition with zero runway length. With this change we're moving the strat down into Expert, via a `canShinechargeMovementTricky` requirement.
I'm also increasing the shinespark frames from 22 to 26. When trying it now, I couldn't get even close to 22 while leaving in top position; I suspect the previous value may have just been based on bottom position.
> Update West Ocean hero shot spark

- region/brinstar/green/Etecoon Energy Tank Room.json
The new frames are based on sliding off the edge, like we've been doing in general since starting to use shinecharge frame leniency.
Videos:
- Fall through crumbles: https://videos.maprando.com/video/1248
- Quick drop: https://videos.maprando.com/video/1249
> Tighten framesRemaining in Etecoon ETank leaveShinecharged

- region/brinstar/red/Alpha Power Bomb Room.json
- region/brinstar/red/Hellway.json
- tech.json
- This adds new strats in Alpha Power Bomb Room and Hellway for using a Samus Eater to gain temporary blue. Insomniaspeed recently showed us how to do this.
- A little more detail is added to the note for the `canSamusEater` tech and its applications, to clarify what the trick is for making it work.
> Samus Eater temp blue strats

- region/maridia/inner-green/West Sand Hall.json
Without HiJump, doing an airball makes it harder to make it across to the pillar, compared to just doing a normal jump. This is already reflected in the "minTiles" for the airball strats which were a tile larger for the airball strats than the corresponding regular jump strats. So there doesn't seem to be a purpose for the airball strats to exist.
This also updates the description of the "Jump With Momentum" and "Tricky Jump With Momentum" strats to reflect the runway requirements currently in those strats.
> Remove useless airball strats in West Sand Hall

- region/norfair/west/Crocomire Escape.json
This is a relatively minor tweak to the `comeInShinecharged` strat to cross right-to-left in Crocomire Escape:
- The heat frames are tightened. The new values are still probably conservative in that they're allowing time to get back to the item location. Regardless of whether of you want to go left or right after collecting the item, being at the Super gate is probably the more favorable position (to be able to open the gate quicker, or gain more run speed for jumping to the right). So we could probably tighten the heatframes further by measuring just to the time when landing after the shinespark crash; I just wasn't 100% confident in case there may be something I'm overlooking.
- A variant is added that goes fast enough to beat the Geruta into the position where you activate the spark, …
> Refine Croc Escape comeInShinecharged

- helpers.json
- region/brinstar/blue/Blue Brinstar Energy Tank Room.json
- region/brinstar/green/Early Supers Room.json
- region/brinstar/green/Etecoon Energy Tank Room.json
- region/brinstar/pink/Big Pink.json
- region/crateria/west/Terminator Room.json
- region/maridia/inner-pink/Aqueduct.json
- region/maridia/inner-pink/Botwoon Energy Tank Room.json
- region/maridia/outer/Mama Turtle Room.json
- region/norfair/east/Double Chamber.json
- region/norfair/east/Green Bubbles Missile Room.json
- region/norfair/west/Crocomire Escape.json
- region/norfair/west/Hi Jump Energy Tank Room.json
- region/wreckedship/main/Bowling Alley.json
- region/wreckedship/main/Gravity Suit Room.json
This adds `collectsItems` throughout. 
- Strats could be added to avoid the item in many of these instances.
- Some of the strats in heated rooms, where I didn't add `collectsItems`, would have more heatFrames if they were to avoid the items.
- It's also possible that I missed some strats if the entire node was avoided, but it's pretty uncommon to skip item nodes with those kinds of strats
> Use collectsItems Throughout

- region/brinstar/red/Below Spazer.json
This comes from Athebyne who mentioned in the Discord that it was missing: https://discord.com/channels/1053421401354285129/1053436236628496454/1304853408863354880.
> Below Spazer cross-room spark up strats

- region/crateria/central/Crateria Super Room.json
This adds a couple new "tricky" strats which make it possible to spark across the top of the room left-to-right while conserving enough energy to be able to survive a spike hit tankless on the way back. Later when we have schema support for coming in shinecharged with momentum, lower-difficulty strats for doing this could also be added.
Videos:
- comeInShinecharged: https://videos.maprando.com/video/1314
- comeInShinecharging: https://videos.maprando.com/video/1315
The strats for sparking up the room from the bottom are also refined/tightened.
> Crateria Supers spark strats

- region/norfair/crocomire/Post Crocomire Farming Room.json
This adds several new shinecharge strats:
- In-room strat to leave shinecharged out the top-left door:
- With a short right-to-left shortcharge and HiJump + wall jump, this can be done with 20 frames remaining.
- For comparison, the in-room strat already in logic uses a shortcharge left-to-right and leaves with 10 frames remaining (but no wall jump required).    
- In-room strats to leave with a shinespark out the top-left door:
- A HiJump version which is basically a more lenient (Very Hard-level) version of the strat that leaves with 10 frames remaining.
- A (bootless) tricky dash jump wall jump version
- In-room strats to leave with a shinespark out the top-right door, with a wall jump or Space Jump.
Adjustments to existing strats:
- Some strats are renamed to follow the conventions …
> Post Croc Farm Room shinecharges

- region/norfair/west/Crocomire Speedway.json
- tech.json
- This adds many new shinecharge strats and updates the existing ones.
- A new tech `canControlShinesparkEnd` is added for manipulating Samus' regular energy in order to cause a shinespark to end in a desired location.
- Using this tech, the reverse spark with Varia becomes in logic tankless.
- Heat frames are tightened, so the reverse spark from the Save door becomes in logic with 2 ETanks.
- Reserve abuse strats are added, allowing getting through with 1 Reserve Tank from any of the three doors on the right, using the recently added tech `canPreciseReserveRefill` (or 2 Reserve Tanks without that tech but still with `canPauseAbuse`).
- The shinecharge strats from node 6 (with obstacle "A" cleared) are not yet updated. These currently require `h_heatProof`. It will take a little more …
> Croc Speedway shinecharges

- region/lowernorfair/west/Fast Ripper Room.json
These are strats for coming in through the left door, crossing the room, and sparking back out the left door.
It would be possible to add 2->1 strats here as well, which could save some heat frames. But gate glitching and dealing with the Rippers from the right seems tricky enough that I don't want to try to figure it out.
> Fast Ripper Room shinecharges

- region/crateria/central/Landing Site.json
- region/norfair/crocomire/Post Crocomire Jump Room.json
This is mostly adding strats for sparking through the left door of PCJR, with a few other refinements/fixes. This also adds strats for sparking diagonally to the top-left, using less energy than the horizontal spark currently in logic.
In Landing Site, I noticed that strats that went through the open left door were implicitly requiring unlocking the door a second time, so that is also fixed here.
As usual, videos for all the new stuff are on https://videos.maprando.com
> PCJR shinesparks

- helpers.json
- region/crateria/east/East Ocean.json
- region/maridia/inner-green/West Sand Hall.json
- region/maridia/inner-pink/Botwoon Hallway.json
- region/maridia/inner-pink/East Sand Hole.json
As discussed in #1744.
Note that I removed the `can` and just named it `h_UnderwaterCrouchJumpWithFlashSuit`. We were thinking it could be nice to remove `can` from helpers, and reserve it for tech. 
Also created the very long named `h_UnderwaterMaxHeightSpringBallJumpWithFlashSuit`. I plan to use it the same way, in an OR.
> Redefine h_UnderwaterCrouchJumpWithFlashSuit

- region/maridia/inner-pink/Halfie Climb Room.json
Some grapple teleport strats in Halfie Climb that were missed in the first pass. These all involve getting into the air space in the top left and then grapple clipping to bypass the door shell.
Videos:
- original find by SamLittlehorns: https://videos.maprando.com/video/1470
- from Moat to top-right door (on-camera): https://videos.maprando.com/video/1648
- from Moat to bottom-right door (off-camera): https://videos.maprando.com/video/1649
- from Red Brin Firefleas to top-right door (on-camera): https://videos.maprando.com/video/1651
- from Red Brin Firefleas to bottom-right door (off-camera): https://videos.maprando.com/video/1652
> Halfie Climb grapple teleport into grapple clip

- region/lowernorfair/west/Screw Attack Room.json
- strats.md
- tests/asserts/keywords.py
This overhauls the shinecharge/shinespark strats in this room, removing the obstacle "C" in favor of the newer `startsWithShineCharge`/`endsWithShineCharge` strat properties used in The Moat. This allows us to express many more strats that collect the item while holding a shinecharge, as well as more ways of using the shinecharge afterward.
As part of this, I got rid of the notable "Descent and Shinespark Escape". It seemed maybe unnecessary now that we have `canShinechargeMovementTricky` and shinecharge frame leniency to express the strat difficulties. There are many different possible difficulties depending on the combination of strats used here (ranging from Very Hard to Extreme), and not all of them involve a descent since you can also enter shinecharged/shinecharging from the left …
> Screw Attack Room shinecharges

- region/crateria/east/East Ocean.json
- region/crateria/east/The Moat.json
- region/maridia/inner-green/Oasis.json
- region/maridia/inner-green/Pants Room.json
- region/maridia/inner-green/Spring Ball Room.json
- region/maridia/inner-green/West Sand Hall.json
- region/maridia/inner-pink/Aqueduct.json
- region/maridia/inner-pink/Below Botwoon Energy Tank.json
- region/maridia/inner-pink/Botwoon Energy Tank Room.json
- region/maridia/inner-pink/Colosseum.json
- region/maridia/inner-pink/East Cactus Alley Room.json
- region/maridia/inner-pink/East Sand Hole.json
- region/maridia/inner-pink/Halfie Climb Room.json
- region/maridia/inner-pink/The Precious Room.json
- region/maridia/inner-pink/West Sand Hole.json
- region/maridia/inner-yellow/Butterfly Room.json
- region/maridia/inner-yellow/Plasma Spark Room.json
- region/maridia/inner-yellow/Thread The Needle Room.json
- region/maridia/inner-yellow/Watering Hole.json
- region/maridia/outer/Crab Tunnel.json
- region/maridia/outer/Fish Tank.json
- region/maridia/outer/Glass Tunnel.json
- region/maridia/outer/Mama Turtle Room.json
- region/maridia/outer/Mt. Everest.json
- region/maridia/outer/Red Fish Room.json
- region/wreckedship/main/Electric Death Room.json
- tech.json
Looked through all of the `canSuitlessMaridia/h_canNavigateUnderwater` to see what should be allowed in Map Rando's `Basic`. Most of these changes are actually that a strat required `canSuitlessMaridia` and another tech that relied on it.
I wasn't consistent with underwater spring ball jumps, but I'm kind of leaning towards having very simple underwater spring ball jumps not require `canSuitlessMaridia`, since underwater actually makes them easier - thoughts?
I was wondering if it might be useful to add `canSuitlessMaridia` to some tech and helpers, like crab/snail/mochtroid climbs, and the double spring + HiJump helper - thoughts?
This will definitely need a second pass after I get your feedback, and then I was thinking it could be nice to rename `canSuitlessMaridia`. Maybe …
> Slightly Refine canSuitlessMaridia

- region/lowernorfair/east/Fast Pillars Setup Room.json
This also includes strats (not involving shinecharging) that gain blue speed running into the room and use it to kill the bottom two Pirates. There are several variations depending on the entry speed: in addition to using the blue speed to kill the Pirates, the momentum can be used to jump onto the platform or all the way up to the door; or just do a small jump to kill the Pirates and then do a separate tricky dash jump to get onto the platform.
> Fast Pillars Setup Room shinecharges

- region/crateria/central/Parlor and Alcatraz.json
- region/lowernorfair/east/Lower Norfair Farming Room.json
- region/lowernorfair/east/Lower Norfair Spring Ball Maze Room.json
- region/lowernorfair/east/Main Hall.json
- region/lowernorfair/east/Mickey Mouse Room.json
- region/lowernorfair/east/Red Kihunter Shaft.json
- region/lowernorfair/east/Ridley's Room.json
- region/lowernorfair/west/Golden Torizo's Room.json
- region/lowernorfair/west/Screw Attack Room.json
- region/norfair/east/Acid Snakes Tunnel.json
- region/norfair/east/Bat Cave.json
- region/norfair/east/Cathedral Entrance.json
- region/norfair/east/Cathedral.json
- region/norfair/east/Lower Norfair Elevator.json
- region/norfair/east/Norfair Reserve Tank Room.json
- region/norfair/east/Purple Farming Room.json
- region/norfair/east/Upper Norfair Farming Room.json
- region/norfair/west/Crocomire Escape.json
- region/norfair/west/Crocomire Speedway.json
- resources/app/manifests/pip_requirements.txt
- schema/m3-requirements.schema.json
- tests/asserts/keywords.py
- tests/asserts/validate.py
This depends on #1794, so it should be merged first.
This adds tests to check that a `shinespark` logical requirement occurs in every strat with a `leaveWithSpark` exit condition, and that every `or` branch is covered. This turned up three strats that were missing a `shinespark`; these are fixed here.
Tests are also added to check for a `heatFrames` requirement for every strat in heated rooms, again ensuring that every `or` branch is covered. Here, "h_heatProof" and a number of helpers that indirectly include heat frames are also counted. Exceptions are carved out for common situations where it is normal for no heat frames to be included (such as "leaveWithRunway" at a door node, "comeInWithGMode", and grapple teleports that bypass a door lock). For all other "false positive" cases, I'm …
> More tests

- resources/app/manifests/pip_requirements.txt
- tests/asserts/validate.py
The validation script has been giving warnings that RefResolver is deprecated in favor of the `referencing` package. This PR migrates over to the new, recommended package.
What prompted this is that since #1789 fixed the top-level `$id` property, the RefResolver started recognizing it and fetching the schema files using HTTP GET requests, treating the `$id` as a URL, and using the responses as the schemas to apply  in validation. This initially appeared to work because those URLs actually are valid references to the schema files on GitHub. But once we start introducing schema changes locally, then it doesn't work because it's using the schemas from the master branch instead of the local copies. This was considered a bad behavior of the RefResolver, and it no longer happens after switching …
> Migrate json schema validation to use 'referencing' instead of RefResolver

- strats.md
- tech.json
- Implicit "canShinechargeMovement" tech on "leaveShinecharged" and "comeInShinecharged" exit/entrance conditions. I think we've been trying to put the "canShinechargeMovement" requirement explicitly on the strat with the "comeInShinecharged", but it's easy to forget. It should be less error-prone to have it be an implicit requirement on the exit/entrance conditions. Moving through a door transition with a stored shinecharge should always fit the description of "canShinechargeMovement" so I think it makes sense to have it always there. This is in contrast to "comeInShinecharging" which doesn't always need it.
- Implicit "canMidairShinespark" on "comeInWithSpark" in top position. There are some cases where you can stand on an elevated platform near a door to leave in top position without a …
> Add detail in shinespark tech descriptions and docs

- scripts/format_json.py
This makes some adjustments to the autoformatting script, allowing more values to be formatted on a single line:
- Character limit for a single-line value increased from 50 to 80
- Relaxed requirements on data types allowed to nest inside a value formatted on one line.
- Properties of "unlocksDoors" are now excluded from the rules about certain field names (e.g. "requires") being disallowed from being a one-liner.
The most common things impacted by these changes are "unlocksDoors", "canShineCharge", and "enemyDamage". I wasn't sure about "enemyDamage" being on one line; I think it maybe looks ok, but if it isn't liked, it could be added to the `non_one_line_keys`.
> Tweak auto-formatting script for more compactness

- logicalRequirements.md
- schema/m3-requirements.schema.json
- schema/m3-room.schema.json
- scripts/migrations/shinecharge_frames.py
- strats.md
- tests/asserts/keywords.py
This script removes the `framesRemaining` and `framesRequired` properties from the exit condition `leaveShinecharged` and the entrance condition `comeInShinecharged`. These are converted into `shineChargeFrames` logical requirements within the strat `requires`. The docs are also updated, to clarify how the `shineChargeFrames` logical requirement should be used, in combination with `leaveShinecharged` and `comeInShinecharged`.
This PR adds the script and makes the related schema changes, but the output of running the script will be done in a separate PR. It is expected that the tests fail until running the scripts; so this can be done immediately after this PR is merged.
There are also several tests that I want to add related to shinecharge requirements, but this can be done after the …
> Shinecharge frame migration script

- connection/connection-readme.md
- schema/m3-room.schema.json
- strats.md
All these implicit strats are currently implemented in Map Rando with the exception of the implicit `comeInWithMockball`. So, with that exception, this PR is an attempt to document the existing way that we are interpreting things rather than add new implicit strats. It also adds a way to override these implicit strats, which should allow us to eliminate the need for `spawnAt` nodes in many rooms, and eventually perhaps eliminate the `spawnAt` property altogether.
Something that will still need refining later is how to address the fact that it is unsound for the logic to assume you can enter a heated room (with an implicit "comeInNormally") and leave (with an implicit "leaveNormally") with no heat damage. This is a problem that exists in the randomizer now, though we've never seen an …
> Implicit exit/entrance conditions and related docs

- helpers.json
- region/brinstar/green/Green Brinstar Main Shaft.json
- region/brinstar/pink/Pink Brinstar Power Bomb Room.json
- region/maridia/inner-pink/Halfie Climb Room.json
Currently Map Rando removes the misplaced door closing animation in Etecoon Shaft, and fixes the closing animation. This will enable a fix the closing animation of all 3 bad doors.
I think it would make sense for Map Rando to not use this helper and to revert back to the vanilla door close in Etecoon shaft (but fix the misplaced doorshell in Main Shaft).
> Rename and Broaden h_EtecoonDoorSpawnFix

- region/wreckedship/main/Wrecked Ship Main Shaft.json
Bobbob showed us these a while ago.
This also fixes the "Temporary Blue Chain (In-Room)" strat to clear the bomb block obstacle.
Videos:
- Atomic Ice Moonfall Screw Attack Clip: https://videos.maprando.com/video/2359
- Covern Wall Ice Screw Clip: https://videos.maprando.com/video/2365
> Wrecked Ship Main Shaft break bomb block with Ice and Screw

- logicalRequirements.md
- region/brinstar/blue/Construction Zone.json
- region/brinstar/pink/Big Pink.json
- region/region-readme.md
- schema/m3-requirements.schema.json
- schema/m3-room.schema.json
This is a proposed schema for a new way of representing farming strats, along with a couple examples.
I tried to be relatively accurate in these examples, but in general I think that for `cycleFrames` it is not so important to have the frame counts be tight compared to `heatFrames`. In the end, all these numbers are going to have a "patience" factor applied, which is somewhat arbitrary anyway.
Unrelated to the main change in the PR, I also added a little clarification to the `shineChargeFrames` doc.
> Farm cycle schema and examples

- region/crateria/east/West Ocean.json
In Map Rando, with HiJump getting to the item is already in Basic logic by riding Trippers. Still, the speedy jump is much faster and commonly useful so it seems worth including; it also avoids the `canUseEnemies` requirement.
Video by SamLittlehorns: https://videos.maprando.com/video/2430
> West Ocean speedy HiJump to top item

- region/crateria/east/West Ocean.json
This is what bobbob called the "World's Stupidest Moondance". In Map Rando I'm planning to make this an Ignored notable since it takes 45 minutes, exceeding even the patience threshold for Beyond (roughly 10-15 minutes).
- Video by Sam: https://videos.maprando.com/video/2311
- Original video by bobbob: https://vimeo.com/815466837
> West Ocean respawning shot block moondance

- region/norfair/east/Bat Cave.json
This splits off the "Frozen Skree" strat from the base strat, and tightens the heat frames on other variants of the Base strat by adding "tricky" versions. 
Videos:
- Frozen Skree - With Varia (by Sam): https://videos.maprando.com/video/2395
- Frozen Skree - Suitless: https://videos.maprando.com/video/2458
- Tricky HiJump: https://videos.maprando.com/video/2462
- Tricky Spring Ball Jump: https://videos.maprando.com/video/2461
> Some tricky Bat Cave bottom-to-top strats

- region/crateria/central/Climb.json
- region/crateria/central/Crateria Power Bomb Room.json
- region/crateria/central/Flyway.json
- region/crateria/central/Pit Room.json
- region/crateria/east/Bowling Alley Path.json
I went ahead and put videos for these farm strats on https://videos.maprando.com, since I needed to do testing anyway to get `cycleFrames` values. They're not optimized as heavily as heat frames but I wanted them to be at least somewhat reasonable.
In cases where it seemed important, I included a "Both Doors" variant that resets the room twice, at opposite ends of the room. In this case the enemy drop counts are doubled, cycle frames are the total for traversing both directions, and it's understood that the randomizer will add extra `cycleFrames` for each `resetRoom` requirement to account for the time taken by the door transitions.
> Some Crateria farms

- region/brinstar/red/Red Brinstar Fireflea Room.json
I don't believe this would be possible with only 1 spike hit.
> Add missing spike hit req for red brin firefleas x-mode

- region/maridia/inner-yellow/Plasma Spark Room.json
Without HiJump, this is coming up almost 2 tiles short.
> Add missing HiJump req to Bomb Boost Spring Ball Jump

- schema/m3-room.schema.json
- scripts/format_json.py
- scripts/migrations/import_map_tile_mask.py
This is the starting point for a project to include map-tile data in `sm-json-data`. I'm using a script here to import the data from the Map Rando [room_geometry.json](https://github.com/blkerby/MapRandomizer/blob/6177311d46d36f1da6b2fc4702d240b2c8c7c145/room_geometry.json). I'll open a second PR committing the results of executing the script (#1849).
After this a few rooms will need to be manually added as they were not included in `room_geometry.json`: all Ceres rooms, Homing Geemer Room, and East Pants Room.
Next steps in the project then include:
- Importing node-level map-tile data. This data is used in the Map Rando spoiler map to determine which map tiles to highlight on each step. Currently this data often gets broken, whenever nodes are added, deleted, or redefined. It will be …
> Script to import map tile data from room_geometry.json

- schema/m3-note.schema.json
- schema/m3-room.schema.json
- scripts/autoformat.py
- scripts/schema_order.py
This adds a step in the auto-formatting script: it will now put object properties in the order dictated by the JSON schema. For example, in a strat with an `exitCondition`, the `exitCondition` will come after the `requires`. This helps iron out some little inconsistencies in the format of the data. It also moves the newly added room-level `mapTileMask` to near the top, instead of being near the bottom where it is now.
One thing is note is that while running this introduces a lot of changes in terms of amount of lines, it is low-risk because the auto-formatting script is still protected by a check that ensures the equivalence of the JSON input and output; specifically, the Python objects are tested for equality, which validates that any differences are only in formatting.
To make the new …
> Make auto-formatting sort object properties by schema order

- region/wreckedship/main/Bowling Alley.json
- region/wreckedship/main/Gravity Suit Room.json
This is a short-term fix to resolve some major logic unsoundness. Later we can come back and properly handle requirements for collecting the items in a way that takes into account their spawn conditions.
> Remove collectsItems on strats with unhandled item spawn requirements

- region/norfair/west/Crocomire Speedway.json
This was based on seeing [this video](https://videos.maprando.com/video/491) in the Incomplete queue. Worked on it a bit and was surprised to find that it can be done from Crocomire's Room without HiJump or any tanks.
- From the bottom door:
- with HiJump: https://videos.maprando.com/video/3010
- with tricky dash jump (speed $6.0): https://videos.maprando.com/video/3009
- with tricky dash jump (speed $6.1): https://videos.maprando.com/video/3008
- From the bottom-right door:
- with full run speed: https://videos.maprando.com/video/3011
- with high run speed ($6.5, which is approximately the minimal amount needed to make it through tankless): https://videos.maprando.com/video/3012
> More Croc Speedway speedball strats

- region/maridia/outer/Mt. Everest.json
- region/norfair/crocomire/Post Crocomire Jump Room.json
- tests/asserts/keywords.py
This checks a couple things, to prevent some mistakes that we have seen in the past with `and`/`or`:
- That `and`/`or` requirements always have at least 2 elements inside.
- That `and` does not have another `and` directly inside of it, and similarly for `or`.
Logically or mathematically, there's nothing inherent wrong with having 0 or 1 elements in and `and`/`or` or having them directly nested inside each other. It's just that in practice it seems like it would usually indicate a mistake was made, and even if it's correct it could always be simplified to avoid violating those rules.
The new tests found only two issues, both of which are fixed here. The one in PCJR could use a closer look to make sure I understood the intent correctly. I imagine that with some patience, bringing the Mella …
> Add some tests for 'and' and 'or', fix a couple issues

- region/norfair/east/Single Chamber.json
This room is where I hit a wall when I was last going through and adding temp blue strats.
As usual, videos for all these strats on https://videos.maprando.com. 
For measuring heat frames, it definitely helped to be able to reference a video, because there are a few tricky things:
- While using X-Ray the in-game time continues to count up while no heat damage is happening. So for estimating heat frames we look at the change in Samus energy rather than in-game time.
- We want to exclude the time spent gaining the shinecharge or blue speed.
- Since we're looking at the change in Samus energy rather than in-game time, we need to be careful to account for any drops that happened to be collected.
The strats in these videos (especially the Spring Ball jump ones) are generally optimized a little …
> Single Chamber temp blue

- region/norfair/west/Ice Beam Gate Room.json
Videos:
- SamLittlehorn's original video: https://videos.maprando.com/video/2513
- Possibly improved version, with no damage: https://videos.maprando.com/video/3091
- A version with Wave beam: https://videos.maprando.com/video/3091
The Wave version is what I was trying at first because it seemed easier, though after messing more with the Ice-only version it ended up seeming fine.
I'm thinking Extreme notable for this one; the `canWallIceClip` would already put it in Extreme, the notable is just because of the unintuitiveness/obscurity of the trick. If there end up being a lot more tricks like this, then maybe the notable would be not needed :shrug:
> Ice Beam Gate Room: Mella Wall Ice Clip X-Ray Climb

- region/brinstar/blue/Construction Zone.json
This is one of the easier ice moonfalls to set up. The only idea behind making it notable is that there's a big knowledge check in understanding that the Komas are enemies and that it's possible to get stuck using them.
Videos by SamLittlehorns:
- right side: https://videos.maprando.com/video/2637
- left side: https://videos.maprando.com/video/2638
> Construction Zone ice moonfall leave with stored fall speed

- region/maridia/outer/Mt. Everest.json
- region/maridia/outer/Red Fish Room.json
- region/norfair/east/Bubble Mountain.json
- region/tourian/main/Metroid Room 4.json
These are more strats for using an ice moonfall to clip down past a door lock.
Videos:
- Metroid Room 4: https://videos.maprando.com/video/2182
- Bubble Mountain:
- Sam's original video (with Bombs): https://videos.maprando.com/video/2183
- version with Power Bomb: https://videos.maprando.com/video/3084
- Red Fish Room: https://videos.maprando.com/video/2184 
- Mt. Everest bottom-left door:
- Sam's original video: https://videos.maprando.com/video/2187
- possibly improved version: https://videos.maprando.com/video/3090
- Mt. Everest bottom-right door:
- Sam's original video: https://videos.maprando.com/video/2186
- version not requiring Supers: https://videos.maprando.com/video/3086
> Add some of SamLittlehorns' new ice moonfall strats

- region/brinstar/green/Brinstar Pre-Map Room.json
- region/brinstar/green/Green Brinstar Main Shaft.json
- region/brinstar/pink/Waterway Energy Tank Room.json
- region/crateria/central/Final Missile Bombway.json
- region/crateria/central/Pre-Map Flyway.json
- region/crateria/east/The Moat.json
- region/lowernorfair/east/Lower Norfair Spring Ball Maze Room.json
- region/maridia/inner-pink/Aqueduct.json
- region/maridia/inner-pink/Crab Shaft.json
- region/maridia/inner-pink/Draygon's Room.json
- region/maridia/inner-pink/East Cactus Alley Room.json
- region/maridia/inner-pink/Halfie Climb Room.json
- region/maridia/outer/Fish Tank.json
- region/norfair/east/Bubble Mountain.json
- region/norfair/east/Spiky Acid Snakes Tunnel.json
- region/norfair/west/Crocomire Speedway.json
- region/tourian/main/Dust Torizo Room.json
- region/tourian/main/Metroid Room 3.json
- region/tourian/main/Tourian Escape Room 2.json
- region/tourian/main/Tourian Escape Room 3.json
- region/tourian/main/Tourian Escape Room 4.json
- region/tourian/main/Tourian Eye Door Room.json
- region/wreckedship/main/Spiky Death Room.json
- region/wreckedship/main/Sponge Bath.json
- strats.md
- tests/asserts/keywords.py
When certain phrases occur in strat names (e.g. "Leave With Temporary Blue") without a corresponding exit/entrance condition (e.g. "leaveWithTemporaryBlue"), it likely indicates a mistake. It's a common enough problem that it seemed worthwhile to add tests for this, including fixes for the failing cases. A few cases were relatively benign, where it seemed fine to just rename them to work around the tests. It's maybe an awkward sort of test but it does catch a lot.
I had to try out the case in Green Brinstar Main Shaft that had the wrong exit condition, to figure out what the shinespark frames were supposed to be; went ahead and adjusted the shinecharge frames too because I noticed they were loose.
> Add tests for exit/entrance conditions based on strat name phrases

- region/maridia/inner-pink/Botwoon Quicksand Room.json
If entering from a 4-tile-wide sand transition above, it is surprisingly difficult to reach the tunnel. And I think 4-tile-wide entrance is consistently what happens in Map Rando whenever the tunnel would be logically useful. It feels like at least an Expert-level mid-air morph, but with only one attempt, so probably an Extreme notable.
I left a FIXME to handle different types of entrances. Even with the vanilla transition, it's not trivial and would probably be at least a Very Hard trick; a Bull can mess you up, or you can easily move too far off the top ledge and not have enough time to move back to the tunnel, since the acceleration is so slow in the sand. With the vanilla transition, though, there's no reason to ever use the tunnel because you could just enter from the opposite side …
> Refine Botwoon Quicksand Hidden Tunnel logic

- region/lowernorfair/east/The Worst Room In The Game.json
The existing 2->4 shinespark strat seemed too difficult for Medium. Added a `canMidairShinespark` requirement to put it in Hard; even though it's technically possible to do this from the ground with no mid-air spark, I don't think that makes it significantly easier. One thing to keep in mind is that when sparking from from too far right (as a player on Medium would likely do), there's significant risk of not just taking the hit from the fireball but also getting knocked back down by it. Assuming a mid-air spark also allows us to tighten the shinespark frame requirements without having to double the amount of variants further. 
Videos on https://videos.maprando.com.
> Worst Room In The Game shinecharges

- region/maridia/inner-pink/Botwoon Quicksand Room.json
It was an oversight that these strats were kept named "Base" when they're now an Extreme-level notable.
> Rename strats passing through Botwoon Quicksand tunnel

- region/norfair/crocomire/Post Crocomire Jump Room.json
This PR removes the X-Ray variant of the Mella Ice Clip, making "h_canPreciseIceClip" (Expert) required. It also adds more detail to the notes/devNotes about how to do the trick using Eddie's normalized setup. If this is merged, we would also move the corresponding notable up from Very Hard to Expert difficulty.
HisBeardNis brought this up to me the other day in his stream: he mentioned he had been doing an Extreme seed but spent 3 hours to get this clip which is currently in Very Hard if X-Ray is available, as it was in his case.
I took a look and to me even with X-Ray it feels pretty bad to try to freestyle it; I don't think it's really ok in Very Hard. It's much better to use Eddie's normalization trick, and in that case X-Ray is irrelevant. The setup for the normalization is kind of …
> Refine PCJR Mella ice clip

- region/maridia/inner-pink/Colosseum.json
- region/maridia/inner-pink/Halfie Climb Room.json
- tech.json
This adds a new tech `canFrozenEnemyGrappleHang`, with applications in Halfie Climb and Colosseum. With this technique, it is possible to perform grapple teleports from these locations without Morph.
For the `canUnmorphGrappleHang` strats, the "Bombless" descriptor used in many of the strat names now became ambiguous, so I renamed these to use the word "Unmorph" instead.
somerando(cauuyjdp) showed us this technique here: https://discord.com/channels/1053421401354285129/1053436236628496454/1328638519047880729
As usual, I added videos for all of the new strats on https://videos.maprando.com.
G-mode artificial morph is another possible way that grapple teleports could be set up from these locations without Morph. Strats for that can be added in a later PR.
> Frozen Mochtroid morphless grapple teleport setups

- region/brinstar/pink/Dachora Room.json
- region/brinstar/pink/Pink Brinstar Hopper Room.json
- region/crateria/east/East Ocean.json
- region/lowernorfair/east/Lower Norfair Spring Ball Maze Room.json
- region/norfair/east/Frog Speedway.json
- region/tourian/main/Tourian Escape Room 4.json
- region/wreckedship/main/Wrecked Ship East Super Room.json
This simplifies a few notable names that seemed more verbose than necessary. I started with notables referenced in the v117 release notes, then did a few more. It's not a complete pass though.
I also added a `canPreciseSpaceJump` requirement on the East Ocean left-to-right strat with Space Jump only.
Also I notice we have a lot of notables for cross-room shinecharge/shinespark strats that probably don't need to be notable anymore, something that could be cleaned up later.
> Clean up some notable names

- region/maridia/inner-green/East Pants Room.json
- region/maridia/inner-green/East Sand Hall.json
- region/maridia/inner-green/Oasis.json
- region/maridia/inner-green/Pants Room.json
- region/maridia/inner-green/Shaktool Room.json
- region/maridia/inner-green/West Sand Hall Tunnel.json
- region/maridia/inner-green/West Sand Hall.json
This completes a full pass over the regions to add/refine shinecharge strats, since "Carry Shinecharge" became possible in the schema. It's taken long enough that now the early regions could probably use another pass; not planning on that though, haha.
> Green Maridia shinecharges

- region/maridia/outer/Main Street.json
This is mostly just a restructure of the current g-mode overload speed block strats. I added two new junctions and added more strats to get into position. It's also worth noting that there are no strats in this PR to grab the item without Ice, but there are strats added that get into position without it.
This lays the groundwork to (hopefully) be able to easily add the other ways to grab the item:
- wave+ice and wave is the item
- PB + ice
- Kago +ice (immobile, CF, E-Tank item)
- R-Mode standup (CF + no ice)
> Main Street G-Mode Cleanup

- region/brinstar/green/Green Brinstar Main Shaft.json
- region/brinstar/pink/Big Pink.json
- region/brinstar/red/Alpha Power Bomb Room.json
- region/brinstar/red/Beta Power Bomb Room.json
- region/brinstar/red/Hellway.json
- region/crateria/central/Parlor and Alcatraz.json
- region/maridia/inner-pink/Colosseum.json
- region/maridia/outer/Mt. Everest.json
- region/norfair/east/Kronic Boost Room.json
- region/norfair/west/Ice Beam Snake Room.json
- region/wreckedship/main/Wrecked Ship Main Shaft.json
- schema/m3-room.schema.json
- strats.md
- tech.json
This introduces
- a new tech `canSamusEaterTeleport`
- new entrance/exit conditions `leaveWithSamusEaterTeleport` and `comeInWithSamusEaterTeleport`
- setups in Hellway and Alpha Power Bomb Room
- applications in many rooms (covering all examples that I know of)
As usual, videos for all the new strats are on https://videos.maprando.com.
> Samus eater teleport

- region/maridia/inner-pink/Botwoon Energy Tank Room.json
This will allow the left to right variant to be moved up in difficulty, or at least be a toggleable notable.
> Notable sand bomb boost (left to right)

- region/maridia/outer/Main Street.json
- tech.json
This PR
- Adds a `canTrickyJump` requirement for the getting up the bottom of Main Street with Ice + HiJump without Supers. 
- Clarifies the `note`, prioritizing the Super version.
- Clarifies the `canTrickyUseFrozenEnemies` tech description.
In my testing, the version of this strat with Supers is noticeably easier than the other 3 methods. With Supers, there's a lot of lenience in where the crab and fish can be frozen, and there is time to deal with freezing or refreezing the fish after getting on top of the frozen crab. The other 3 methods all have something tricky about them that I think makes them fit better in Very Hard:
- The method that freeze the crab on the corner requires fairly precise positioning of both the crab and the fish simultaneously.
- The crouch-jump down-grab method …
> Adjust Main Street 'Suitless Frozen Fish, HiJump'

- region/maridia/inner-pink/Botwoon Energy Tank Room.json
I played around with this in TAStudio to work out the details of the timing.
Interestingly, the timings for a Power Bomb turned out to be significantly different, and in a way that doesn't have anything to to do with lag. Overall the Power Bomb variant seems noticeably easier (though still Insane), so I added a variant for that. I think ammo lenience is not a significant concern, as this is already an Insane-level strat and softlock risk is the main challenge rather than running out of ammo.
The left-to-right strat had a `canDownGrab` requirement and right-to-left had a crouch-jump requirement, neither of which made sense, so I removed them. I added requirements for the mid-air morph in the left-to-right direction.
> Sand Bomb Boost strat: add details and PB variant

- region/maridia/outer/Main Street.json
- region/maridia/outer/Mt. Everest.json
When I was thinking about this earlier, I forgot that the `comeInWithGrappleSwing` strat in Red Fish Room only gets you to the ledge, not all the way to the top of the room. So it makes sense to add a `leaveWithGrappleJump` strat to Mt. Everest after all.
> Add leaveWithGrappleJump in Everest

- region/maridia/inner-pink/Draygon's Room.json
This adds a Charge requirement which appears to have been missing. Also adds `canTrickyDodgeEnemies` as an alternative to some of the other requirements.
This was prompted by Sam's video which does a 1-cycle with Charge+Plasma beam only and without breaking the turrets: https://videos.maprando.com/video/4356
> Fix/refine Draygon Microwave Fight strat

- region/maridia/inner-pink/Crab Shaft.json
I checked this out thoroughly with TAStudio and am confident there's no way to make it onto the floating platform with a 12-tile runway Space Jump; the best candidate is extra run speed $3.1 (as the jump height drops off at $3.2), and it comes up about half a tile short still, even with last-frame Space Jump, lowest possible position in the doorway, and latest possible turnaround. Based on the note, the 18.4375 runway length is what was intended here; I must have just put in the wrong number.
I think it would be useful at some point to add a node below the floating platform, as there are many ways of getting there without necessarily being able to climb onto the floating platform; and with a flash suit, from there you could spark up either through the door or onto the floating platform.
> Fix Crab Shaft cross room space jump strat, add notes

- region/brinstar/blue/Blue Brinstar Energy Tank Room.json
- region/brinstar/green/Green Brinstar Main Shaft.json
- region/brinstar/red/Beta Power Bomb Room.json
- region/crateria/central/Landing Site.json
- region/crateria/central/Parlor and Alcatraz.json
- region/maridia/inner-green/East Sand Hall.json
- region/maridia/inner-pink/Aqueduct.json
- region/maridia/inner-pink/East Sand Hole.json
- region/maridia/inner-pink/The Precious Room.json
- region/maridia/inner-yellow/Plasma Spark Room.json
- region/maridia/outer/Main Street.json
- region/maridia/outer/Mt. Everest.json
- region/norfair/east/Double Chamber.json
- region/tourian/main/Metroid Room 1.json
- region/tourian/main/Metroid Room 2.json
- region/tourian/main/Metroid Room 4.json
These are fixes to some of the problems we found from videos on the video site. Most of them are from Sam's videos.
> Video Site Finds Pt. 1

- region/norfair/east/Acid Snakes Tunnel.json
- region/norfair/east/Bat Cave.json
- region/norfair/east/Cathedral.json
- region/norfair/east/Double Chamber.json
- region/norfair/east/Green Bubbles Missile Room.json
- region/norfair/east/Kronic Boost Room.json
- region/norfair/east/Lava Dive Room.json
- region/norfair/east/Lower Norfair Elevator.json
- region/norfair/east/Magdollite Tunnel.json
- region/norfair/east/Purple Shaft.json
- region/norfair/east/Rising Tide.json
- region/norfair/east/Single Chamber.json
When I added these strats, I forgot that heat frames aren't part of the implicit requirements when `unlocksDoors` is explicitly given. In all these cases, it doesn't cost any extra heat frames to open a Super door, and I think Power Bombs are also fine given that you're already morphing and not approaching the door too quickly. Missiles would generally be a problem though.
The 50 heat frames is the standard amount and may be more than needed. I don't think it's important to be too precise, given that it's unlikely to be important in logic and we don't have a convenient way of testing these yet anyway. The idea is just to be safe with it to avoid a possibility of unsoundness.
> Add heat frames for leaveWithTemporaryBlue missile unlock

- region/brinstar/blue/Blue Brinstar Energy Tank Room.json
- region/brinstar/red/Caterpillar Room.json
- region/crateria/central/Climb.json
- region/maridia/inner-green/Oasis.json
- region/maridia/inner-green/West Sand Hall Tunnel.json
- region/maridia/inner-pink/Aqueduct.json
- region/maridia/inner-pink/Botwoon Energy Tank Room.json
- region/maridia/inner-pink/Crab Shaft.json
- region/maridia/inner-pink/Halfie Climb Room.json
- region/maridia/inner-pink/The Precious Room.json
- region/maridia/inner-pink/West Cactus Alley Room.json
- region/maridia/inner-yellow/Plasma Room.json
- region/maridia/inner-yellow/Plasma Spark Room.json
- region/maridia/outer/Crab Hole.json
- region/maridia/outer/Crab Tunnel.json
- region/maridia/outer/Fish Tank.json
- region/maridia/outer/Glass Tunnel.json
- region/maridia/outer/Main Street.json
- region/maridia/outer/Mama Turtle Room.json
- region/maridia/outer/Mt. Everest.json
- region/norfair/crocomire/Post Crocomire Jump Room.json
- region/norfair/east/Bubble Mountain.json
- region/norfair/east/Cathedral Entrance.json
- region/norfair/east/Frog Speedway.json
- region/norfair/west/Crocomire Escape.json
- region/norfair/west/Crumble Shaft.json
- region/tourian/main/Tourian Escape Room 4.json
- region/wreckedship/main/Sponge Bath.json
- region/wreckedship/main/Wrecked Ship Energy Tank Room.json
Here are some more of the easier fixes that were found when going through the logic videos
> Video Site Finds Pt. 2

- region/norfair/east/Spiky Acid Snakes Tunnel.json
- region/norfair/east/Upper Norfair Farming Room.json
- region/norfair/east/Volcano Room.json
- tech.json
This should finish off a first pass at temp blue in East Upper Norfair. I also tightened/corrected some shinecharge frames and heat frames for shinecharge strats in Upper Norfair Farming Room. There's still stuff that can be done using a frozen Gamet to extend the runways at the bottom of this room, but those can be added later.
I also updated the tech description of `canChainTemporaryBlue` to give some more detail about the timings. Something that I think Kyle suggested a long time ago, which I think could be useful, would be to add a `detailNote` to the schema (between `note` and `devNote`), the idea being that `note` could describe what the tech covers, i.e. what you're expected to be able to do, while `detailNote` tells you more exactly how to do it. In the randomizer Generate page, …
> Rest of East Upper Norfair temp blue

- region/maridia/inner-pink/Draygon's Room.json
- Added tech requirements to the Cross Room Space Jump, where previously there were none. Avoiding the overhang in Draygon's Room requires at least somewhat precise positioning and timing of the Space Jump. I'm not sure if it's quite `canPreciseSpaceJump` but it seems like at least a `canTrickyJump`. And of course it also needed `canCrossRoomJumpIntoWater`.
- Increased the `minTiles` for "Cross Room Jump (Lenient)" from 2.4375 to 3: I tested with Construction Zone (3-tile runway with closed end) and found it still required a frame-perfect jump. It needs 3-tile with open end in order to get a 2-frame window.
- Removed the `canTrickyDashJump` requirement from "Cross Room Jump with Speedbooster". Here all you have to do is use the full (1-tile) runway and it gives a 2-frame window for the …
> Update Draygon cross-room requirements and notes

- helpers.json
- region/norfair/west/Crocomire Escape.json
- tests/asserts/keywords.py
Maddo said the tests could be edited to allow these helpers instead of heat frames.
> Add G-Mode to Croc Escape

- helpers.json
- region/norfair/crocomire/Post Crocomire Power Bomb Room.json
- region/norfair/west/Crocomire Escape.json
- region/norfair/west/Crumble Shaft.json
- region/norfair/west/Ice Beam Acid Room.json
- region/norfair/west/Ice Beam Snake Room.json
- region/norfair/west/Ice Beam Tutorial Room.json
- tests/asserts/keywords.py
Also Post Crocomire Power Bomb Room
> G-Mode: Remaining Upper Norfair West

- region/brinstar/blue/Morph Ball Room.json
- region/brinstar/pink/Pink Brinstar Hopper Room.json
- region/brinstar/red/Below Spazer.json
- region/maridia/inner-pink/Aqueduct.json
- region/maridia/inner-pink/Crab Shaft.json
- region/maridia/inner-pink/West Cactus Alley Room.json
- region/maridia/outer/Fish Tank.json
- region/norfair/crocomire/Post Crocomire Farming Room.json
- region/norfair/east/Acid Snakes Tunnel.json
- region/tourian/main/Metroid Room 1.json
- tests/asserts/keywords.py
I'm pretty sure there used to be a test for this, but it apparently got lost during a migration at some point.
- Add test to check that there aren't two strats with the same name within the same link.
- Fix existing violations.
> Test for unique strat names within a link

- region/maridia/inner-pink/West Cactus Alley Room.json
Video: https://videos.maprando.com/video/5308
The video demonstrates what seems to be a more reliable method of doing the tech:
- After pressing pause, delay the jump as much as possible, doing a very quick mid-air morph, and equip Spring Ball.
- Do the second pause close to as early as possible, and delay the first mid-air Spring Ball jump close to as much as possible. The mid-air Spring Ball jump should happen slightly after pressing pause. Unequip Spring Ball.
- Lay the Bomb slightly after coming out of the unpause, then pause again as soon as possible. Equip Spring Ball and buffer the second mid-air Spring Ball jump out of the unpause.
With this method, there is a 3-frame window for the amount of time between laying the Bomb and pressing pause again. The previous steps just need to be …
> West Cac Alley underwater bomb into Spring Ball jump

- helpers.json
- region/norfair/east/Acid Snakes Tunnel.json
- region/norfair/east/Cathedral Entrance.json
- region/norfair/east/Cathedral.json
- region/norfair/east/Green Bubbles Missile Room.json
- region/norfair/east/Kronic Boost Room.json
- region/norfair/east/Magdollite Tunnel.json
- region/norfair/east/Norfair Reserve Tank Room.json
- region/norfair/east/Purple Shaft.json
- region/norfair/east/Rising Tide.json
- region/norfair/east/Single Chamber.json
- region/norfair/east/Speed Booster Hall.json
- region/norfair/east/Upper Norfair Farming Room.json
- region/norfair/east/Volcano Room.json
- region/norfair/west/Crocomire Escape.json
- region/norfair/west/Crocomire Speedway.json
- region/norfair/west/Crumble Shaft.json
- region/norfair/west/Ice Beam Snake Room.json
- strats.md
- tech.json
- tests/asserts/keywords.py
Its uses should be able to be added implicitly. I'm not expected that entering and exiting a heated room while already in G-mode to require this, but might not matter much either way (i.e. enterring Caterpillar Room in direct, using the elevator into LN Elevator Room and returning to despawn the gate)
> Add canHeatedGMode

- region/brinstar/red/Below Spazer.json
This is an X-ray climb up the left side of Below Spazer, only useful if walljump is unavailable:
Video: https://videos.maprando.com/video/5405
> Below Spazer left-side X-ray climb

- region/brinstar/pink/Pink Brinstar Hopper Room.json
While reviewing a recent video by Sam (https://videos.maprando.com/video/4680), I noticed that the logic is requiring a longer runway for this strat than is required. This jump has two narrow windows of other-room runway length that work, one around 2 tiles and one around 7. And then anything above 14 tiles (including a little lenience) will work.
So this PR tightens the "Tricky Speedy Spring Ball Jump" strat, and also adds a less tricky version for when at least 14 tiles are available.
> Refine Pink Brin Hoppers right-side speedy spring ball jump

- region/maridia/inner-green/Oasis.json
- schema/m3-note.schema.json
- schema/m3-room.schema.json
- tests/asserts/keywords.py
- Update the notes of the strats that use Screw Attack to jump up through the top door of Oasis.
- Add blue speed variations that don't require Screw Attack.
- Add schema for `detailNotes`.
The existing notes here very much overstate how much precision is needed in the amount of runway to use. There's a wide range that works well, with only a slight benefit to using the minimal amount of 13 tiles. The blue speed version was also not so bad: with a 2-tap, I could consistently get run speed in a good range, and from there the trick is the same as the version with Screw Attack.
Videos for the blue speed version:
- left-to-right: https://videos.maprando.com/video/5482
- right-to-left: https://videos.maprando.com/video/5483
> Refine Oasis jump-through-top-door strats, add detailNotes schema

- region/norfair/east/Lava Dive Room.json
- region/norfair/east/Spiky Acid Snakes Tunnel.json
This is the end of Upper Norfair! 
Most of these strats are just copies of the non-G-mode variants with removed heat frames. I skipped adding the G-mode strats in Lava Dive without Gravity - it felt too complex and very unlikely to ever be useful. 
Also cleaned up `disableEquipment` to describe what needs to be disabled in these two rooms, and used `gravitylessLavaFrames` for Lava Dive strats that could not be done with Gravity equipped.
> G-Mode: Spiky Acid Snakes, Lava Dive

- region/norfair/west/Crocomire Escape.json
- region/norfair/west/Crumble Shaft.json
- region/norfair/west/Hi Jump Energy Tank Room.json
- region/norfair/west/Ice Beam Acid Room.json
- region/norfair/west/Ice Beam Gate Room.json
This just leaves Crocomire Speedway for a separate PR. I'm also skipping Ice Beam Tutorial Room and Ice Beam Snake Room, which probably have some dumb things that could be done to carry temp blue through them.
This also includes a new mockball strat for Ice Beam Gate Room left-to-right, using Speedbooster to do it with a much shorter other-room runway, by delaying the mockball until right before the gate.
> Most of rest of West Norfair temp blue

- region/maridia/inner-green/East Sand Hall.json
- region/norfair/west/Ice Beam Gate Room.json
- schema/m3-room.schema.json
- Adds a notable strat Ice Beam Gate Room: Anti-Short Charge Hero Shot.
- Adds a property `minExtraRunSpeed` to `leaveWithRunway`, to represent the new strat.
- Adds a "Cross-Room Blue Speed Jump" strat in East Sand Hall, which can match with the new strat in Ice Beam Gate Room. 
- Adds "comeInNormally" entrance conditions to Ice Beam Gate Hall strats that rely on the gates still being up (since we don't have an obstacle to represent their state).
There's already a "Cross-Room Blue Speed Jump, Leave With Temporary Blue" strat in East Sand Hall. The only reason the more simple "Cross-Room Blue Speed Jump" didn't already exist is because I was thinking it was covered by the "Cross-Room Speed Jump", which doesn't need as much runway. But that one has a specific run speed requirement which …
> Ice Beam Gate Room anti-shortcharge

- region/maridia/outer/Fish Tank.json
The Fish Tank "Wall Jump Entry" works differently enough when passing through the Toilet that it makes sense to have a separate strat for it. This way we can tailor the note in that situation, to explain the key differences like wall jumping from the left side and releasing jump to shorten Samus' hitbox vertically.
> Separate Toilet version of Fish Tank Wall Jump Entry

- region/maridia/inner-pink/The Precious Room.json
- schema/m3-tech.schema.json
- tech.json
I noticed that during the second seed of Nito's recent 24hr stream, he got Gravity early by sequence breaking the Precious Room stutter water shinecharge, doing it with 2 runway tiles when the logic required 2.4375.
I dug into it a little to see how the runway length affects the frame window, and concluded that we could probably use some more tech to help place strats into an appropriate difficulty level. We moved "canStutterWaterShinecharge" down to Very Hard a while ago, but in Precious Room with only 2.4375 tiles I think it's too tough for Very Hard, and would fit better in Expert. With only 2 tiles, I think it fits in Extreme, because this case needs a double-frame-perfect stutter: releasing for exactly 3 frames, and repressing on the last possible frame.
- New tech …
> Refine Precious Room shinecharge/shinespark strats

- region/maridia/inner-green/Oasis.json
- tests/asserts/keywords.py
Similar to Precious Room, this adds new nodes to represent having just gained a shinecharge while running into the room. It helps because there are many ways to gain the shinecharge and also many ways to use it. With this way of doing it, many strats are covered that were missed before. I also tightened shinecharge frames and shinespark frames.
Probably the most interesting addition is the way to do the stutter shinecharge using only 1 tile of runway. It requires being able to open the opposite door, and it needs a not-so-intuitive subpixel normalization in the other room, along with a double frame-perfect stutter. This one I think fits in Insane, with `canBeVeryPatient` (could be improved with a more specific tech later). I created videos for these, showing all 3 ways that I know of to …
> Refine Oasis shinecharges

- region/maridia/inner-green/Oasis.json
- region/maridia/inner-green/West Sand Hall Tunnel.json
The changes here are similar to in Oasis, except with a crab to deal with.
The left-to-right comeInShinecharging strat with Gravity seemed fairly questionable, so I removed it for now. It could probably be added back in some form, given reliable ways to deal with the crab, but I just left it as a FIXME for now. It seems like a stutter water shinecharge would generally be a better option there anyway.
> Refine West Sand Hall Tunnel shinecharges

- region/brinstar/blue/Blue Brinstar Energy Tank Room.json
- region/maridia/inner-pink/Below Botwoon Energy Tank.json
- region/maridia/inner-pink/Colosseum.json
- region/maridia/outer/Crab Hole.json
- region/tourian/main/Metroid Room 1.json
- region/wreckedship/main/Bowling Alley.json
- schema/m3-room.schema.json
- Adds side platform strats for going from the bottom right of Colosseum to the top right.
- Fixes a small bug in a Crab Hole side platform strat.
- Adds more notes to some setups. There are still more details that could added, especially for describing setups that only use part of the available runway (since this can sometimes be easier than using a full runway).
- Adds "environment" property to platforms in the entrance condition `comeInWithSidePlatform`, to be able to specify if it's required for the neighboring room to be water (with Gravity). Where applicable, doing a Gravity jump before the transition makes both momentum-conserving turnarounds and ceiling mockballs easier due to the slower underwater animations, in addition to its main effect of preserving greater vertical speed. In …
> Colosseum side platform applications

- region/tourian/main/Tourian Escape Room 4.json
- schema/m3-room.schema.json
- strats.md
This addresses a long-standing issue (#1001) about marking strats that are only useful in walljumpless contexts. This PR just adds a new boolean property `wallJumpAvoid` to strats and notables, along with an example. Later PRs would go through and populate this throughout the logic.
Based on the discussion in the issue, one alternative that was considered was implementing a more general `tag` property. However, after thinking about this some more, it seems that a simple tag would not work well for the other examples mentioned in the issue. For example, to model a strat that softlocks you at an item location, we would want to model more information such as the specific item and/or tech that could get you out of the softlock. The existing "failures" schema is also relevant to modeling …
> Add wallJumpAvoid to strat and notable schema

- region/maridia/outer/Main Street.json
We played a bugged seed that expected `G-Mode Morph IBJ Overload Speed Blocks` Without Morph Bombs.
> Fix Main Street Gmode Requirements

- helpers.json
- logicalRequirements.md
- region/tourian/main/Mother Brain Room.json
- schema/m3-requirements.schema.json
In the first few months of Map Rando, we heard that cemo knew a way to clip past Mother Brain from the left, using a Crystal Flash, moondance, and ice clipping. Finally got around to working out the details. This can be interesting because with G-mode artificial morph it's possible without Morph. Compared to the Halfie Climb grapple teleport (the only other known way to do Mother Brain without Morph), this technique is much more broadly applicable.
Videos:
- https://videos.maprando.com/video/6000
- https://videos.maprando.com/video/6001
- https://videos.maprando.com/video/6002
> Mother Brain left-to-right clips

- region/brinstar/kraid/Baby Kraid Room.json
- region/crateria/central/Flyway.json
- region/maridia/inner-pink/Colosseum.json
- region/maridia/inner-pink/Crab Shaft.json
- region/maridia/inner-pink/Halfie Climb Room.json
- region/maridia/inner-pink/The Precious Room.json
- region/maridia/inner-yellow/Maridia Elevator Room.json
- region/maridia/outer/Crab Hole.json
- region/maridia/outer/Fish Tank.json
This strat is only useful in a situation where wall-jump is unavailable and you want to preserve a flash suit (and so can't crouch-jump down-grab).
Removing the "canInsaneMidAirMorph" requirement from the Baby Kraid Room side platform setup, since depending on the runway length used, it is not necessarily that difficult. The "canInsaneMidAirMorph" can still be applied to individual applications as needed.
> Maridia Elevator Room L->R side platform jumps

- region/tourian/main/Mother Brain Room.json
This fixes a bug found by Selicre: the Speed Zebetite Skip strats were missing a Morph requirement.
> Add Morph req to speed zebetite skip

- region/brinstar/pink/Waterway Energy Tank Room.json
- region/maridia/inner-pink/Aqueduct.json
This refines the water shinecharge strats entering from the bottom-left door of Aqueduct. This time I took a closer look at how the runway length affects the amount of frames remaining with "Leave Shinecharged" strats. It turned out to make a fairly big difference. Making 5 strats for the various runway lengths might seem like a bit of overkill, but there are applications for each case; maybe someday we'll be able to reference the runway length in the `requires` so that they wouldn't have to all be separate strats. Once this PR is merged, I plan to go back and apply the same refinement to `leaveShinecharged` variants in the other rooms (e.g. Precious Room, West Sand Hall Tunnel, Oasis).
Example applications:
1 tile, Screw Attack Room: https://videos.maprando.com/video/5923
2 tiles, …
> Aqueduct shinecharges

- region/maridia/outer/Main Street.json
- Fixed a misunderstanding between Bomb/PB to kill the crab (thanks Eddie)
- Removed `canBeVeryPatient` from strats that can keep the top crab in position, instead of waiting for the global crab to cycle the room
- Removed `canBeVeryPatient` from strats that use crouch jump + bombs to overload the speed blocks (It's not that hard to get 2 bombs per jump, which gives plenty of time, otherwise Ice can help)
> G-Mode: Refine Main Street Speed locked item

- region/norfair/crocomire/Grapple Tutorial Room 3.json
This is mainly useful if for some reason Gamet damage boost is not possible (e.g. if their damage value is increased). In any case, logically it can at least save a bit of energy.
> Grapple Tutorial Room 3 side platform jumps

- region/lowernorfair/east/Ridley's Room.json
- region/maridia/inner-pink/Halfie Climb Room.json
- tests/asserts/keywords.py
This also updates the test to collect the `requires` from side platform entrance conditions and include them in the checks on the `requires`. It is treated as if all the platform `requires` are joined by an `or`, appended to the main strat `requires`. In order to avoid triggering false positives on the `and`/`or` tests, we have to be careful how the `and` and `or` here are constructed.
> Ridley Room side platform jumps

- region/maridia/inner-green/Oasis.json
- region/maridia/inner-green/West Sand Hall Tunnel.json
- region/maridia/inner-pink/The Precious Room.json
These are essentially copied from the bottom-left Aqueduct strats, with a few necessary adaptations:
- In Oasis and West Sand Hall Tunnel, for the 1-tile runway variation, we have to unlock the opposite door.
- In West Sand Hall Tunnel, we have to kill the crab in the left-to-right strats. I checked that right-to-left there is time to jump over the crab (tested with 1-tile and 5-tile runway variants).
- In Precious Room, there's no 1-tile runway variation since there's not enough space; you would run into the wall before being able to gain the shinecharge.
In all of these, I removed the existing "Leave Shinecharged" strats. These started from a shinecharged junction node, and the location of the node is not defined precisely enough to use for this (i.e., since the exact location where you …
> Refine water shinecharge return in Oasis, Precious, and West Sand Hall Tunnel

- region/lowernorfair/east/Fast Pillars Setup Room.json
I created a bunch of videos a while ago for doing side platform jumps at this location. But then today when I came back to it, I realized that with 1 tile of air runway, you can do this tricky dash jump. It's dangerous (risk of hitting of the Space Pirate) but probably not any more than the side platform jumps, so with this I think there's not much reason to add strats for the side platform jumps.
Video: https://videos.maprando.com/video/6177
> Fast Pillars Setup cross-room tricky dash jump

- region/brinstar/kraid/Baby Kraid Room.json
- region/lowernorfair/west/Screw Attack Room.json
This is mainly useful as an alternative to shinesparking, in order to preserve a flash suit. It can also save some energy.
The test failure should be resolved after #2026 is merged (which can be done first).
Updated the Baby Kraid Room right-side setup note. Using the overhang makes the setup faster, and doing 4 arm pumps give you a 2nd possible frame for the morph, something I had missed before.
> Screw Attack Room left-to-right side platform jumps

- region/norfair/west/Crocomire Escape.json
This adds a couple notable strats based on videos that Sam recently shared:
- Ceiling Mockball Spring Fling:
- original video by Sam: https://videos.maprando.com/video/6221
- video from room entry, for measuring frames: https://videos.maprando.com/video/6228
- Spring Ball Jump into Damage Boost:
- original video by Sam: https://videos.maprando.com/video/6061
- video from room entry, for measuring frames: https://videos.maprando.com/video/6229
There's more work that can be done in the room. I didn't look into the frozen Geruta walljump variant, and Kyle also mentioned a G-mode setup with the Geruta.
> Croc Escape spring ball strats

- region/brinstar/pink/Big Pink.json
- Add missing remote acquire strats (still missing remote acquiring both items simultaneously, but not planning on adding that)
- Add missing strats that leave at 4 while still in G-mode
- Add missing Spring Flings to the top item and from the middle item going up
- Room cleanup
> G-Mode: Big Pink Overhaul

- region/brinstar/pink/Big Pink.json
A few months ago I thought this side platform jump into "Super Block Speedball" seemed Insane-level and wasn't able to get it without a save state in the door transition. Trying it again, I found that doing a slower shortcharge can make it more lenient (ideally you want not much more than $1.2 extra run speed, which is where a drop-off in jump height happens) . I think it still seems Insane if the setup is heated?
This also adds a `comeInBlueSpaceJumping` variant of the strat.
> Big Pink side platform jumps

- region/lowernorfair/west/Golden Torizo's Room.json
When I looked at this a few months ago, I thought some of these would be Beyond. But with a better understanding now of how to set these up, they are seeming fine in Extreme and Insane. The main things that make it easier are
1. Pause buffering the morph input. This breaks up the tight input sequence, and makes it more reliable to use a visual cue for the pause press to get a consistently timed morph.
2. Using a shorter runway (in the long setup rooms). Having too much horizontal speed makes the timing for the unmorph tighter, or even impossible depending on the morph timing. Since you have to wait for the morph animation to finish before unmorphing, in that time you could overshoot past the bomb blocks if your speed is too high. And of course, at lower speeds it is also easier to time a …
> Golden Torizo side platform jumps

- region/maridia/inner-pink/Botwoon Energy Tank Room.json
- The existing strats required 2 runway tiles in order to stutter water shinecharge here. This PR adds 1-tile options, with the `canPreciseStutterWaterShineCharge` tech. With 1 runway tile, it requires a 1 or 2 frame release of forward, and a last-frame forward repress, which seems ok for Expert.
- Options are added to go back out through the right door with temporary blue or shinecharged. For the "Leave Shinecharged" variants, I just copied the strats from Aqueduct. In theory, the slopes will slow down your horizontal movement while running into the room, making it so you cover relatively more ground while spin jumping back out. So for some of these it should be possible to leave with slightly more frames remaining here compared to Aqueduct, but I don't think it's significant enough to …
> Refine Botwoon ETank right-side shinecharges

- region/brinstar/green/Brinstar Reserve Tank Room.json
- region/brinstar/green/Green Brinstar Main Shaft.json
- region/brinstar/green/Green Hill Zone.json
- tests/asserts/keywords.py
This is for the remaining parts of Green Brinstar. Etecoon E-Tank is in a separate PR, because it was known to be missing a lot of strats.
> Refine G-Mode: Green Brinstar

- region/brinstar/green/Green Brinstar Main Shaft.json
- region/brinstar/green/Green Hill Zone.json
- region/brinstar/pink/Pink Brinstar Hopper Room.json
- region/crateria/east/The Moat.json
- region/lowernorfair/east/Fast Pillars Setup Room.json
- region/lowernorfair/east/Ridley's Room.json
- region/lowernorfair/west/Screw Attack Room.json
- region/maridia/inner-pink/Halfie Climb Room.json
- region/maridia/inner-pink/The Precious Room.json
- region/maridia/inner-yellow/Maridia Elevator Room.json
- region/norfair/crocomire/Grapple Tutorial Room 3.json
- region/norfair/east/Bubble Mountain.json
Kyle pointed out this Green Hill Zone setup. It has a 4-tile-long obstruction, which makes it have very limited use. It only seems to be usable with the gate open, with the only application being jumping up the bottom left of Maridia Elevator Room.
The Halfie Climb Room setup was too short because I forgot about being able to shoot out the shot blocks. In theory there could be situations where the Oums get in your way, but it didn't seem like it's really a problem. If needed we could add a `comeInNormally` entrance condition.
This should wrap up the first pass at side platforms.
> Add Green Hill Zone side platform setup, extend Halfie Climb setup

- region/maridia/inner-pink/Crab Shaft.json
- Added a junction node 5 representing getting a shinecharge after running in from the left door.
- Added temporary blue chain strats from there to all 3 doors.
- Refined the shinespark frames and excessFrames for the strat that shinesparks up. The old value of 6 excess frames was unsound for getting onto the top platform.
> Refine Crab Shaft shinecharges

- region/crateria/east/Crab Maze.json
There's already a "Leave with Spark" water shinecharge strat here in Very Hard that can only spark out in bottom position. The new strat can make it out with frames remaining. Without canInsaneJump, the extra lenience is designed to make it so that in Expert you would only be expected to spark at the doorway, not actually leave with frames remaining.
Video: https://videos.maprando.com/video/6401
> Crab Maze leave shinecharged

- region/norfair/east/Spiky Acid Snakes Tunnel.json
- With no runway (e.g. water in the other room), this is doable with 390 heat frames, compared to 420 that was listed. This makes it now logical to do tankless (in Insane).
- The existing strat for a 3-tile appeared to be unsound: the heat frames matched what I could get with a 4-tile runway. I'm guessing this was written back when we had some confusion about whether the door shell tile was supposed to be included as part of the runway or not.
- I added strat variants for each of the possible runway lengths up to 4 tiles.
- At 4 tiles, without Speed Booster you already reach max speed, so longer runways above that won't help. But with Speed Booster, longer runways do help, so I included strats for a sample of them.
It's a bit annoying to have to create separate strats for each variant, …
> Refine Spiky Acid Snakes Tunnel space jump strats

- region/tourian/main/Tourian Escape Room 3.json
Was going through Sam's videos and noticed this was missing: https://videos.maprando.com/video/5861
> Add missing spring ball jump options in Escape Room 3

- region/norfair/east/Spiky Platforms Tunnel.json
I was reviewing Sam's videos and noticed that he managed to get through on 1 tank using no runway: https://videos.maprando.com/video/5104, showing that this could work from a water entrance. So this PR adds this to logic. Looking over the room again, also made a few more fixes/refinements:
- The bounceball strats were misleadingly named "Bounceball Double Lava Bath" even though they only do one lava bath.
- The right-to-left "Shorter runway" was expecting a 3-tile runway when it was supposed to be 1-tile.
- Tightened the heat/lava frames a bit and made videos to demonstrate each of the runway length (0, 1, 3).
> Refine spiky platform bounceball strats

- region/lowernorfair/east/Fast Pillars Setup Room.json
Sam's video shows doing this with 6 Supers while only taking one Pirate laser hit: https://videos.maprando.com/video/5964. I tried it out and found it works reliably; it's just a little tricky because of the long cooldown coming out of X-ray, and it helps to fire the last shot diagonally. Found that Charge+Plasma also works reliably, with a similar degree of trickiness.
> Refine fast pillars setup top-left x-ray climb

- region/tourian/main/Tourian Escape Room 4.json
With nothing, killing all the Pirates here takes quite a long time, which doesn't seem fair for Basic. And even for Hard, if you were in a situation where you really had to kill them (e.g. walljumpless with IBJ) and had no weapons, I think it would feel pretty bad. So this splits off "Evade Pirates" and "Tank Damage" strats from the "Base" kill strat. There could possibly be more options here, so let me know if I missed something.
> Add reqs to deal with Pirates in Escape Room 4 L->R

- logicalRequirements.md
- region/lowernorfair/east/Ridley's Room.json
- schema/m3-requirements.schema.json
- tests/asserts/keywords.py
This replaces the Ridley `enemyKill` requirement with a new logical requirement `ridleyKill`, with some documentation on how the ammo/energy can be calculated. This way it's less of a magical thing happening on the randomizer side. I would like to do this same sort of thing with the other bosses. With this, the existing boss scenarios could probably be removed.
The new G-mode CF Ridley strats still require handling different combinations of ammo/beams/patience which would be unreasonably complicated to handle precisely without the boss calculation, which is the motivation for supporting this using `gMode` and `stuck` properties inside the `ridleyKill` object. The existing `enemyKill` schema was limiting because it didn't allow us to include boss-specific properties like this.
Doing a …
> Ridley G-mode and ridleyKill requirement

- region/maridia/outer/Mama Turtle Room.json
In some cases, the item/junction nodes at the top of the room can be reachable without "On Mama Turtle" (node 4) being reachable. So to prevent weird-looking gaps in the spoiler map, we need to expand the set of tiles included in those item/junction nodes at the top of the room:
> Adjust Mama Turtle node map tiles

- region/tourian/main/Metroid Room 2.json
I started going through the backlog of Incomplete videos by Sam and saw several strat options were missing for going up the left side of Metroid Room 2. These are mostly walljump-avoid strats, but not strictly since they also avoid `canMidairWiggle` tech. 
There's also a two-tile squeeze strat for top-to-bottom which surprisingly appears slightly faster than the moonfall and Morph variants. The difference seemed not quite enough to justify tightening the shinecharge frames though. It feels more difficult than the moonfall/Morph options overall but easier to avoid Metroid damage so it can be a viable strat. The Metroid damage scaling for this strat in general (across all the variants) seemed a bit unreasonable, because if you don't do it just right then you take like 10x more Metroid …
> Refine some Metroid Room 2 shinecharges

- region/brinstar/pink/Big Pink.json
As I recently learned, those enemies are not called Zebbos but Zebs.
Since the devnote was part of a 2->12 strat, I think `1->15->12` is probably an oversight?
No idea if this pr is problematic since there's another one open for the same file right now.
> minor fixes to Big Pink

- region/brinstar/green/Green Hill Zone.json
- region/norfair/east/Double Chamber.json
Also add missing indirect strats in Double Chamber
> Direct G-mode open blue gates

- region/tourian/main/Seaweed Room.json
- Bugfix: the 3->1 strats were missing a Wave requirement.
- Add strats based on Sam's method to carry a shinecharge from bottom-right to bottom-left without Wave.
- Likewise, add strats to carry shinecharge from bottom-left to bottom-right without Wave.
- Refine/tighten shinecharge frames throughout (and add videos to document them).
- Include comeInShinecharging+leaveShinecharged variants that were skipped before.
> Refine Seaweed Room shinecharges

- region/lowernorfair/east/Fast Pillars Setup Room.json
- region/norfair/east/Red Pirate Shaft.json
Videos:
- Red Pirate Shaft: https://videos.maprando.com/video/2264
- Fast Pillars Setup Room:
- original video by Sam: https://videos.maprando.com/video/2515
- full video showing setup and with Charge+Ice only: https://videos.maprando.com/video/6961
> A couple more moonfall clips

- region/brinstar/red/Below Spazer.json
This is based on a recent Bobbob video:
https://www.youtube.com/watch?v=_ynzaEpkBEs
I tested it out and found there's a decent range of speeds that work.
> Below Spazer CWJ jump shot speedball

- logicalRequirements.md
- region/norfair/east/Volcano Room.json
- schema/m3-requirements.schema.json
- schema/m3-room.schema.json
- Handle heated runway at top door
- Handle locked doors at bottom
- Tighten lava frames for top-to-bottom suitless strat
- Remove stray `heatFrames` on the bottom leaveWithRunway strat.
> Refine Volcano Room

- region/brinstar/pink/Big Pink.json
I noticed that even sparking out here wasn't in VH logic. It's currently expecting leaving shinecharged with 25 frames remaining, and VH would need 30. My best attempt leaves with 40. Proposed logic would be leaving with 35.
If we didn't want this in VH logic we could upgrade it to canShinechargeMovementTricky. I think it's probably ok though?
> Tighten Big Pink right-side tunnel leaveShinecharged

- region/brinstar/pink/Dachora Room.json
- region/brinstar/pink/Mission Impossible Room.json
- region/brinstar/pink/Pink Brinstar Wave Gate Room.json
- region/brinstar/pink/Spore Spawn Farming Room.json
- region/brinstar/pink/Spore Spawn Super Room.json
- region/brinstar/pink/Waterway Energy Tank Room.json
Aside from the farm migration, this PR reworks the "Doorway Sidehopper Kill" strat in Mission Impossible Room and turns it into a notable strat. This is moving it up from Very Hard to Expert as I found it was trickier to do reliably than I had expected; the trick I found was to delay shooting the Hopper until after it hops 4 times, which is not very intuitive. For the doorway strat, I don't think additional beams or Morph really affect the difficulty, as the main thing is knowing how to manipulate the Hopper RNG to avoid getting hit in the doorway. And of course, if you have strong enough weapons then it's already covered by other strats that don't involve getting in the doorway.
> Pink Brinstar farms

- region/brinstar/kraid/Baby Kraid Room.json
- region/brinstar/kraid/Kraid Eye Door Room.json
- region/brinstar/kraid/Warehouse Energy Tank Room.json
- region/brinstar/kraid/Warehouse Kihunter Room.json
- region/brinstar/kraid/Warehouse Zeela Room.json
For Warehouse Kihunter Room, I did separate farm strats for each of the three doors where you can reset the room, because the way you interact with the Kihunters differs so much based on which direction you're coming from.
> Warehouse Brinstar farms

- region/brinstar/kraid/Kraid Eye Door Room.json
I believe the strat is unsound the way it is currently written. With 40 frames there's not enough time to get over the pillar, so top position would be the only option.
> Restrict position of Kraid Eye Door hero shot spark

- .github/workflows/run_scripts.yml
- schema/m3-room.schema.json
- scripts/format_json.py
This fixes a couple issues with auto-formatting:
- Certain kinds of objects weren't being formatted on one line when they should have been. Most noticeably this was affecting `resetRoom` requirements.
- The GitHub action ("Run Scripts") was not performing schema ordering as part of auto-formatting.
This is also switching the order of a couple things in `leaveWithSidePlatform` to align with what is used in most places.
> Fix some issues with auto-formatting

- region/crateria/east/The Moat.json
- region/maridia/outer/Mama Turtle Room.json
This was one of the items on Bobbob's list from a couple years ago (https://github.com/vg-json-data/sm-json-data/issues/2149).
I'm thinking this is probably an Extreme notable, though maybe it could be Insane.
This bomb boost strat can be useful if the door on the left is locked since the usual CWJ strat won't work in that case.
Video: https://videos.maprando.com/video/7142
> Moat CWJ bomb boost

- region/maridia/inner-pink/Halfie Climb Room.json
- leaveWithTemporaryBlue strats from bottom-left door to top-right without X-Ray
- leaveWithTemporaryBlue strats using frozen Mochtroids
- low-speed comeInBlueSpinning from top-right into leaveWithTemporaryBlue top-left.
> Halfie Climb temp blue updates based on Sam videos

- region/norfair/crocomire/Post Crocomire Shaft.json
Videos:
- original by Sam https://videos.maprando.com/video/6635
- a slight variant (not holding angle): https://videos.maprando.com/video/7170
- for comparison, the version with a Super: https://videos.maprando.com/video/7171
> Post Croc Shaft superless moonfall option

- region/norfair/east/Rising Tide.json
This had the wrong entrance condition before. 
Videos:
- comeInGettingBlueSpeed: https://videos.maprando.com/video/6665
- comeInBlueSpinning: https://videos.maprando.com/video/7172
> Refine Rising Tide speedball

- region/maridia/inner-green/Pants Room.json
Avoiding the Menus doesn't seem bad, by just grapple jumping up all the way to the top.
Video by Sam: https://videos.maprando.com/video/6717
> Add dodge option for Pants Room grapple jump

- region/maridia/inner-pink/Aqueduct.json
Video: https://videos.maprando.com/video/6751
> Aqueduct damageless snail stuck moonfall

- region/crateria/central/Climb.json
I'm getting interested in generalizing `heatFramesWithEnergyDrops` and `lavaFramesWithEnergyDrops`, rather than adding a new one `shinesparkWithEnergyDrops`, which would apply here.
Video: https://videos.maprando.com/video/6761
> Climb frozen pirate behemoth spark

- region/norfair/west/Crumble Shaft.json
- Many heat frames are tightened.
- More lenience is added to the wall-jump climbs on low difficulty (especially Medium)
- Some apparently non-useful strats are removed:
- HiJump Climb: The instruction to wall jump directly off the top-right crumble block seemed questionable; using the floating crumble platform is much easier and also seems faster. I combined this with the bootless version since there doesn't seem to be a reason for it to be a separate strat.
- WallJump and SpringBall: The problem is the Sova gets in your way where you want to bounce with Spring Ball. You can wait for it with canStaggeredWalljump, or bounce in a very precise place on the edge of the crumbles; but these both seem more difficult than just wall jumping the regular way off the side of the crumble block.
- …
> Refine Crumble Shaft

- region/crateria/east/The Moat.json
More finds from Sam's videos:
- For the Gravity jump variant, it can be done relatively easily without any jump assist (HiJump/SpringBall).
- Blue spring ball bounce L->R is a new interesting option.
> Refine Moat temp blue

- region/maridia/inner-pink/Botwoon Energy Tank Room.json
- region/maridia/inner-pink/Halfie Climb Room.json
- region/maridia/inner-pink/West Cactus Alley.json
This is the rest of Pink Maridia, excluding East Cac Alley.
I also didn't add any strats for Botwoon. I figured G-mode would help with accuracy, as the rest of the body doesn't appear, but apparently it still has collision. Is it beneficial to add G-mode Botwoon strats just to help avoid the projectiles (from the left and right)?
> Most of Pink Maridia G-Mode: Second Pass

- region/crateria/central/Climb.json
Videos:
- Screw Attack (with setup): https://videos.maprando.com/video/7204
- Power Beam: https://videos.maprando.com/video/7203
> Behemoth spark while farming

- region/brinstar/pink/Big Pink.json
- region/brinstar/red/Red Tower.json
- region/crateria/central/Landing Site.json
- region/crateria/east/West Ocean.json
- region/crateria/west/Gauntlet Energy Tank Room.json
- region/crateria/west/Gauntlet Entrance.json
- region/lowernorfair/east/Lower Norfair Fireflea Room.json
- region/lowernorfair/east/The Worst Room In The Game.json
- region/lowernorfair/east/Three Musketeers' Room.json
- region/lowernorfair/west/Golden Torizo's Room.json
- region/maridia/inner-green/Pants Room.json
- region/maridia/inner-pink/East Cactus Alley.json
- region/maridia/inner-pink/The Precious Room.json
- region/maridia/inner-yellow/Maridia Elevator Room.json
- region/maridia/inner-yellow/The Beach.json
- region/maridia/outer/Mt. Everest.json
- region/norfair/crocomire/Grapple Tutorial Room 3.json
- region/norfair/east/Bubble Mountain.json
- region/norfair/east/Double Chamber.json
- region/norfair/east/Lava Dive Room.json
- region/norfair/west/Crumble Shaft.json
- region/tourian/main/Metroid Room 1.json
- tech.json
Following a suggestion by @kjbranch this introduces a new tech `canTrickyWalljump` which replaces both `canDelayedWalljump` and `canStaggeredWalljump`. The idea is that individually these tech don't make a lot of sense:
- Staggered walljumps just meant wall jumping in place, but on its own that doesn't really represent any new knowledge or difficulty on top of `canConsecutiveWalljump`. 
- `canDelayedWalljump` made some sense in how it expressed an ability to control the horizontal position of the wall jump. But there's nothing that special about being able to control the horizontal position as opposed to other elements like the vertical position or the timing of the wall jump.
In practice the ability to do wall jump strats seems determined less by specific tech knowledge and more by an …
> Wall jump tech adjustments

- region/norfair/crocomire/Indiana Jones Room.json
This was done to clean up the strats and make it more clear what to do. There is a lot going on still, so maybe it would be worth adding a junction node back, but it is not immediately clear how to best do that.
Also worth noting that the some of the old artificial morph strats required "canIBJ" instead of its morphless variant.
> Indiana Jones G-Mode Restructure

- region/brinstar/blue/Blue Brinstar Energy Tank Room.json
- region/brinstar/blue/Morph Ball Room.json
- region/crateria/central/Landing Site.json
- region/crateria/east/Crab Maze.json
- region/crateria/east/West Ocean.json
Completes several missing things in #2149
> G-Mode Fixes from Bobbob's List

- region/brinstar/red/Red Brinstar Fireflea Room.json
There is already a 2->3 Damage Boost strat in Very Hard. This PR adds a 2->4 version, which does the same thing except it also continues using the Waver for i-frames and then lands on the safe platform below. I'm thinking this should be fine in Very Hard since it doesn't have to do the tricky damage boost at the end and also has no need to do the entry quickly (since the second Waver cycle is fine). Landing on the safe platform is a bit tricky and we could add a spike hit requirement if it's an issue. 
I'm hoping this will help smooth the difficulty curve, by giving VH players more exposure to this easier version of the damage boost. If the items are available to go 4->1, this new strat can also reduce the logical damage (taking only 3 Waver hits instead of 6).
Videos:
- Extra Waver hits …
> Refine X-Ray dboost strats

- region/maridia/inner-yellow/Plasma Spark Room.json
- region/maridia/inner-yellow/Watering Hole.json
This was supposed to be an Expert notable now, but that isn't working as intended because of the `canInsaneJump` requirement. So this downgrades it to a `canTrickyJump`.
> Downgrade Plasma Spark precise crouch jump

- region/norfair/east/Bat Cave.json
- region/norfair/east/Bubble Mountain.json
- region/norfair/east/Cathedral Entrance.json
Bubble Mountain is chaos.  I treated it as 3 Sovas = Cac = Ripper as a source of supers to trim a few combinations.  And wavers are added when they are in the way.
> UN East farms part 1

- region/norfair/east/Cathedral.json
- region/norfair/east/Double Chamber.json
- region/norfair/east/Frog Speedway.json
- region/norfair/east/Green Bubbles Tunnel.json
- region/norfair/east/Kronic Boost Room.json
- region/norfair/east/Lava Farm Tunnel.json
Tell me what you think of moving the pause abuse into a lead-in strat to the farm, to keep the heat frames and such separate.
> UN East Farms Part 2

- region/maridia/inner-yellow/Plasma Room.json
I'm thinking Extreme for the lenient version of this (assuming 2 hits), Insane for killing all 4 Pirates damageless.
> Plasma Room damage-avoiding pseudo screw

- region/maridia/inner-green/East Sand Hall.json
Sam shared videos of all of these a while ago.
I wasn't sure if we might want to consolidate some of the notables in this room but figured that can be postponed to a later PR if needed. The existing notable "Cross Room Jump with Ice or Damage Boost" seems maybe obsolete since the "Suitless Bootless Evir Freeze (Left to Center)" is relatively simple and has no runway or damage requirements.
I was thinking probably Insane for the Door Stuck Flatley Jump (especially since in all useful cases it has to be combined with the water-to-water door stuck setup), and Extreme for the others.
Videos:
- Suitless Bootless Evir Freeze (Left to Center): https://videos.maprando.com/video/6774
- Suitless Bootless Evir Climb: https://videos.maprando.com/video/4589
- Door Stuck Flatley Jump: …
> More East Sand Hall notables

- region/maridia/inner-pink/Botwoon Energy Tank Room.json
I would have liked for this to be able to start from node 7 to avoid duplication, but that node can be reached while in speedball or blue spring ball bounce so it wouldn't be valid for gaining a shinecharge. Adding another junction node would also be another option; it just seemed maybe not quite worth it.
> Botwoon E-Tank Room: add left-side suitless leaveShinecharged

- region/norfair/east/Bubble Mountain.json
- region/norfair/east/Cathedral Entrance.json
- region/norfair/east/Frog Speedway.json
- region/norfair/east/Green Bubbles Tunnel.json
- region/norfair/east/Lower Norfair Elevator.json
These include all of the rooms with already-merged farm strats, so there shouldn't be any risk of conflict here.
> Upper Norfair East G-mode: part 1

- region/brinstar/blue/Blue Brinstar Energy Tank Room.json
- region/lowernorfair/west/Screw Attack Room.json
Initially I was looking to add the canBombAboveIBJ version of IBJ to Screw Attack Room, but I ended up making a full pass through the room since a lot of the heat frames throughout were outdated/loose. For example, going from the top door to bottom door using Power Bombs logically required 420 heat frames, whereas now it requires 335. 
I added an obstacle ("C") to track if all the bottom bomb blocks have been destroyed, making it impossible to start an IBJ from them. The main scenario I can think of where this matters is if you had to do a Crystal Flash in the bottom of the room (otherwise, since you have Bombs, you would just use Bombs instead of ever Power Bombing the bottom blocks)
The main thing in this room that I skipped over for now is updating the X-ray climb heat frames. That …
> Screw Attack Room canBombAboveIBJ and other refinements

- region/lowernorfair/east/Amphitheatre.json
- tests/asserts/keywords.py
The existing 2->3 strat seemed not right to me: the heat/acid frames seemed very loose, and I couldn't see any benefit from the reset fall speed or wall jump options; it's possible I'm missing something though.
Normally traversing the room right-to-left needs at least 5 tanks with either Varia or Gravity. With a CF in the safe place at the bottom of the room, this can be reduced to 4 tanks with Varia or 3 tanks with Gravity (very tight). If weapons are available to kill the bottom-left Pirate, 3 tanks with Varia also becomes possible.
Videos:
- Crystal Flash in safe spot with Varia (4 tanks): https://videos.maprando.com/video/7404
- Crystal Flash in safe spot with Gravity (3 tanks): https://videos.maprando.com/video/7407
- Kill Pirates and CF with Varia (3 tanks, Charge+Plasma): …
> Amphitheatre CF strats and a few other refinements

- helpers.json
- region/lowernorfair/east/Mickey Mouse Room.json
- region/norfair/east/Single Chamber.json
- region/norfair/east/Speed Booster Hall.json
- region/norfair/east/Spiky Platforms Tunnel.json
- region/norfair/east/Upper Norfair Farming Room.json
- region/norfair/east/Volcano Room.json
- region/norfair/west/Ice Beam Snake Room.json
This partially addresses #1216.
This also changes the `h_heatedCrystalFlash` helper to use `simpleHeatFrames` since normally you aren't doing anything while waiting for the CF to start. Speed Booster Hall was the main one motivating this change. In theory we could also have `simpleLavaFrames` and `simpleAcidFrames` for the lava/acid CF helpers, but those logical requirements haven't been defined and I'm not sure if it's worth the trouble :shrug: A little extra lenience for lava/acid CF may be fine anyway; for lava/acid there's not really a case like Speed Booster Hall where the movement is very simple.
> More heated Crystal Flash strats

- region/maridia/inner-green/East Pants Room.json
- region/maridia/inner-green/Lonely Crab Room.json
- region/maridia/inner-green/Pants Room.json
- region/maridia/inner-green/Shaktool Room.json
In Pants Room, I put minimal effort into the Menu farm because it will be a very complicated one to model accurately; it is probably only useful if the internal door of Pants Room were locked (which currently not allowed in the randomizer but probably will be in the future) since otherwise the Puyo farm is probably better.
> Rest of Green Maridia farms: Shaktool Room, etc.

- tech.json
Of course, Github makes this simple change difficult to follow, so I'll describe the changes:
- Removed R-mode as a requirement from G-mode (no longer an extension)
- Split the tech description to fill a note and devNote for G-mode, upward setup, downward setup
- Move upward setup and downward setup to be inside the extension of g-mode, it now requires g-mode instead of r-mode, and added a FIXME devNote to them
I have more I want to do, but the changes were starting to look too messy, so I'll finish the rest later.
> Remove R-mode Req from G-mode

- helpers.json
- region/brinstar/blue/Blue Brinstar Energy Tank Room.json
- region/brinstar/blue/Morph Ball Room.json
- region/brinstar/green/Green Brinstar Main Shaft.json
- region/brinstar/pink/Big Pink.json
- region/brinstar/pink/Pink Brinstar Wave Gate Room.json
- region/brinstar/red/Caterpillar Room.json
- region/crateria/central/Landing Site.json
- region/crateria/east/West Ocean.json
- region/crateria/west/Green Pirates Shaft.json
- region/lowernorfair/east/Wasteland.json
- region/maridia/inner-pink/Aqueduct.json
- region/maridia/inner-pink/Halfie Climb Room.json
- region/maridia/inner-yellow/Maridia Elevator Room.json
- region/maridia/outer/Crab Hole.json
- region/maridia/outer/Main Street.json
- region/maridia/outer/Mt. Everest.json
- region/norfair/crocomire/Crocomire's Room.json
- region/norfair/crocomire/Grapple Tutorial Room 3.json
- region/norfair/crocomire/Indiana Jones Room.json
- region/norfair/crocomire/Post Crocomire Farming Room.json
- region/norfair/east/Bubble Mountain.json
- region/norfair/west/Crocomire Speedway.json
- region/wreckedship/main/Wrecked Ship Energy Tank Room.json
- strats.md
- tech.json
Also renamed `canRMode`, `canGModeImmobile`. These now match `canXMode`.
- Pulled out upward/downward setups to no longer require G or R mode. 
- Split a few more long g-mode descriptions to include detail notes
> Rename canEnterGMode to canGMode

- region/brinstar/red/Red Tower.json
Videos by Sam:
- 1->5: https://videos.maprando.com/video/7562
- 2->5: https://videos.maprando.com/video/7563
> Red Tower x-ray climbs

- region/brinstar/green/Early Supers Room.json
This came up in Eddie's latest shuffler.
The right-side entry has the advantage that you don't risk a softlock, and you only have to get under a single shutter instead of two. And it could be logically important in case the left door is locked.
Video by Sam: https://videos.maprando.com/video/7579
> Early Supers right-side G-mode setup from right

- region/maridia/inner-yellow/Maridia Elevator Room.json
I'm thinking probably an Extreme notable for the Dodge Rippers IBJ, with damageless only expected in Insane? It took me a couple hours or so to learn but I can get it kind of quickly now.
Videos:
- Sam's: https://videos.maprando.com/video/7571
- Alternative method: https://videos.maprando.com/video/7605
> Maridia Elevator IBJ and SpaceJump ripper dodge options

- region/norfair/west/Ice Beam Gate Room.json
At higher speeds the frame window for the jump is larger but for me it didn't translate into feeling easier. I'm thinking this would probably be an Insane notable. You have to reset the room between attempts, and there's a possibility of the neighboring room being heated, which would be a particularly bad scenario.
Video by Sam: https://videos.maprando.com/video/7557
> Ice beam crouch gate clip

- helpers.json
- region/maridia/outer/Crab Gate Room.json
- tech.json
This builds on PR #2258 , which should be merged first.
> Main uses of canComplexCarryFlashSuit

- logicalRequirements.md
- region/crateria/central/230 Missile Room.json
- region/crateria/central/Blue Brinstar Elevator Room.json
- region/crateria/central/Bomb Torizo Room.json
- region/crateria/central/Climb Supers Room.json
- region/crateria/central/Climb.json
- region/crateria/central/Crateria Map Room.json
- region/crateria/central/Crateria Power Bomb Room.json
- region/crateria/central/Crateria Save Room.json
- region/crateria/central/Crateria Tube.json
- region/crateria/central/Final Missile Bombway.json
- region/crateria/central/Flyway.json
- region/crateria/central/Landing Site.json
- region/crateria/central/Parlor and Alcatraz.json
- region/crateria/central/Pit Room.json
- region/crateria/central/Pre-Map Flyway.json
- strats.md
- tech.json
I was happy to confirm that the requirements related to flash suit already seem nicely set up in the tech/helpers, so almost all strats can just be marked `"flashSuitChecked": true`. Some possible exceptions that I'm trying to watch out for:
- Strats involving Grapple. These can sometimes need the "h_midAirShootUp" helper. Grapple jump/fling strats I'm just putting `"flashSuitChecked": false` on for now because I think they could use a closer look. The tech `canGrappleJump` currently has a `noFlashSuit` requirement but that should possibly be refined later.
- Strats involving tight mid-air morphs from a stand. Without Hi-Jump, even `canJumpIntoIBJ` can be a bit tricky though I'm assuming not enough to justify adding the Insane-level `canTrickyCarryFlashSuit` as a requirement (PR #2259 …
> Crateria Central check flash suits

- helpers.json
- region/crateria/east/East Ocean.json
- region/maridia/inner-green/West Sand Hall.json
- region/maridia/inner-pink/Botwoon Hallway.json
- region/maridia/inner-pink/Crab Shaft.json
- region/maridia/inner-pink/East Sand Pit.json
The existing helper name `h_underwaterCrouchJumpWithFlashSuit` seems misleading because it suggests a requirement to have a flash suit, when all it means is that you *may* have a flash suit. It is defined as `{"tech": "canCrouchJump"}`, i.e. simply the crouch-jump tech without the `{"noFlashSuit": {}}` requirement that normally comes along with it. This seems to have led to some confusion where we are using redundant blocks like this:
```
{"or": [
"canCrouchJump",
"h_underwaterCrouchJumpWithFlashSuit"
]},
```
which expands to
```
{"or": [
"canCrouchJump",
{"tech": "canCrouchJump"}
]},
```
where it becomes clear that the first case of the `or` is unnecessary.
This PR proposes that we rename the helper to `h_underwaterCrouchJump` and replace blocks like this with simple uses of the helper. …
> Simplify underwater crouch jump helpers

- helpers.json
- region/brinstar/blue/Blue Brinstar Boulder Room.json
- region/maridia/outer/Crab Hole.json
We can use these to mark individual cases that are more difficult to carry a flash suit than reflected by their tech requirements alone.
> A couple more helpers for flash suits

- region/tourian/main/Big Boy Room.json
- region/tourian/main/Dust Torizo Room.json
- region/tourian/main/Lower Tourian Save Room.json
- region/tourian/main/Metroid Room 1.json
- region/tourian/main/Metroid Room 2.json
- region/tourian/main/Metroid Room 3.json
- region/tourian/main/Metroid Room 4.json
- region/tourian/main/Mother Brain Room.json
- region/tourian/main/Rinka Shaft.json
- region/tourian/main/Seaweed Room.json
- region/tourian/main/Tourian Escape Room 1.json
- region/tourian/main/Tourian Escape Room 2.json
- region/tourian/main/Tourian Escape Room 3.json
- region/tourian/main/Tourian Escape Room 4.json
- region/tourian/main/Tourian Eye Door Room.json
- region/tourian/main/Tourian First Room.json
- region/tourian/main/Tourian Hopper Room.json
- region/tourian/main/Tourian Recharge Room.json
- region/tourian/main/Upper Tourian Save Room.json
- strats.md
Rooms with an interesting flash suit interaction :
- Big Boy Room: flash suit makes it hard to break the top seaweed while baby skipping counter-clockwise. Doing it clockwise should be an option. Using a Power Bomb can be another alternative (saw this on your stream yesterday @osse101 ). I'm not good enough at baby skipping to estimate how these variations would impact difficulty, so I just put `h_trickyToCarryFlashSuit` to be safe. It can be adjusted if there is a case that would be ok with just `complex`.
- Mother Brain Room: Destroying the Zebs or doing Ice Zeb Skip are both a bit awkward, seemed like `complex` level.
- Tourian Escape Room 4: Freezing the Pirates while climbing the left side is tricky. Killing them also seemed non-trivial (complex level).
- Tourian Hopper Room: going …
> Tourian check flash suits

- region/norfair/crocomire/Cosine Room.json
- region/norfair/crocomire/Crocomire's Room.json
- region/norfair/crocomire/Grapple Beam Room.json
- region/norfair/crocomire/Grapple Tutorial Room 1.json
- region/norfair/crocomire/Grapple Tutorial Room 2.json
- region/norfair/crocomire/Grapple Tutorial Room 3.json
- region/norfair/crocomire/Indiana Jones Room.json
- region/norfair/crocomire/Post Crocomire Farming Room.json
- region/norfair/crocomire/Post Crocomire Power Bomb Room.json
- region/norfair/crocomire/Post Crocomire Save Room.json
- region/norfair/crocomire/Post Crocomire Shaft.json
- Post Croc Farm Room had the most interesting changes: using the Ripper to grapple across from top-left to top-right is always possible with a flash suit, but using it to get up from the bottom of the room requires "h_midAirShootUp". With a flash suit, damage boosting off the Ripper becomes logically significant, because you may not be able to use the Gamets. Boosting off a Gamet to the top-right also becomes a useful option.
- Heat frames in Post Croc Power Bomb Room seemed way off, so I updated them.
- Added a grapple jump strat in Grapple Beam Room which is only useful for carrying a flash suit.
- Added a "Tricky Dash Jump with Hi-Jump" strat in Indiana Jones Room to directly reach the item from the bottom-right with PB blocks cleared. It mostly only makes a difference logically if …
> Crocomire Norfair check flash suits

- region/brinstar/red/Red Brinstar Fireflea Room.json
- region/crateria/east/East Ocean.json
- region/maridia/inner-green/East Pants Room.json
- region/maridia/inner-green/East Sand Hall.json
- region/maridia/inner-green/Oasis.json
- region/maridia/inner-green/Pants Room.json
- region/maridia/inner-green/West Sand Hall.json
- region/maridia/inner-pink/Aqueduct.json
- region/maridia/inner-pink/Colosseum.json
- region/maridia/inner-pink/Crab Shaft.json
- region/maridia/inner-pink/East Cactus Alley.json
- region/maridia/inner-pink/East Sand Pit.json
- region/maridia/inner-pink/Halfie Climb Room.json
- region/maridia/inner-pink/West Sand Pit.json
- region/maridia/inner-yellow/Watering Hole.json
- region/maridia/outer/Fish Tank.json
- region/maridia/outer/Main Street.json
- region/maridia/outer/Mama Turtle Room.json
- region/maridia/outer/Maridia Tube.json
- region/maridia/outer/Mt. Everest.json
- region/norfair/crocomire/Grapple Tutorial Room 3.json
- region/norfair/east/Double Chamber.json
Removed flash suit checked from a couple max height spring ball into double reserve trigger. Not sure if those were tested properly? If so, I can add them back
> Refine flash suits and max height spring ball

- region/norfair/west/Crocomire Speedway.json
- In the top part of the shaft, some of the "Carry Shinecharge" heat & shinecharge frames were tighter than the Base ones. They are adjusted now to be consistent.
- The Base strat for traversing past the Cacatacs bottom-to-top was very loose. It is tightened here, and strats are also added for farming the Cacs along the way.
- The Base strat for running along the speedway left-to-right seemed like a good candidate for `simpleHeatFrames`. It could be added for right-to-left strats as well.
- I added strats that use the speedway to go from the left door directly to either of the bottom-right doors, because the heat frames can be reduced quite a bit compared to assuming you make a stop at the floating platform junction. With Wave it becomes fairly reasonable to get to either of these doors …
> Croc Speedway: tighten some heat frames

- region/brinstar/kraid/Baby Kraid Room.json
- region/brinstar/kraid/Kraid Eye Door Room.json
- region/brinstar/kraid/Kraid Recharge Station.json
- region/brinstar/kraid/Kraid Room.json
- region/brinstar/kraid/Kraid Save Room.json
- region/brinstar/kraid/Varia Suit Room.json
- region/brinstar/kraid/Warehouse Energy Tank Room.json
- region/brinstar/kraid/Warehouse Entrance.json
- region/brinstar/kraid/Warehouse Kihunter Room.json
- region/brinstar/kraid/Warehouse Zeela Room.json
Coming from the bottom of kihunter room looks like it might need some work. I just marked it as `checked = false` for now.
> Kraid Brinstar check flash suits 

- region/maridia/inner-green/Pants Room.json
- region/maridia/inner-green/Shaktool Room.json
- region/maridia/inner-green/Spring Ball Room.json
- region/maridia/inner-green/West Sand Hall.json
These remaining rooms seemed fairly straightforward. West Sand Hall was the only one with significant changes:
- Tightened shinespark excessFrames in the suitless comeInWithSpark strats.
- Added strats that use cross-room momentum to reach the center of the room from the left. A flash suit can then be used to reach the right door with much less energy than sparking across the whole room.
- Also added a cross-room space jump strat to reach the first pillar (node 5) from the left, which can be useful even without a flash suit.
For the Insane grapple jump strats in Pants Room, I didn't try to figure out how a flash suit affects the difficulty, because I couldn't manage to do the strat even when not carrying a flash suit :shrug: So I left that as `flashSuitChecked` false.
> Green Maridia check flash suits pt. 3 (West Sand Hall, etc.)

- region/norfair/east/Lava Grapple Tunnel.json
Looked into this after noticing a video by Sam that showed you could traverse Lava Grapple Tunnel tankless with Grapple. It took a while to get the hang of how to optimize the swings, but it seems not too bad.
With the new amount of heat frames, crossing tankless would be in Expert logic. I think this may be ok, but if it's not then we could add some extra heat frames in an `or` with `canInsaneJump` or something. 
Videos for this are on the video site.
> Tighten Lava Grapple Tunnel grapple heat frames

- region/brinstar/red/Below Spazer.json
This is only a half-tile more, but it can be significant because it means you can get tricky dash jump speed.
> Increase leaveSpaceJumping runway in Below Spazer top

- region/brinstar/pink/Spore Spawn Farming Room.json
- tech.json
add canSlopeSpark to logic + 2 examples in spore spawn farming room
> add CanSlopeSpark to logic
