vg-json-data/sm-json-data

connection/crateria/central.json
connection/crateria/east.json
connection/crateria/west.json
connection/norfair/crocomire.json
connection/norfair/east.json
connection/norfair/west.json
connection/tourian/main.json
connection/wreckedship/main.json
region/cleanup.json
region/crateria/central.json
region/crateria/east.json
region/crateria/west.json
region/norfair/crocomire.json
region/norfair/east.json
region/norfair/west.json
region/tourian/main.json
region/wreckedship/main.json

Since yesterdays pull request wasn't merged I'm not sure how to pull todays new files without the earlier ones as well. Hope it's alright.

Yesterdays pulls + Norfair and more cleanup

---

region/norfair/crocomire.json
region/norfair/east.json
region/norfair/west.json

All Norfair reqs and nodes

---

connection/crateria/central.json
connection/crateria/east.json
region/brinstar/pink.json
region/crateria/central.json
region/crateria/east.json
region/crateria/west.json
region/lowernorfair/east.json
region/lowernorfair/west.json
region/norfair/crocomire.json
region/norfair/west.json

Missing connection in crateria east, lowernorfair stuff etc. etc.

LowerNorfair and various fixes

---

region/crateria/west.json
region/lowernorfair/east.json

Minor link fixes

---

region/brinstar/blue.json
region/brinstar/green.json
region/brinstar/kraid.json
region/brinstar/pink.json
region/brinstar/red.json
region/ceres/main.json
region/cleanup.json
region/crateria/central.json
region/crateria/east.json
region/crateria/west.json
region/lowernorfair/east.json
region/lowernorfair/west.json
region/maridia/inner.json
region/maridia/outer.json
region/norfair/crocomire.json
region/norfair/east.json
region/norfair/west.json
region/tourian/main.json
region/wreckedship/main.json

Croc and Crateria with LeaveSparked removed. Also added Phantoon requirement needed to activate wrecked ship statue.

New Spark structure and Wrecked Ship statue req

---

region/maridia/inner.json
region/maridia/outer.json

Got the whitespacing done etc.

Maridia runways fixed with canSwim

---

region/brinstar/pink.json
region/crateria/central.json
region/maridia/inner.json
region/maridia/outer.json
region/norfair/crocomire.json
region/norfair/east.json
region/norfair/west.json
region/wreckedship/main.json

canShineCharge replacing Shinespark and other forms of QuickChargery

Runway split

---

readme.md

See https://github.com/fdtaillefer/sm-json-data/tree/master_readme to look at how the readme file comes out on the project page

Add a readme file

---

helpers.json
region/brinstar/blue.json
region/brinstar/green.json
region/brinstar/kraid.json
region/brinstar/pink.json
region/brinstar/red.json
region/ceres/main.json
region/cleanup.json
region/crateria/central.json
region/crateria/east.json
region/crateria/west.json
region/lowernorfair/east.json
region/lowernorfair/west.json
region/maridia/inner.json
region/maridia/outer.json
region/norfair/crocomire.json
region/norfair/east.json
region/norfair/west.json
region/tourian/main.json
region/wreckedship/main.json
schema/m3-region.schema.json
tech.json

This is meant as additional adjustments for after https://github.com/miketrethewey/sm-json-data/pull/56 has been merged into master. Please do not consider merging until then,

Runway adjustments

---

region/norfair/crocomire.json

Norfair Crocomire heatdata

---

region/brinstar/red.json
region/lowernorfair/west.json

A minor cost change for Red Tower found its way in but it's something that should be in the end product anyway.

Lower Norfair West heatdata

---

region/norfair/west.json

Norfair West heatdata

---

region/lowernorfair/east.json
tech.json

Lower Norfair: East heatdata

---

region/norfair/crocomire.json
tech.json

Issue #105: Missing logic in Post Croc Jump Room: Breaking the speed blocks from the left

---

region/brinstar/green.json
region/brinstar/red.json
region/lowernorfair/east.json
region/lowernorfair/west.json
region/norfair/east.json
region/wreckedship/main.json

Adds several new runways and links that needs a "resetRoomAtNode" to work properly.

Reset rework. Closes #121

---

connection/crateria/intra.json
region/brinstar/blue.json
region/brinstar/pink.json
region/maridia/outer.json
region/tourian/main.json

Also fixed various naming errors

Openings without doors become doorways. Closes #151

---

region/crateria/central.json
region/lowernorfair/east.json
region/maridia/inner-pink.json
region/maridia/outer.json
region/norfair/crocomire.json
region/norfair/east.json
region/tourian/main.json
region/wreckedship/main.json

There where some more shinesparkFrames to add, yay!

canLeaveCharged (when 0) shinesparkFrames

---

region/brinstar/red.json
region/lowernorfair/east.json
region/maridia/outer.json
region/norfair/east.json
region/norfair/west.json

Adds "type" into the enemyDamage cost object to play with the changed enemy file. Progress in #103

enemyDamage type

---

enemies/enemies-readme.md
region/norfair/east.json
region/region-readme.md

Plus a random nodeItem -> node fix

Update documentation for utility and the change in enemy attacks

---

helpers.json
region/brinstar/blue.json
region/brinstar/green.json
region/brinstar/pink.json
region/brinstar/red.json
region/crateria/central.json
region/maridia/inner-pink.json
region/maridia/inner-yellow.json
region/norfair/crocomire.json
region/norfair/east.json
region/norfair/west.json
region/wreckedship/main.json
tech.json

Remaining canDash into SpeedBooster

---

region/brinstar/blue.json
region/brinstar/green.json
region/brinstar/kraid.json
region/crateria/east.json
region/maridia/inner-green.json
region/maridia/inner-pink.json
region/maridia/inner-yellow.json
region/maridia/outer.json

A bunch of extra ones I found along with a couple errors as a bonus.

Treasure Hunt: canComeInCharged & canLeaveChargeds

---

region/brinstar/blue.json

Strats are a springwall, and a tricky walljump that makes the room doable naked.

Add two more strats to Boulder Room. Resolves #208.

---

enemies/bosses/main.json
enemies/main.json
region/brinstar/red.json
region/lowernorfair/east.json
region/lowernorfair/west.json
region/norfair/east.json
region/norfair/west.json
region/tourian/main.json
region/wreckedship/main.json
schema/m3-enemies.schema.json
schema/m3-region.schema.json

dropRequires - What extra feat is required to obtain the drop of an enemy such as dipping into lava or taking a spikehit. Many enemies are placed where Samus can't walk but their drops can be reached anyway.
amountOfDrops - What amount of drops an enemy leaves behind

Drops extended

---

enemies/bosses/main.json
region/lowernorfair/east.json
region/tourian/main.json
weapons/main.json

Attempt at boss health handling with expectedDamageFrames and weapon cooldownFrames (rate of fire)

expectedDamageFrames

---

helpers.json
region/norfair/west.json

You can lure the Geruta to the left and freeze it to get up the ledge

FrozenEnemy strats in Crocomire Escape

---

region/crateria/east.json
region/maridia/inner-yellow.json
region/region-readme.md
schema/m3-region.schema.json
tech.json

And apply it in two specific instances (Bowling Alley Skip, and Butterfly Botwoon Skip).

Add the possibility of bypassing a lock without deactivating it

---

enemies/bosses/scenarios.json

(You can only get one off per round rather than 3).

Create a different Phantoon scenario for high-damage Charge Shots

---

logicalRequirements.md
region/lowernorfair/east.json
region/norfair/east.json
region/region-readme.md
schema/m3-region.schema.json

+ other miscellaneous schema and documentation improvements.

Alter the schema to prepare for changing runway requirements into strats

---

logicalRequirements.md
region/ceres/main.json
region/tourian/main.json
schema/m3-region.schema.json
tech.json

Add a logical element for dropping energy to a fixed amount + add baby skip strats

---

logicalRequirements.md
region/tourian/main.json
schema/m3-region.schema.json

Add an Ammo Drain logical element

---

region/brinstar/blue.json
region/region-readme.md
schema/m3-region.schema.json

Alter the schema to refine how the ability to view an item node from another node is described

---

region/brinstar/green.json
region/brinstar/pink.json
schema/m3-bossScenarios.schema.json
schema/m3-connection.schema.json
schema/m3-enemies.schema.json
schema/m3-region.schema.json
schema/m3-weapons.schema.json

And add failures for quick crumble escape strats.
Fixes #285.

Add a definition for strat failure consequences

---

connection/norfair/east.json
connection/norfair/west.json
region/crateria/central.json
region/crateria/west.json
region/lowernorfair/east.json
region/maridia/inner-pink.json

Add missing junction nodes in some rooms, add missing links in Pit Room, fix some connections.

Miscellaneous fixes

---

schema/m3-region.schema.json
schema/m3-requirements.schema.json
schema/m3-weapons.schema.json

Makes it possible to re-use it in the weapons file schema.

Move the json-schema definition of logical requirements into its own file

---

enemies/bosses/main.json
enemies/enemies-readme.md
enemies/main.json
schema/m3-enemies.schema.json

And use camelCase for its property names.

Standardise the definition of enemy drops into a single definition

---

enemies/bosses/main.json
enemies/enemies-readme.md
enemies/main.json
schema/m3-enemies.schema.json
schema/m3-weapons.schema.json
weapons/main.json
weapons/weapons-readme.md

To have consistent property names. Also add a category for charged beam attacks.

Change the format of enemy damage multipliers

---

helpers.json
items.json
schema/m3-helpers.schema.json
schema/m3-items.schema.json
schema/m3-tech.schema.json
tech.json

Also includes changes to the data in items.json.

Add schemas for helpers.json, tech.json, and items.json

---

enemies/main.json
region/lowernorfair/west.json

Made them consistent with the name of the corresponding item and weapon.

Fix some references to Screw Attack

---

connection/inter.json
connection/maridia/inner.json
region/brinstar/blue.json
region/brinstar/kraid.json
region/crateria/east.json
region/crateria/west.json
region/lowernorfair/east.json
region/maridia/inner-green.json
region/maridia/inner-pink.json
region/maridia/inner-yellow.json
region/maridia/outer.json
region/norfair/east.json
region/norfair/west.json
region/wreckedship/main.json
tech.json

Connections, misspelled requirements, missing canHeatRun tech.

Miscellaneous integrity fixes

---

enemies/main.json
region/lowernorfair/east.json
region/norfair/east.json

Now in-line with https://wiki.supermetroid.run/Damage_Sources

Change alternate enemy attack names

---

logicalRequirements.md
region/brinstar/red.json
region/crateria/central.json
region/crateria/east.json
region/maridia/inner-green.json
region/maridia/inner-pink.json
region/maridia/outer.json
region/norfair/crocomire.json
region/norfair/east.json
region/norfair/west.json
region/tourian/main.json
schema/m3-requirements.schema.json

This is to indicate the expected path through the room when `fromNode` is not the node we are at

Add an optional `inRoomPath` property to `adjacentRunway` and `canComeInCharged`

---

region/brinstar/kraid.json
region/norfair/west.json

These discrepancies were found by data mining the rom.

Fix Zeela & Crocomire Save Room addresses.

---

region/brinstar/pink.json

Adjust the strat name to setup the X-Ray climb in Big Pink

---

region/brinstar/pink.json
tech.json

So it doesn't require the actual execution of a blue gate glitch tech.

Fix Hopper Room Reverse GGG 

---

region/brinstar/blue.json
region/brinstar/green.json
region/brinstar/kraid.json
region/brinstar/pink.json
region/brinstar/red.json
region/ceres/main.json
region/crateria/central.json
region/crateria/east.json
region/crateria/west.json
region/lowernorfair/east.json
region/lowernorfair/west.json
region/maridia/inner-green.json
region/maridia/inner-pink.json
region/maridia/inner-yellow.json
region/maridia/outer.json
region/norfair/crocomire.json
region/norfair/east.json
region/norfair/west.json
region/region-readme.md
region/tourian/main.json
region/wreckedship/main.json
schema/m3-region.schema.json

To avoid ambiguity with the upcoming groupName property.

Change room enemy's name property to enemyName

---

region/tourian/main.json
tech.json

Replace the morph zeb skip tech/strat with remorph zeb skip.

---

region/maridia/outer.json
tech.json

Add a strat for Fish Tank SpringBall escape

---

region/brinstar/blue.json
schema/m3-requirements.schema.json

Adjust strats in boulder room

---

region/brinstar/red.json
schema/m3-region.schema.json

Add strats and canLeaveChargeds for the 13-tile runway in the middle of Red Brin Firefleas

---

region/wreckedship/main.json

This link is not quite free as it requires a down grab if you have no items.

Add canDownGrab strat to the Electric Death Room

---

region/norfair/west.json

Fix Ice Beam Snake Room
Node 4 to 2:
- This requires wall jump, hi jump, or space jump. IBJ is not worth using unless you're heatproof, in which case you can choose path 3->1->5->2 instead of 3->4->2.
- There is no reason to tank the Sovas if you are heat proof. You can wait for them to come out, shoot them, then go in.
- Similar to the Power Bomb strat, Wave can be used to quickly kill the Sovas before they come out. 
Node 5 to 2:
- There is no reason to tank the Sovas if you are heat proof. You can wait for them to come out, shoot them, then go in.
- Note that no Wave strat was added - The firing angle doesn't seem to work unless you wait a bit, and at that point it doesn't seem to save you any energy.

Fix Ice Beam Snake Room

---

region/norfair/west.json

Add wall jump and ice beam strats to the Hi Jump Energy Tank Room

Add canWalljump to Upper Norfair West

---

region/norfair/east.json

- Upper Norfair Farming Room
- Bubble Mountain (After getting the item)
- Bat Cave
- Single Chamber (Many spots)

Add canWalljump to Upper Norfair East

---

schema/m3-tech.schema.json
tech.json

Also changed canPreciseWalljump to no longer require canTrickyJump, and canSnailClip now requires canUseEnemies.

Modify tech.json to contain a hierarchy of extension techs

---

region/brinstar/kraid.json
region/crateria/east.json
region/lowernorfair/west.json
region/maridia/inner-pink.json
region/wreckedship/main.json
tech.json

Also change one tech's parent.

Rename more techs

---

region/brinstar/kraid.json
region/maridia/inner-yellow.json

- Added strat in the plasma room to allow samus to shinespark out with a slightly larger runway.
- Add ammo reqs for phase 1 of Kraid.

Fix to Kraid and Plasma Room

---

region/brinstar/green.json

Add dodge, kill, and evade strats in the Green Brinstar Beetom Room and the Etecoon Energy Tank Room.

Add Beetom strats in the Beetom Room, Etecoon E Tank Room

---

logicalRequirements.md
region/wreckedship/main.json
schema/m3-requirements.schema.json
tech.json

-Add NOT
-covern ice partial clip
-spongebath / spiky death / electric death without power is free
-bull boost

Unpowered Wrecked Ship

---

region/norfair/crocomire.json
tech.json

- Clean up various strats and add wall jumps throughout.
- Add canMellaIceClip to PCJR

Add to PCJR and Grapple Tutorial 2, 3

---

region/tourian/main.json
tech.json

Add canWalljump throughout Tourian
Add canConsecutiveWalljump for reverse Tourian Escape Room 4
- Made canFastWalljumpClimb an extension of this tech

Add canWalljump in Tourian and canConsecutiveWalljump 

---

region/crateria/east.json
region/lowernorfair/east.json
region/norfair/east.json

- West Ocean Bug Boost
- Bubble Mountain 1->7 and 7->1
- Norfair Fireflea Bug Boost

Add Damage to Damage Boosts

---

region/maridia/inner-pink.json

Separate out strats to get to the top right that were all considered "Base"

Separate Room Traversal strats in Draygon's Room

---

region/maridia/outer.json

- Convert IBJ strat to use canJumpIntoIBJ and add a note. It is no longer notable
- Add strat "Mama Turtle Wall Jump Bomb Boost", which relies on #496 and fixes #431
- Add strat "Tricky Speed Hi Jump", which fixes #407

Add Strats to Mama Turtle's Room

---

region/maridia/outer.json
tech.json

Spinjumping under the slope is enough to clip but to be safe one should tunnelcrawl through

Morphless Tube Clip

---

region/brinstar/pink.json

An alternate strat without wall jump requirements

Add Waterway Come In Charged

---

region/norfair/west.json

- Croc Escape Jump IBJ
- Croc Escape Lava IBJ

Add Croc Escape IBJ Strats

---

region/brinstar/green.json
tech.json

There are two new strats: One with a damage boost and one with moon walk.
Added two new tech:
- canCrouchGateClip
- canMoonwalk
This should fix #302

Add canCrouchGateClip Strats to Early Supers Room

---

region/norfair/east.json

Add two strats in double chamber from 3 -> 4:
- Hijumpless Double Chamber Spike Speedjump
- Double Chamber Hijumpless Walljump
This should resolve #360

Add Strats to Double Chamber

---

region/norfair/east.json

This is to get up onto the moving platforms without a wall jump

Add Double Chamber Speed+Hijump

---

region/brinstar/blue.json
region/norfair/crocomire.json

- Blue Brinstar Ceiling E-Tank (Also requires canDoubleBombJump)
- Post Crocomire Farming Room

Add Two canJumpIntoIBJ Strats

---

region/norfair/east.json
tech.json

Added morphless hjbless
Adjusted numbers.  
Added canBounceBall.  There should be more uses for it when cross room physics changes are in.

Lava Dive Strats Update

---

region/maridia/inner-pink.json

Springball Spike Boost

---

region/brinstar/pink.json

Breaking the top left bomb block to the save room, from the right, with a speedball.  In room takes a stutter 3. #547

Big Pink SpeedBall Save

---

region/maridia/inner-yellow.json
region/norfair/east.json

- Lava Dive
- Maridia Elevator

Add canStaggeredWalljump

---

region/norfair/east.json

Single Chamber and Upper Norfair Farming Room

Add IBJ and Ice Beam Strats in Norfair East

---

region/brinstar/blue.json
region/brinstar/pink.json
region/lowernorfair/east.json
region/tourian/main.json
tech.json

- Pink Hopper Room
- Morph Ball Room Hoppers
- Blue Hopper Room
- Mickey Mouse Room

Add canPrepareForNextRoom to Enemy Hit on Entry

---

region/norfair/east.json
tech.json

Both for left door.
-Freeze a Sova on the right wall to jump up.
-Use a Sova to bounce into the Morph Tunnel
#514

Precathedral no walljump strats

---

region/brinstar/blue.json
region/norfair/east.json
region/wreckedship/main.json

- Spiky Death Room
- Wrecked Ship Energy Tank Room
- Red Pirate Shaft
- Morph Ball Room

Add canCarefulJump in various places

---

region/brinstar/kraid.json

100 energy without canTrickyJump, 70 with.

Add tricky strat to Kraid's Beetoms

---

region/brinstar/green.json

It may not be possible to resetRoom using the left door

Update early supers canLeaveCharged

---

region/brinstar/green.json
tech.json

-eticoon beetom trickyjump both directions
-grapplejump requirements which carry into draygon grapplejump requirements.

Mostly tech notes

---

region/maridia/inner-pink.json

- Halfie Climb Room
- Precious Room
- West Cactus Alley

Add Cross Room Jumps in Pink Maridia

---

region/maridia/inner-pink.json
region/maridia/inner-yellow.json
region/maridia/outer.json
tech.json

-Oum r->l with shinespark
-Oum l->r with walljumps
-fish tank fish freeze mid->left
-canSunkenTileWideWallClimb tech

Various Maridia Strats

---

region/norfair/east.json

Following up on #310 
Springballs and IBJs

The worst Lava Dive strats

---

region/lowernorfair/east.json

https://clips.twitch.tv/ClearSavageWolfDoritosChip-il6VkH1_G9BA_P_0

HiJumpless Hotarubi Special

---

region/maridia/inner-yellow.json

Doesn't address the code dupe issue but I noticed  `Pirates Alive` strats include notes on how to manipulate the pirates.

Update Plasma Room

---

region/brinstar/blue.json
region/brinstar/green.json
region/brinstar/kraid.json
region/brinstar/pink.json
region/brinstar/red.json

- Also modernize some of the code to use correct helpers and obstaclesCleared

Remove some notable strats in Brinstar

---

region/tourian/main.json

- Redesign some Metroid Avoid PB Kill strats

Remove some notable strats in Tourian

---

region/crateria/central.json
tech.json

Central Crateria strat updates

---

region/brinstar/blue.json
region/brinstar/green.json
region/brinstar/pink.json
region/brinstar/red.json
region/crateria/central.json
region/crateria/east.json
region/maridia/inner-pink.json
region/maridia/inner-yellow.json
region/norfair/crocomire.json
region/norfair/east.json
region/wreckedship/main.json

- Naming is designed to be clear what the strat is with only the strat name - the room should be implied

Rename and remove some notables

---

region/brinstar/green.json
region/brinstar/pink.json
region/brinstar/red.json
region/crateria/central.json
region/crateria/east.json
region/maridia/inner-pink.json
region/maridia/outer.json
region/tourian/main.json
region/wreckedship/main.json
tech.json

- Combine `canMorphlessTunnelCrawl` and `canTunnelCrawl` to `canTunnelCrawl`
- Rename `canSuperReachAround` to `canOffScreenSuperShot`
- Rename `canSpringBallJump` to `canSpringBallBounce` and fix misaligned mid air references
- Fix typos

Tech changes

---

helpers.json
region/brinstar/pink.json
region/brinstar/red.json
region/lowernorfair/east.json
region/maridia/inner-green.json
region/maridia/inner-pink.json
region/maridia/inner-yellow.json
region/norfair/west.json
tech.json

and a helper for very short jumps

canRJump and canPartialFloorClip

---

region/norfair/east.json
region/region-readme.md
schema/m3-region.schema.json
strats.md

Add Bubble Mountain Damage Boost example

Add reusableRoomwideNotable and example

---

region/maridia/inner-pink.json

The two strats that used this were fairly different in difficulty

Remove reusable Drayon grapple kill

---

region/brinstar/blue.json
region/brinstar/green.json
region/brinstar/kraid.json

`canShinechargeMovement` was put on anything with a jump.
Falling was considered free except when leaving early supers right door from above.

Shinecharge Brinstar 1

---

region/brinstar/red.json
region/crateria/central.json
region/maridia/inner-pink.json
region/norfair/east.json
region/wreckedship/main.json

Add strats that simply run in the spikes, like a player might do if they didn't know how to utilize the i-frames.

Bypass canIframeSpikeJump

---

region/brinstar/pink.json

HJBless Etankless Dachora escape

---

region/tourian/main.json

Like in this clip: https://clips.twitch.tv/SarcasticWildPepperoniMoreCowbell-FNJCTQxYvX9TDOw_

Blue speed jump through Blue Hopper Room

---

region/maridia/outer.json

Fish Tank Fixes. Looking for specific feedback on:
- Can you do a spring ball midair from 5 to 4 without ice?
- How do you get from 6 to 7 with just a tricky jump?

Fish Tank Fixes

---

region/brinstar/blue.json
region/brinstar/green.json
region/brinstar/kraid.json
region/crateria/east.json
region/crateria/west.json
region/maridia/inner-pink.json
region/norfair/crocomire.json
tech.json

Interesting that microwave isn't used in logic anywhere.  So that can be updated separately.

canXrayTurnaround and canXrayWaitForIFrames

---

region/maridia/outer.json
schema/m3-requirements.schema.json

- Fix strats by modeling Mama Turtle in sleeping and awake states.
- Add `canRiskPermanentLossOfAccess` to a missing `not` in Maridia

Fix Mama Turtle Room

---

region/norfair/east.json

Quick lookthrough for multiples of 400.
-shinespark updates
-few strat updates

UpperNorfair East frame count update

---

region/brinstar/blue.json
region/brinstar/green.json
region/brinstar/kraid.json
region/brinstar/pink.json
region/brinstar/red.json
region/crateria/central.json
region/crateria/east.json
region/lowernorfair/east.json
region/lowernorfair/west.json
region/maridia/inner-green.json
region/maridia/inner-pink.json
region/maridia/inner-yellow.json
region/maridia/outer.json
region/norfair/crocomire.json
region/norfair/east.json
region/norfair/west.json
region/tourian/main.json

A quick first pass at adding and improving notes on notable strats. 
- Added a note to most where they were missing,
- Fixed some to make them more clear or more correct. 
These quick notes can help the player have an idea what the strat means from a higher level. 
This should all be double checked and improved eventually.

Partial fix to adding notes to some notable strats

---

tech.json

There are already enough of these to deserve their own category, and we're about to add more for R-mode and G-mode.

Move X-Ray tech to their own tech category

---

region/brinstar/green.json
tech.json

I don't know exactly how this is done (haven't practiced speed keeps) but I remember seeing it on a stream before. @osse101 would you mind checking?

Brinstar Reserve canSpeedKeep

---

region/norfair/crocomire.json

Noticed this when @osse101 did it in his no-walljump challenge seed.

Add grapple tutorial 2 strat with hijump+speedbooster

---

region/maridia/inner-pink.json

imyt did this in the race last night: https://clips.twitch.tv/HumbleJoyousSwordTebowing-iWdruU5JdsnF1Q3p

add HiJump + SpaceJump strat in East Cac Alley

---

region/brinstar/pink.json

and update speedball into save room

Big Pink walljumpless strats

---

region/lowernorfair/east.json

Adding more strats for Main Hall and Fast Pillars Setup Room

Lower norfair early room strats

---

region/norfair/west.json

Bottom door to IceBeam door strats.
For #694

Update part of IceBeamSnakeRoom

---

region/maridia/outer.json

Add some speed dash jumps to maridia

---

helpers.json
region/maridia/inner-pink.json
region/maridia/outer.json
tech.json

Added canSpringBallBombJump.  That's what I've been calling the tech, but it could also be canBombBoostSpringBallJump.

Cactus Alley Strats

---

region/tourian/main.json

Whoops. I forgot to apply gravity halving the damage taken.

Metroid Room 1 - gravity acid frames

---

region/norfair/east.json

Rising tide

---

region/norfair/west.json

West Norfair - Gravity Lava Frames

---

region/norfair/east.json

Partially addresses #663 
- Lava Dive
- Volcano Room
- Spiky Platforms Tunnel

Lower Upper East Norfair - Gravity Lava Frames

---

enemies/bosses/main.json
enemies/bosses/scenarios.json
region/maridia/inner-pink.json
tech.json
weapons/main.json

Resolving #292 
-A BackSide Botwoon scenario
-angle shot through wall microwave
-angle shot beam fight (Plasma or Ice+spazer)
-Plasma SBA
-Supers only

Reverse Botwoon Scenario

---

region/lowernorfair/east.json

Bomb only can be added separately since I can't do it.

LN Pillars Room

---

region/wreckedship/main.json

This does not include any vertical doors. They will need to be done later

WS G-Mode Setup

---

region/tourian/main.json

Eventually we can add some sort of tech or strats to killing and dodging the tedious space pirates in rooms 3 and 4.

Update Tourian Escape Room 4

---

region/brinstar/red.json

Video by Bobbob: https://vimeo.com/810399620
Oatsngoats did this on stream last night and got it on his first attempt.

Add notable strat in Red Tower for R-mode frozen beetom x-ray climb

---

region/brinstar/blue.json
region/brinstar/green.json
region/brinstar/kraid.json
region/crateria/central.json
region/crateria/east.json
region/crateria/west.json
region/maridia/inner-pink.json
tech.json

And some indentation in Crateria Climb

Consistent Casing on "XRay"

---

region/maridia/outer.json

Fewer tech requirements but same difficulty tier.

lower main street jump up to fish

---

region/maridia/outer.json

Main Street Frozen Fish with Spring Ball

---

region/crateria/east.json

I couldnt quite get it without the sationary/reset fall speed, but it definitely looks possible (and may be how this example did it?)
https://www.youtube.com/watch?v=srfN7LTfKfY

East Ocean Strat

---

region/maridia/inner-green.json

https://www.youtube.com/watch?v=LUa-F4WHQR8

Add Suitless, Bootless Spring Ball Escape

---

region/norfair/crocomire.json

Oats just did this on stream:
https://clips.twitch.tv/ReliableSassyClipsdadYouDontSay-PxcY5droM1zZemD5
I tried it out and it seems reasonable enough to not be notable. The stationary spinjump thing that Oats did isn't needed.

Add left side PCJR Springwall strat

---

region/crateria/east.json

Clip: https://youtu.be/Bja36hFupMA
I tried this out and it doesn't seem bad, so I'm thinking we don't make it notable.

West ocean ice clip

---

region/maridia/inner-pink.json

Harder than the listed requirements would place it.

Colosseum with Ice as notable

---

region/lowernorfair/west.json
tech.json

This may be me going through strats that don't feel race friendly and making them notable.
Jumping over the gap is harder than crumble jumps.
The horizontal bomb jump feels notable since I think you need an idea of when the explosion happens for holding forward, the risk.

Gt Crumble Bridge

---

region/maridia/inner-yellow.json

I wanted to put a harder tech for landing next to the Choot above 4.
Breaking up the 3->5 strats looks a little harder to trace strat coverage, but I needed to separate the notes.

Update Plasma Spark Room

---

helpers.json
region/lowernorfair/west.json

I didn't understand the Flatley fixme.  But its often too slow to setup in acid unless you have to.
Separated out the chozo statue requiring SpaceJump.

Acid Chozo Room

---

tech.json

This is just a partial rework to standardize and clarify some of the tech descriptions. I'm sure a lot more work could be done on it eventually.

Partial tech description rework

---

region/maridia/outer.json

This should include all in-room strats for using gmode in Outer Maridia for rooms that have door caps on all doors.
(Gmode Setup, Glass Tunnel, Main Street, Everest, Crab Hole will be in a different PR)

Outer Maridia Partial Gmode Update

---

region/lowernorfair/east.json

These are done quickly now that turning off wall jumps is being used more, but these strats should be refined and have heat frames added

Add some quick wall jumps in lower norfail

---

region/brinstar/pink.json
region/maridia/inner-pink.json

I was in the room already when SM discord was taking about the precious door grapple clip again.

Walljumpless strats

---

region/crateria/west.json
region/maridia/inner-pink.json
region/maridia/inner-yellow.json
region/maridia/outer.json
tech.json

The ones I had a hard time with were made notable 👀 
Main street has a neat balance - a short one at the top, a tech appropirate one at the bottom, and slightly hard one in the middle.

canUnderwaterWalljump

---

region/lowernorfair/west.json

I also converted `canHeatRun` to `h_canNavigateHeatRooms`, and removed old ammo style references

GT Add Morph to PB Strat

---

region/maridia/inner-green.json

Tempting to add `canBePatient` because you have to reset the room for each attempt.  But with enough practice it looks like you can get somewhat consistent at the trick.
And it feels less insane to do after getting it a few times.
#898

Pants Room Grapplejump

---

region/norfair/east.json

Lava frame counts are guesses.
#864

SpikeSnake damage boosts

---

region/brinstar/blue.json
region/brinstar/pink.json
region/norfair/west.json

I've noticed players struggling with these strats. They really are somewhat tricky and shouldn't be enabled with no tech/notables.

Return Through Broken Crumbles - Notable

---

tech.json

there are currently only 2 strats with this tech. If there arent any/many more, it may be worth removing the tech completely and making them all notable.

Clarify canBabyMetroidAvoid tech

---

logicalRequirements.md
region/region-readme.md
schema/m3-region.schema.json
strats.md

Implements the schema/doc changes for the proposal in #909.

Add clearsObstacles strat property and update docs

---

region/maridia/outer.json

https://discord.com/channels/1053421401354285129/1053436236628496454/1100564018080514060

Wall jump to reset fall speed upon entry of Fish Tank

---

region/norfair/west.json

Noticed this because of what happened in your second seed today @osse101 .

Croc speedway reverse spark fix

---

.github/workflows/ci.yml
helpers.json
resources/ci/common/keywords.py
schema/m3-helpers.schema.json

Mostly helpers have only been moved into categories. Only Leniency helpers have been created and those that use them have been edited. 
Eventually more Leniency helpers would be added, so that all leniency resources are centrally located

Helper Structure

---

region/crateria/east.json

This should prevent tedious Sky Missiles from low difficulty settings and wall jump-less challenges

Update Sky Missiles

---

region/maridia/inner-pink.json
tech.json

I thought this was a good idea from #463

Remove canDraygonTurretGrappleJump, use notable instead

---

region/maridia/inner-yellow.json

This is all of Yellow Maridia, except quicksand rooms.

Yellow Maridia G-Mode Setup and Immobile

---

region/brinstar/green.json
region/brinstar/pink.json
region/lowernorfair/east.json
region/lowernorfair/west.json
region/maridia/inner-pink.json
region/maridia/outer.json
region/tourian/main.json
schema/m3-region.schema.json

1. reusableRoomwideNotable requires notable to be true
2. notable being true requires a note

notable schema update

---

region/brinstar/green.json
region/brinstar/kraid.json
region/brinstar/pink.json
region/brinstar/red.json
region/crateria/central.json
region/crateria/west.json
region/lowernorfair/west.json
region/maridia/inner-green.json
region/maridia/inner-pink.json
region/maridia/outer.json
region/norfair/crocomire.json
region/norfair/west.json
tech.json

`canSubmergedLeftFacingDoorXRayClimb` for the tech name.  
I tried a couple water->water, and water->air doors and didn't have any issues with them.  It helps immensely to have a [visual cue.](https://wiki.supermetroid.run/File:Suitless_right_door_stuck_summary.jpg)  I'd estimate it at 1/10 success rate.
Resolves #863

Water door stuck xray climbs

---

helpers.json
region/brinstar/blue.json
region/brinstar/green.json
region/brinstar/kraid.json
region/brinstar/pink.json
region/brinstar/red.json
region/crateria/central.json
region/crateria/west.json
region/lowernorfair/east.json
region/lowernorfair/west.json
region/maridia/inner-green.json
region/maridia/inner-pink.json
region/maridia/outer.json
region/norfair/crocomire.json
region/norfair/east.json
region/norfair/west.json
region/wreckedship/main.json
tech.json

Before I go through and convert everything, I was hoping to get feedback on this tech, specifically if you think it would be better, and if the tech and helper names seem reasonable.

X-Ray Rework

---

region/maridia/outer.json

This was harder to do than I remember.

update crab hole springball strat

---

region/brinstar/blue.json

Easier than most canUnmorphBombBoost, but thats what it is.

update Ceiling E-Tank Unmorph Bomb Boost

---

region/lowernorfair/east.json

This is the file with the most obstacles, by far, so I figured it would be best split in two.

Partial Lower Norfair East Obstacle Rework

---

region/lowernorfair/east.json
region/maridia/inner-pink.json
region/maridia/inner-yellow.json
tech.json

I added some more options for the `Snail Walk`. I didn't add the super method, because it brings the fast snail instead, and it would be close to also requiring patience. In the end, after trying it for a bit and then simply jumping across with an angle button, I am wondering if this should just be removed and the simpler option be added - thoughts?

Add More Patience Reqs

---

region/tourian/main.json
tech.json

Putting a strat between all useful items and no items looks pretty good.  Morph as a required item is a little hard to place, but with the waveless strat its expected to be harder to do stashio wise, even though you could still do it.
Resolves #908

Update Baby Skip

---

region/lowernorfair/east.json

3 Musketeers is significantly easier going down.
Mickey Mouse Crumble jump with blue is very hard, whereas with springball that component of the strat is trivial.

Split LN notables

---

region/lowernorfair/east.json

This Three Musketeers strat needs an obstaclesCleared requirement.

Add obstacle req on Kihunters Already Killed

---

region/maridia/outer.json
tests/asserts/keywords.py

[Tests] Strat names within a nodepair are to be unique

---

.github/workflows/ci.yml
LICENSE.md
schema/m3-bossScenarios.schema.json
schema/m3-connection.schema.json
schema/m3-enemies.schema.json
schema/m3-helpers.schema.json
schema/m3-items.schema.json
schema/m3-note.schema.json
schema/m3-region.schema.json
schema/m3-requirements.schema.json
schema/m3-tech.schema.json
schema/m3-weapons.schema.json

This appears to be less-breaking than I thought.
Waiting for a time when @blkerby is available to update stuff when I pull the lever.
@tewtal is less-reliant on having stuff re-pointed immediately.
Redirects *should* function appropriately when that happens.

Migrate repo to organization

---

region/norfair/east.json

retime volcano room

---

region/maridia/inner-pink.json
region/maridia/outer.json

Added a few more uses of `h_canMaxHeightSpringBallJump`
Updated some `Ice` strats to use `canTrickyUseFrozenEnemies`
Added a new strat to climb Main Street: https://discord.com/channels/1053421401354285129/1053436236628496454/1129587005311951009

Maridia - Max height spring ball, tricky frozen enemies

---

region/maridia/inner-pink.json

I still haven't been able to get it once.
Closes #987

East Sand Hole Insane Walljump Morph

---

region/maridia/inner-green.json

`Suitless HiJumpless Bomb into Springball Jump` is close to just being a tech, but I don't know of any other situations where you would walljumpInstantMorph, place a bomb, and use the bomb to springballjump.  It is very hard to do.
Using the height gain of a Walljump would work if you have HiJump, but here you would jump directly out instead.  But it could be another general tech around extreme difficulty.
Resolves #1017

Spring ball Room Escape

---

region/brinstar/green.json
region/brinstar/pink.json
region/crateria/east.json
region/crateria/west.json
region/lowernorfair/east.json
region/maridia/inner-pink.json
region/maridia/inner-yellow.json
region/maridia/outer.json
region/norfair/east.json
region/norfair/west.json
region/tourian/main.json
region/wreckedship/main.json

I didn't touch any of the strats going up the Three Musketeer's Room, because I wasn't sure how they would be done without `canCameraManip`

Add uses of canCameraManip

---

region/brinstar/green.json

This is a bit harder than a normal x-ray turnaround, so it should be in a slightly higher difficulty tier (Map Rando: `VH` -> `Expert`)

Green Hill X-Ray Wiggle - Notable

---

region/brinstar/green.json

https://vimeo.com/715803825
I think this is the only gate it works on.

Grapple Gate Glitch

---

region/brinstar/green.json

This is intended to include all Green Brinstar uses and setups excluding Green Hill Zone and the Etecoon Energy Tank Room

G-Mode: Green Brinstar Pt. 2

---

region/tourian/main.json

#1019 may be taken care of.  I didn't visit PBs as a weapon in any way.
#714 M2 looked like it needs a specific setup even if its just a buffered spinjump.  M4 down the strat with Morph is used in every speedrun so is probably known well enough.  Without items was made notable.  Didn't touch PB strats, again.
#953 is done.  `canBlueSpaceJump` is a harder tech than what is needed, but fine.  M4 had too many Rinka shots for me to make it through damageless with just pseduo screw.

Metroid rooms

---

logicalRequirements.md
region/brinstar/pink.json
schema/m3-requirements.schema.json
tests/asserts/keywords.py

This was replaced with `obstaclesNotCleared`.

Remove obstaclesToAvoid

---

region/brinstar/pink.json

- Dachora Room
- Pink Brinstar Power Bomb Room
- Pink Brinstar Hopper Room (half)
- Still need IBJ, PB kill, and indirect strats (left to right)

Pink Brinstar: Add some G-Mode Strats

---

region/brinstar/pink.json

This includes strats to get between the top three doors, to get to the new G-Mode Morph junction, and to get from the junction to the top left door. 
Still need the rest of the room, as well as possibly Spring Ball + Power Bomb strats, which would require PLMs to be overloaded first, to prevent the PB from hitting the block.
The hardest part was figuring out where to put the junction :)

G-Mode: Big Pink Top Third

---

region/brinstar/pink.json

Added strats: 
- to 4, 10
- from 6
- break B
Still need:
- to 8, 12
- from 8, 9
- remote acquire 10, 11

G-Mode: Big Pink part 2

---

region/brinstar/pink.json

Should only be missing the remote acquiring of items now.

G-Mode in Big Pink part 3

---

region/brinstar/green.json

G-Mode Through the Spikeway

---

region/tourian/main.json

Relies on normalized movement, like all the other room strats.

Tourian Hopper Shinespark

---

region/brinstar/green.json
region/brinstar/kraid.json
region/crateria/central.json
region/crateria/east.json
region/lowernorfair/east.json
region/maridia/inner-pink.json
region/maridia/inner-yellow.json
region/maridia/outer.json
region/norfair/east.json
region/tourian/main.json
region/wreckedship/main.json

Add strats at the top of each vertical door. This is assuming you can always enter from off center on either side. I did not edit the 3 rooms in Croc's section.
This addresses #670.

Add vertical spark into room strats

---

region/lowernorfair/east.json
region/norfair/west.json

Guess I thought Croc Speedway was in Croc's section.

Missing Vertical Spark + Heat adjust

---

helpers.json
region/brinstar/green.json
region/brinstar/pink.json
region/brinstar/red.json
region/crateria/central.json
region/lowernorfair/east.json
region/lowernorfair/west.json
region/maridia/inner-green.json
region/maridia/inner-pink.json
region/maridia/outer.json
region/norfair/east.json
region/norfair/west.json

This reverts commit 091d7fa6907cdbcb4026d1240b6a9536d9c36c3c.

Revert "Update Cross-Room X-Ray Climbs (#1117)"

---

region/norfair/west.json

There's a balance to heated room runways between duplicating strats and saving small amounts of heat frames.

Update Cross-Room Runways in UN West

---

.git-blame-ignore-revs
region/brinstar/blue.json
region/brinstar/green.json
region/brinstar/kraid.json
region/brinstar/pink.json
region/brinstar/red.json
region/ceres/main.json
region/crateria/central.json
region/crateria/east.json
region/crateria/west.json
region/lowernorfair/east.json
region/lowernorfair/west.json
region/maridia/inner-green.json
region/maridia/inner-pink.json
region/maridia/inner-yellow.json
region/maridia/outer.json
region/norfair/crocomire.json
region/norfair/east.json
region/norfair/west.json
region/tourian/main.json
region/wreckedship/main.json

Run the autoformatter script to standardize all existing JSON files in /region.
And add this commit to a blame-ignore-revs so that it does not show up with git blame.

Run Autoformatter to standardize JSON formatting

---

region/ceres/main.json

I figure this region had to be done eventually. I didn't include strats for using short runways to leave charged, runways coming in, etc. because this is unlikely to be used and its unclear how it's doorways would even connect to normal rooms.

Ceres Runways

---

region/maridia/inner-green.json
region/maridia/inner-pink.json

I wasn't sure how tight to make the leaving charged strats in Botwoon Hallway. I got both of them with 10 more frames, but it was very uncommon.

Runway Migration - Easy Rooms in Pink/Green Maridia

---

region/maridia/inner-green.json
region/maridia/inner-pink.json
region/maridia/outer.json
schema/m3-region.schema.json
strats.md
tests/asserts/keywords.py

This includes all of the horizontal cross room jumps that are included in bobbob's collection. I re-determined the length of runway needed for each of these strats from the videos:
https://vimeo.com/showcase/10188956

Cross Room Migration: Jump Into Water (Horizontal)

---

region/norfair/east/Cathedral Entrance.json
region/norfair/east/Cathedral.json
region/norfair/east/Frog Speedway.json
region/norfair/east/Rising Tide.json
region/norfair/east/Upper Norfair Farming Room.json

Set the farm room GGG strat to return to the farm spot so that leaving with the runway is easier.

Upper Norfair Runways First Rooms

---

region/brinstar/green/Green Brinstar Fireflea Room.json
region/brinstar/green/Green Brinstar Main Shaft.json

Also adds a couple new strats in the Etecoon shaft: an X-ray climb up into the tunnel, and a moonfall into sparking out the door.
Also cleans up old-style cross-room strats in Green Brinstar Firefleas room which I forgot to remove after doing the migration.

Runway migration for Green Brinstar Main Shaft

---

region/brinstar/green/Brinstar Reserve Tank Room.json
region/brinstar/green/Green Brinstar Main Shaft Save Room.json
region/brinstar/green/Green Brinstar Missile Refill.json
region/brinstar/green/Green Hill Zone.json
region/brinstar/green/Noob Bridge aka A Bridge Too Far.json
region/brinstar/green/Spore Spawn Kihunter Room.json
region/brinstar/green/Spore Spawn Room.json

There is opportunity to add more leave charged/sparking strats, e.g. in Green Hill Zone for the top doors (and a ton of 3-room strats in Green Brinstar Main Shaft). This PR is mostly just trying to migrate the existing ones

Rest of Green Brin Runway migration

---

region/maridia/outer/Main Street.json

Could still add spark strats from 1/2 -> 3

Runway Migration: Main Street

---

region/maridia/inner-pink/East Cactus Alley Room.json
region/maridia/inner-pink/Halfie Climb Room.json
region/maridia/inner-pink/West Cactus Alley Room.json

This should be the last of the Pink Maridia migration, minus a few strats here and there which I couldn't replicate.

Runway Migration: Finishing off Pink Maridia

---

helpers.json
region/norfair/east/Nutella Refill.json
region/norfair/east/Purple Shaft.json
region/norfair/east/Red Pirate Shaft.json
region/norfair/east/Rising Tide.json
region/norfair/east/Single Chamber.json
region/norfair/east/Speed Booster Hall.json
region/norfair/east/Speed Booster Room.json
region/norfair/east/Spiky Acid Snakes Tunnel.json
region/norfair/east/Spiky Platforms Tunnel.json
region/norfair/east/Upper Norfair Farming Room.json
region/norfair/east/Volcano Room.json
region/norfair/east/Wave Beam Room.json
region/norfair/west/Business Center.json
region/norfair/west/Crocomire Escape.json
region/norfair/west/Crocomire Save Room.json
region/norfair/west/Crocomire Speedway.json
region/norfair/west/Crumble Shaft.json
region/norfair/west/Hi Jump Boots Room.json
region/norfair/west/Hi Jump Energy Tank Room.json
region/norfair/west/Ice Beam Acid Room.json
region/norfair/west/Ice Beam Gate Room.json
region/norfair/west/Ice Beam Room.json
region/norfair/west/Ice Beam Snake Room.json
region/norfair/west/Ice Beam Tutorial Room.json
region/norfair/west/Norfair Map Room.json

It looks like I slightly underestimated the heatFrames needed in the `h_canHeatedCrystalFlash` before, probably had a lucky RNG on the heat cycle. Bumping it up from 180 to 185.

Rest of Upper Norfair Crystal Flash strats

---

region/maridia/inner-pink/Botwoon Hallway.json
region/maridia/inner-pink/Crab Shaft.json
region/maridia/inner-yellow/Pseudo Plasma Spark Room.json
region/maridia/outer/Main Street.json
region/maridia/outer/Mt. Everest.json
region/wreckedship/main/Attic.json

Skipping Mt. Everest (just adding a FIXME) because it looks horrible.

Maridia ice vertical door lock skips (+ one more WS)

---

region/brinstar/green/Green Brinstar Main Shaft.json
region/maridia/inner-pink/Crab Shaft.json

Forgot to put the room name here when this was added.

Add room name to Sciser Ice Clip Door Lock Skip notable

---

region/brinstar/green/Green Brinstar Beetom Room.json
region/brinstar/pink/Pink Brinstar Hopper Room.json
region/brinstar/pink/Spore Spawn Farming Room.json
region/crateria/central/Crateria Super Room.json
region/crateria/central/Final Missile Bombway.json
region/maridia/inner-yellow/Watering Hole.json
region/maridia/outer/West (Glass Tube) Tunnel.json
region/norfair/east/Speed Booster Hall.json
region/norfair/west/Crocomire Speedway.json
region/wreckedship/main/Wrecked Ship Main Shaft.json

This finishes off the majority of the remaining strats that aren't in LN

Runway Migration - Stragglers

---

region/maridia/outer/Crab Hole.json

Freezing two crabs here in the right positions at the same time seems tricky to me. I don't think we want this in Medium.

Add req to Crab Hole Suitless HiJump

---

region/brinstar/green/Green Brinstar Main Shaft.json

The "Speedy Spring Ball Jump" can be done without needing to shoot open the door.

Green brin main shaft Spring Ball jumps

---

region/crateria/west/Gauntlet Entrance.json
region/crateria/west/Green Brinstar Elevator Room.json
region/crateria/west/Statues Room.json

Still missing Gauntlet E-Tank Room and Green Pirate Shaft.
#1240 should be merged before this one.

Some of the missing G-Mode strats in Crateria West

---

region/wreckedship/main/Basement.json
region/wreckedship/main/Wrecked Ship Main Shaft.json

These are the easy strats that could be migrated. Ones with multiple from nodes and adding an obstacle to Basement

G-Mode Migration: Wrecked Ship - Easy Strats

---

region/brinstar/green/Green Hill Zone.json

[Video](https://youtu.be/wGbASK2s64o)

Green Hill Zone airball to item

---

region/maridia/inner-yellow/Plasma Spark Room.json

Also fix the destination node of a G-Mode Morph strat in this room.

Add shortcharge strats in Plasma Spark Room

---

region/maridia/inner-green/East Pants Room.json
region/maridia/inner-green/Oasis.json
region/maridia/inner-green/Pants Room.json
region/maridia/inner-green/Shaktool Room.json
region/maridia/inner-green/Spring Ball Room.json
region/maridia/inner-green/West Sand Hall Tunnel.json

This includes both running the script and edits to finish off the region. This section only had a few minor edits: adding a patience requirement, manually moving one strat, and adding some notes and a fixme.

G-Mode Migration: Green Maridia

---

region/tourian/main/Blue Hopper Room.json
region/tourian/main/Metroid Room 1.json
region/tourian/main/Metroid Room 2.json
region/tourian/main/Metroid Room 3.json
region/tourian/main/Metroid Room 4.json

Mostly consists of artificial morph PB Metroid kills.

Add Missing G-Mode Strats in Tourian

---

region/brinstar/blue/Blue Brinstar Energy Tank Room.json

Do we think this should maybe also be notable (in Medium) for the sake of bringing visibility to it?

Add canCarefulJump req to Blue Brin Ceiling E-Tank Speed Jump

---

region/maridia/outer/Boyon Gate Hall.json
region/maridia/outer/Crab Hole.json

Manually migrating the remaining strats which had multiple fromNodes, and adding artificial morph strats from the bottom to top of Crab Hole

G-Mode Migration: Boyon Gate, Crab Hole

---

region/lowernorfair/east/Fast Pillars Setup Room.json
region/lowernorfair/east/Mickey Mouse Room.json
region/norfair/crocomire/Post Crocomire Shaft.json
region/norfair/east/Acid Snakes Tunnel.json
region/norfair/west/Ice Beam Tutorial Room.json

Ran the script, then moved two strats in Post Croc Shaft that climb with a frozen Viola to start at the bottom of the room to save a Super

G-Mode Migration: Run Scripts for the Few Strats in Norfair

---

region/brinstar/green/Brinstar Pre-Map Room.json
region/brinstar/green/Brinstar Reserve Tank Room.json
region/brinstar/green/Early Supers Room.json
region/brinstar/green/Etecoon Energy Tank Room.json
region/brinstar/green/Green Brinstar Beetom Room.json
region/brinstar/green/Green Brinstar Main Shaft.json
region/brinstar/green/Green Hill Zone.json
region/brinstar/green/Noob Bridge.json
region/brinstar/green/Spore Spawn Kihunter Room.json

I think this looks good to merge. I only edited a strat in Early Supers to use the new obstacle instead of a `resetroom`.
This section looked really good overall, and there are not many edits needed as a future PR, except migrating strats with multiple `fromNodes`.

G-Mode Migration: Green Brinstar - Run Scripts

---

region/brinstar/kraid/Baby Kraid Room.json
region/brinstar/kraid/Warehouse Energy Tank Room.json
region/brinstar/kraid/Warehouse Entrance.json
region/brinstar/kraid/Warehouse Kihunter Room.json
region/brinstar/kraid/Warehouse Zeela Room.json
region/brinstar/pink/Big Pink.json
region/brinstar/pink/Dachora Room.json
region/brinstar/pink/Pink Brinstar Hopper Room.json
region/brinstar/pink/Pink Brinstar Power Bomb Room.json
region/brinstar/pink/Spore Spawn Farming Room.json
region/brinstar/pink/Spore Spawn Super Room.json
region/brinstar/pink/Waterway Energy Tank Room.json
region/brinstar/red/Red Tower.json

This section actually has quite a few things that need to be edited, so I figure I'll do it at a separate time. 
I didn't fully review the migration of Big Pink, but will do so when I finish off this area.

G-Mode Migration: Remaining Areas of Brinstar - Run Scripts

---

helpers.json
region/brinstar/blue/Blue Brinstar Energy Tank Room.json
region/brinstar/blue/Construction Zone.json
region/brinstar/blue/Morph Ball Room.json
region/crateria/central/Climb.json
region/crateria/central/Parlor and Alcatraz.json
region/crateria/central/Pit Room.json
region/crateria/central/The Final Missile.json
strats.md
tech.json

This has been a point of confusion in Map Rando. This can help reduce the confusion by adding it as a tech in `Medium`

Add canAwakenZebes Knowledge Tech

---

region/brinstar/green/Spore Spawn Room.json
region/crateria/central/Bomb Torizo Room.json
region/lowernorfair/west/Golden Torizo's Room.json
region/maridia/inner-pink/Botwoon's Room.json
region/maridia/inner-pink/Draygon's Room.json
region/norfair/crocomire/Crocomire's Room.json
region/wreckedship/main/Phantoon's Room.json

- Phantoon had no logic?
- My Croc reference has 30 missiles going into the fight as just enough for a Hard player.
- GT blocks a lot of charge spazer shots and that was lame
- BT very often gets some hits in before drops appear to farm health

Boss Update

---

region/brinstar/red/Red Brinstar Fireflea Room.json
region/crateria/central/Climb.json
region/crateria/central/Pit Room.json
region/crateria/east/East Ocean.json
region/lowernorfair/east/Amphitheatre.json
region/lowernorfair/east/Mickey Mouse Room.json
region/lowernorfair/east/Pillar Room.json
region/maridia/inner-green/East Sand Hall.json
region/maridia/inner-green/Oasis.json
region/maridia/inner-green/Pants Room.json
region/maridia/inner-green/West Sand Hall.json
region/maridia/inner-pink/Colosseum.json
region/maridia/inner-yellow/Plasma Spark Room.json
region/maridia/outer/Fish Tank.json
region/maridia/outer/Mama Turtle Room.json
region/maridia/outer/Mt. Everest.json
region/norfair/east/Norfair Reserve Tank Room.json
region/tourian/main/Big Boy Room.json

- Removed Everest Foosball since it is only a perfectly timed jump

Insane jump

---

region/wreckedship/main/Wrecked Ship Main Shaft.json

This recently added strat seemed to be missing a Morph requirement. Also the note referenced Spring Ball which I don't think is required

Add Morph req to Spooky Missile Temp Blue strat

---

region/brinstar/pink/Big Pink.json
region/maridia/outer/Mt. Everest.json
tech.json

This felt like it should be a tech even though there's only these two places where we (currently) know of an application.

Deep transition tech: X-Ray climbs in Big Pink and Everest

---

region/brinstar/pink/Pink Brinstar Power Bomb Room.json
region/maridia/outer/Mt. Everest.json

We already had the crazy strat that does two consecutive grapple bomb jumps here. But with HiJump you can do it with a single grapple bomb jump.

Everest HiJump grapple bomb jump

---

region/brinstar/red/Red Tower.json

This is a recent strat from Bobbob: https://discord.com/channels/1053421401354285129/1053436236628496454/1207096037836193802
I wasn't really sure how many Beetom hits to put in for leniency because it's hard for me to tell how viable it is to do these jumps consistently.

Red Tower Frozen Beetom Climb

---

region/brinstar/red/Red Brinstar Fireflea Room.json

Noticed this on Eddie's stream: https://clips.twitch.tv/TardyBoredBaboonPJSalt-4DmlZ-_BxOgdpA2Y. Tried it out and it seems reasonable. If there were a different tech requirement that could bump up the 2-hit version to Expert, that may be ideal? But I don't know what we would use?

Update X-Ray Exit Damage Boost waver hits

---

region/maridia/inner-pink/Aqueduct.json
region/maridia/inner-pink/Below Botwoon Energy Tank.json
region/maridia/inner-pink/Botwoon Hallway.json
region/maridia/inner-pink/Colosseum.json
region/maridia/inner-pink/Crab Shaft.json
region/maridia/inner-pink/Halfie Climb Room.json

Skipped a few here, which can be added on a second pass:
- East Pants with a Puyo - its bad but not terrible ... but it has no use if East Pants connects to Pants.
- Botwoon E-Tank - it doesnt look like the Puyos align easily. The Zoa from across the room also doesnt align with any easy setup.
- The Oums in Halfie Climb - they are a lot of fun to play with, but I couldn't find anything too reliable and it wasnt clear if a short charge is possible on them.

Frozen Enemy Runways in Pink & Green Maridia

---

region/maridia/inner-yellow/Bug Sand Hole.json
region/maridia/inner-yellow/Butterfly Room.json
region/maridia/inner-yellow/Kassiuz Room.json
region/maridia/inner-yellow/Watering Hole.json
region/maridia/outer/Boyon Gate Hall.json
region/maridia/outer/Crab Hole.json
region/maridia/outer/Crab Tunnel.json
region/maridia/outer/Main Street.json
region/maridia/outer/Mt. Everest.json
region/maridia/outer/Red Fish Room.json

I didn't skip many in this section:
- NW Maridia Bug Room
- Thread the Needle

Frozen Enemy Runways in Yellow & Outer Maridia

---

region/brinstar/pink/Pink Brinstar Hopper Room.json

These are new right-side X-Ray climb strats by bobbob:
HiJump: https://www.youtube.com/watch?v=_hblD6uxx58
G-Mode: https://www.youtube.com/watch?v=hYkD5BnNjW8
Spring Ball: https://www.youtube.com/watch?v=Nj6_FBbgFsY
I tested them to work out details on positioning. Also added more cross-room Speed jump strats on both sides.

Pink Hoppers more walljumpless strats

---

region/tourian/main/Metroid Room 1.json
region/tourian/main/Metroid Room 2.json
region/tourian/main/Metroid Room 3.json
region/tourian/main/Metroid Room 4.json
region/tourian/main/Rinka Shaft.json

Skipped a few strats:
- Metroid room 3 right door
- Rinka Shaft top door
- Both MB doors - the left door could be added with a helper, but the right door could cause some problems for Map Rando. I'll add it on my next pass through.

Frozen Enemy Runways in Tourian

---

region/maridia/outer/Fish Tank.json

This strat is currently in Medium. Skilled players regularly seem unaware that this is possible. I figure it should at least need "canTrickyUseFrozenEnemies", which would put it in Hard. @osse101 Do you think Hard is ok, or should it need something to bump it to Very Hard, either a "canTrickyJump" or notable? The jump doesn't seem very precise as long as the fish is frozen in a good spot.

Fish Tank tricky frozen fish

---

region/norfair/crocomire/Grapple Tutorial Room 3.json
region/norfair/crocomire/Post Crocomire Farming Room.json
region/norfair/east/Bubble Mountain.json
region/norfair/east/Red Pirate Shaft.json
region/norfair/west/Hi Jump Energy Tank Room.json
region/norfair/west/Ice Beam Gate Room.json

Things that were skipped for this PR:
- All of Business Center, as there's a big open PR in that room right now
- It may be possible to use a frozen Waver in Bubble Mountain
- PCJR using a frozen Mella

Unheated Frozen Enemy Runways in Norfair

---

region/brinstar/green/Green Hill Zone.json
region/lowernorfair/west/Screw Attack Room.json
region/maridia/inner-green/Pants Room.json
region/maridia/outer/Fish Tank.json
region/maridia/outer/Glass Tunnel.json
tech.json

Also edited the green hills grapple gate glitch while I had the file open.

Tricky grapple jump

---

region/norfair/west/Business Center.json
region/norfair/west/Crocomire Escape.json
region/norfair/west/Crumble Shaft.json
region/norfair/west/Ice Beam Snake Room.json

Here is Insomnia's video for the Geruta freeze: https://discord.com/channels/1053421401354285129/1053436236628496454/1156796076339245066
It's possible but terrible to freeze the Geruta to extend the left runway, but I'm leaving that out.
PS: There were no more runways needed in Crocomire's section, so that's done too.

Frozen Enemy Runways in Norfair West

---

region/maridia/inner-green/East Sand Hall.json
region/maridia/inner-green/Oasis.json
region/maridia/inner-green/West Sand Hall Tunnel.json
region/maridia/inner-yellow/Butterfly Room.json
region/maridia/inner-yellow/Pseudo Plasma Spark Room.json
region/maridia/outer/Crab Hole.json
region/maridia/outer/Crab Tunnel.json
region/maridia/outer/Fish Tank.json
region/maridia/outer/Glass Tunnel.json
region/maridia/outer/Main Street.json
region/maridia/outer/Mama Turtle Room.json
region/maridia/outer/Mt. Everest.json
region/wreckedship/main/Sponge Bath.json

- Crab hole jump is annoying on Very hard, so I made it notable
- I couldn't do the Glass Tube bottom to top jump so I put insanejump on it; ~and I need to look at it some more~
- I couldn't do the east sand hall springball bomb jump, but I believe I have gotten it in the past, so I take it as being much harder than positioning the bomb correctly.

Cross room jumps into Water review - The rest of Maridia

---

region/norfair/east/Spiky Acid Snakes Tunnel.json

- Renamed the ice notable to be "Snakes"  
- There are many combinations of runway length / springfling / airball vs falling morph.  I went for airball + no springfling.

Spiky Acid Snakes Tunnel

---

region/norfair/east/Upper Norfair Farming Room.json

This gate requires significantly less leniency due to the farm and has been a reoccurring problem.
@osse101 , @blkerby - What do you think about this solution?

Upper Norfair Farming Room Gate Glitch

---

region/brinstar/blue/Blue Brinstar Energy Tank Room.json
region/brinstar/pink/Big Pink.json
region/crateria/central/Landing Site.json
region/crateria/east/Crab Maze.json
region/crateria/east/West Ocean.json
region/crateria/west/Green Pirates Shaft.json
region/maridia/inner-pink/Aqueduct.json
region/maridia/inner-yellow/Maridia Elevator Room.json
region/maridia/outer/Crab Hole.json
region/maridia/outer/Mt. Everest.json
schema/m3-room.schema.json

Also new `"nodeSubType": "g-mode"` to help find them easier in the future.

Use Artificial Morph Helpers from G-Mode Junctions

---

region/maridia/inner-green/East Sand Hall.json
region/maridia/inner-green/West Sand Hall.json
region/maridia/inner-pink/Botwoon Quicksand Room.json
region/maridia/outer/Fish Tank.json
region/tourian/main/Blue Hopper Room.json

Botwoon QuickSand Room was interesting where it looked like dash state rolling(assuming that's why) gives a lot more drift speed.  Dodging Bulls wasn't realistic.
The other quicksand rooms could use some science on Bull movement.

Turbo tube Related Strat Changes

---

region/norfair/crocomire/Crocomire's Room.json

We can refine the ceiling bomb jump requirements here once #1436 is merged.

Crossing Crocomire's Room acid

---

region/brinstar/red/Red Tower.json

This should finish off Red Brinstar.

Add G-Mode Strats in Red Tower

---

region/maridia/outer/Crab Hole.json

Add Strats in Crab Hole

---

region/norfair/east/Lava Dive Room.json
tests/asserts/keywords.py

partialRefill wasn't being handled in tests.

Max lava dive

---

region/brinstar/kraid/Baby Kraid Room.json
region/brinstar/kraid/Kraid Eye Door Room.json
region/brinstar/kraid/Kraid Room.json

Looks like this subregion was mostly complete, but was missing a few things.

G-Mode in Kraid's Brinstar - A Few Missing Strats

---

region/norfair/east/Frog Speedway.json
region/norfair/west/Hi Jump Energy Tank Room.json
region/norfair/west/Ice Beam Gate Room.json

If the Frog Speedway [1, 2] leave with G-Mode is too hard for no requirements, I can convert the speed blocks to an obstacle and split the strat.

A Few G-Mode Setups in Unheated Norfair

---

region/tourian/main/Blue Hopper Room.json

This is the Blue Hopper dodge that Eddie did in his seed yesterday: https://clips.twitch.tv/DistinctSwissFiddleheadsLeeroyJenkins-pYlLF0RMYe6yet2H.
Also a new, easy way to get through with Screw Attack, obsoleting the other Screw Attack strats. I put "canTrickyJump" on it only because the movement is potentially unintuitive; it's very lenient, with no specific timings on the jumps.

Blue Hopper left-to-right dodging and Screw Attack

---

region/maridia/inner-green/Pants Room.json
region/maridia/inner-pink/Colosseum.json

This is based on insomniaspeed's technique:
https://youtu.be/hf-dM3JpZbk?si=Le3jZ-xWsN_LkQz4
https://youtu.be/1du4nXXcD8c?si=c007eDdU5cQOgFy1
After learning the timing and practicing for a bit, the spring fling method in Colosseum does seem much easier.

Spring fling bomb water escapes

---

region/norfair/crocomire/Grapple Beam Room.json
region/norfair/crocomire/Post Crocomire Missile Room.json
region/norfair/crocomire/Post Crocomire Shaft.json

There are some problems with vertical doors and G-Mode, with and without the toilet conditions. I'll make a pass through all of them once I finish unheated Norfair.

Add G-Mode to Grapple Room, Post Croc Shaft, Missiles

---

region/norfair/east/Bubble Mountain.json

~~Added uses and immobile strats. Still need to add the setups.~~
Added uses and immobile strats and the setups.

G-Mode in Bubble Mountain

---

region/brinstar/green/Green Brinstar Beetom Room.json
region/brinstar/green/Green Brinstar Main Shaft.json
region/brinstar/green/Spore Spawn Room.json
region/brinstar/kraid/Warehouse Zeela Room.json
region/brinstar/pink/Big Pink.json
region/crateria/central/Parlor and Alcatraz.json
region/crateria/east/Crateria Kihunter Room.json
region/crateria/east/West Ocean.json
region/lowernorfair/east/Mickey Mouse Room.json
region/lowernorfair/west/Screw Attack Room.json
region/maridia/inner-pink/Botwoon Hallway.json
region/maridia/inner-yellow/Pseudo Plasma Spark Room.json
region/maridia/outer/Main Street.json
region/norfair/crocomire/Post Crocomire Farming Room.json
region/norfair/crocomire/Post Crocomire Shaft.json
region/wreckedship/main/Attic.json
region/wreckedship/main/Wrecked Ship Main Shaft.json
strats.md
tech.json

It looks like the easy free falls (like right above doors) aren't notable, but the longer ones are.

Add canFreeFallClip tech

---

region/maridia/inner-yellow/Plasma Spark Room.json

Node 6 could maybe be removed entirely. Keeping it for now just in case an application is found.

Remove bad strat in Plasma Spark Room

---

region/brinstar/green/Brinstar Map Room.json
region/brinstar/green/Brinstar Pre-Map Room.json
region/brinstar/green/Brinstar Reserve Tank Room.json
region/brinstar/green/Early Supers Room.json
region/brinstar/green/Etecoon Energy Tank Room.json
region/brinstar/green/Etecoon Save Room.json
region/brinstar/green/Etecoon Super Room.json
region/brinstar/green/Green Brinstar Fireflea Room.json
tech.json

This is mostly just the easier strats which were easy to test.  More will come later.

Flash Suit Strat Compatibility - Green Brinstar Pt. 1

---

region/crateria/east/East Ocean.json
region/lowernorfair/east/Lower Norfair Fireflea Room.json
region/lowernorfair/east/Red Kihunter Shaft.json
region/maridia/inner-green/Pants Room.json
tech.json

- East Ocean Damage Boosts
- Bottom Ki Stairs Dodge
- Jump Morph over firefleas Fune
- Pants room Diagonal Shinespark
- RMode gets `noFlashSuit` -- The general case is from a crouch jump.  If you really want, it could be a spinjump or straight jump into pseudo buffered down presses.

Some logic tweaks

---

region/brinstar/blue/Blue Brinstar Energy Tank Room.json
region/brinstar/red/Red Tower.json
region/lowernorfair/east/Fast Pillars Setup Room.json
region/lowernorfair/east/The Worst Room In The Game.json
region/lowernorfair/west/Screw Attack Room.json
tech.json

For the Screw Attack Room, I just used the IBJ heat frames that were used in [5, 3]

Add and use canPowerBombMidIBJ

---

region/maridia/inner-pink/The Precious Room.json
region/maridia/outer/Main Street.json
tech.json

I double checked all strats with `{"tech": ""}` to ensure there were no other problems.

A Few Small Edits

---

region/brinstar/green/Green Brinstar Main Shaft.json
region/brinstar/pink/Dachora Room.json
region/brinstar/red/Red Tower.json
region/crateria/central/Climb.json
region/crateria/central/Crateria Tube.json
region/crateria/central/Landing Site.json
region/crateria/east/Bowling Alley Path.json
region/crateria/east/Homing Geemer Room.json
region/crateria/west/Green Pirates Shaft.json
region/crateria/west/Lower Mushrooms.json
region/crateria/west/Terminator Room.json
region/lowernorfair/east/Red Kihunter Shaft.json
region/maridia/inner-green/Oasis.json
region/maridia/inner-green/West Sand Hall Tunnel.json
region/maridia/inner-yellow/Plasma Tutorial Room.json
region/maridia/outer/Boyon Gate Hall.json
region/maridia/outer/Glass Tunnel.json
region/maridia/outer/West Glass Tube Tunnel.json
region/norfair/east/Frog Speedway.json
region/norfair/east/Lower Norfair Elevator.json
region/norfair/east/Speed Booster Hall.json
region/norfair/west/Business Center.json
region/norfair/west/Ice Beam Gate Room.json
region/wreckedship/main/Gravity Suit Room.json
region/wreckedship/main/Wrecked Ship Entrance.json

Didn't add it to strats with screw to break a block while still having stored fall speed, because I wasn't able to test it.

Add flashSuitChecked to transitioning with stored fall speed

---

region/norfair/crocomire/Post Crocomire Jump Room.json

PCJR Quick Fix: Return right if speed blocks are broken, morphless

---

region/brinstar/green/Brinstar Pre-Map Room.json
region/brinstar/kraid/Warehouse Kihunter Room.json
region/brinstar/pink/Big Pink.json
region/brinstar/pink/Pink Brinstar Hopper Room.json
region/brinstar/pink/Waterway Energy Tank Room.json
region/brinstar/red/Alpha Power Bomb Room.json
region/brinstar/red/Below Spazer.json
region/crateria/central/Climb.json
region/crateria/central/Crateria Super Room.json
region/crateria/central/Parlor and Alcatraz.json
region/crateria/west/Gauntlet Energy Tank Room.json
region/crateria/west/Gauntlet Entrance.json
region/lowernorfair/east/Amphitheatre.json
region/lowernorfair/east/Lower Norfair Spring Ball Maze Room.json
region/lowernorfair/east/Mickey Mouse Room.json
region/lowernorfair/east/Pillar Room.json
region/lowernorfair/west/Screw Attack Room.json
region/maridia/inner-pink/Botwoon Energy Tank Room.json
region/norfair/crocomire/Post Crocomire Jump Room.json
region/norfair/west/Crocomire Speedway.json
region/tourian/main/Blue Hopper Room.json
region/tourian/main/Metroid Room 1.json
region/tourian/main/Metroid Room 3.json
region/tourian/main/Tourian Escape Room 3.json
region/tourian/main/Tourian Escape Room 4.json
region/wreckedship/main/Bowling Alley.json

I looked through all of the strats, but didn't touch ones with temporary blue. I'm thinking most of those need to be split based on if they gain the temp blue from a speedball or shinecharge.

Convert some comeInShinecharging to comeInGettingBlueSpeed

---

region/brinstar/green/Brinstar Pre-Map Room.json
region/brinstar/green/Early Supers Room.json
region/brinstar/green/Etecoon Energy Tank Room.json
region/brinstar/green/Green Brinstar Beetom Room.json
region/brinstar/green/Green Brinstar Fireflea Room.json
region/brinstar/green/Green Brinstar Main Shaft Save Room.json
region/brinstar/green/Green Brinstar Main Shaft.json
region/brinstar/green/Green Brinstar Missile Refill.json
region/brinstar/green/Green Hill Zone.json
region/brinstar/green/Noob Bridge.json
region/brinstar/green/Spore Spawn Kihunter Room.json
region/brinstar/green/Spore Spawn Room.json

This should finish off all of the simpler strats in the region

Verify flash suit compatibility in Green Brinstar - Part 2

---

region/brinstar/pink/Big Pink.json
region/crateria/central/Crateria Tube.json
region/lowernorfair/east/Amphitheatre.json
region/maridia/inner-yellow/Bug Sand Hole.json
region/maridia/outer/Crab Hole.json
region/maridia/outer/Glass Tunnel.json
region/norfair/west/Ice Beam Gate Room.json
region/tourian/main/Big Boy Room.json
region/tourian/main/Mother Brain Room.json
region/tourian/main/Seaweed Room.json

This will fix some strats, but more spawn ats should be added.

Add G-Mode Return Strats - Horizontal SpawnAt, Doorways

---

region/brinstar/blue/Blue Brinstar Boulder Room.json
region/brinstar/blue/Morph Ball Room.json
region/crateria/east/West Ocean.json
region/lowernorfair/east/Fast Pillars Setup Room.json
region/lowernorfair/east/Mickey Mouse Room.json
region/lowernorfair/east/Ridley's Room.json
region/lowernorfair/west/Screw Attack Room.json
region/tourian/main/Blue Hopper Room.json

Looks like the enemy ones are fine, as Samus will have i-frames.

Add G-Mode return strats where there are SpawnAts

---

helpers.json
region/crateria/central/Climb.json

There are some strats that arent perfect; they basically all deal with going to door 4 moderately slowly, or 4 is locked.

Climb - Add logic for rising lava

---

region/maridia/outer/Boyon Gate Hall.json
region/maridia/outer/Crab Hole.json

Crab Hole has new applications with cross-room space jumps and spring ball bounces. The spring ball bounces split into different runway requirements based on uncontrolled vs. controlled bounces. And most of the strats also split based on whether Speedbooster is equipped. This also includes refinements of the existing cross-room jump strats.

Boyon Gate and Crab Hole remote runways

---

region/brinstar/blue/Blue Brinstar Boulder Room.json
region/brinstar/blue/Blue Brinstar Energy Tank Room.json
region/brinstar/blue/Morph Ball Room.json
region/brinstar/pink/Dachora Room.json
region/brinstar/pink/Pink Brinstar Hopper Room.json
region/brinstar/pink/Pink Brinstar Power Bomb Room.json
region/brinstar/pink/Waterway Energy Tank Room.json

I was thinking it would be nice to have maintaining a flash suit have an implicit requirement of: `canTrickyJump`, `canPrepareForNextRoom`, `canMidairShinespark`. All frames given are with a midair jump.

Blue, Pink Brinstar: Use Flash Suit

---

region/maridia/inner-pink/Crab Shaft.json
region/maridia/inner-pink/Draygon Save Room.json
region/maridia/inner-pink/Draygon's Room.json
region/maridia/inner-pink/East Cactus Alley Room.json
region/maridia/inner-pink/Halfie Climb Room.json
region/maridia/inner-pink/The Precious Room.json
region/maridia/inner-pink/West Cactus Alley Room.json
region/norfair/east/Frog Savestation.json
tech.json

I'm putting off figuring out the temporary blue chain strats in West Cactus Alley (1->2). There's going to be several tricky ones involving pause-buffered remorphs and it's not easy to work out all the ranges of speed values that work for each one.

Rest of Pink Maridia remote runways

---

scripts/populate_strat_ids.py

After this, I'm planning to create a GitHub Actions workflow that we could use to just click a button to generate/open a PR to apply this script whenever we want.

Add script to populate strat IDs

---

region/maridia/inner-pink/Aqueduct.json

Update description for:
https://maprando.com/logic/room/Aqueduct/9/6/AqueductTopDoorCrouchJump
Add note about subpixel position.

Update AqueductTopDoorCrouchJump notes

---

region/maridia/inner-pink/East Cactus Alley Room.json

https://maprando.com/logic/room/EastCactusAlleyRoom/3/1/SuitlessSpringball
1) Update notes to explain how to do this.
2) This jump is currently in Medium Tech, but the timing is quite difficult.
Discussion begins here: https://discord.com/channels/1053421401354285129/1079847747307446413/1274788834923774045

East Cactus Alley Room / Suitless Springball: Medium -> Very Hard

---

region/crateria/west/Green Pirates Shaft.json
region/maridia/inner-pink/Aqueduct.json
region/maridia/outer/Mama Turtle Room.json
region/wreckedship/main/Sponge Bath.json
region/wreckedship/main/Wrecked Ship Energy Tank Room.json

I lowered the number of Beetom hits on the ice+x-ray climb to be doable tankless. Alternatively it could be lowered to 19 to require one tank - what do you think?

Misc Fixes: Sponge Bath, WS E-Tank, Green Pirate, Mama Turtle

---

region/crateria/central/Landing Site.json

https://videos.maprando.com/video/382
I could not make this trick work with a max height jump, even without high jump boots.

Add note to LandingSite - BigJumpMidairShinespark

---

region/norfair/east/Bubble Mountain.json

I made videos for all of these strats on https://videos.maprando.com. Takes more time that way, so haven't decided yet whether or not to keep doing this going forward.

Bubble mountain temporary blue

---

region/crateria/central/Parlor and Alcatraz.json

Videos:
- Leave With Spark: https://videos.maprando.com/video/379
- Leave With Temporary Blue: https://videos.maprando.com/video/369
The Leave With Spark one comes from insomniaspeed showing us here: https://discord.com/channels/1053421401354285129/1053436236628496454/1272215980483022849.

A couple of new Alcatraz strats

---

region/brinstar/green/Early Supers Room.json

This is just a couple of strats that were missed earlier.
Videos:
- Leave With Mockball (out the right door): https://videos.maprando.com/video/619
- Speedball, Leave With Temporary Blue (out the left door): https://videos.maprando.com/video/620

A couple more strats in Early Supers

---

region/brinstar/green/Etecoon Energy Tank Room.json

Videos:
- top-right to bottom-left: https://videos.maprando.com/video/626
- top-left to bottom-left: https://videos.maprando.com/video/642
- bottom-left to bottom-right (speedball): https://videos.maprando.com/video/633
- bottom-left to bottom-right (spring ball bounce): https://videos.maprando.com/video/634

Etecoon ETank temp blue

---

region/crateria/west/Gauntlet Energy Tank Room.json
region/crateria/west/Gauntlet Entrance.json

I skipped these ones in my first pass through Crateria.
Videos:
- Gauntlet Entrance right-to-left: https://videos.maprando.com/video/393
- Gauntlet Entrance left-to-right (with walljumps): https://videos.maprando.com/video/458
- Gauntlet Entrance left-to-right (no walljumps): https://videos.maprando.com/video/459
- Gauntlet Energy Tank Room left-to-right: https://videos.maprando.com/video/570
- Gauntlet Energy Tank Room right-to-left: https://videos.maprando.com/video/588
- Gauntlet Energy Tank Room right-to-left, method to avoid acid damage at end: https://videos.maprando.com/video/589

Gauntlet temp blue

---

region/brinstar/pink/Big Pink.json

Just a few `leaveWithTemporaryBlue` strats that were missed on the first pass.
Videos:
- top-left door: https://videos.maprando.com/video/643
- middle left door: https://videos.maprando.com/video/644
- bottom right door: https://videos.maprando.com/video/645

A few Big Pink temp blue strats

---

region/brinstar/red/X-Ray Scope Room.json

Video: https://videos.maprando.com/video/646
Based on insomniaspeed showing us here: https://discord.com/channels/1053421401354285129/1053436236628496454/1280911335063949475.

X-Ray Scope Room shinespark to break bomb block

---

region/wreckedship/main/Wrecked Ship East Super Room.json

Currently this is an Insane-level notable strat. But the shortcharge is not actually very tight and I believe it makes more sense in Expert. To do it while staying completely inside the robot, it can be done with a 4-tap with relatively long taps, 7 frames each (or more).

Relax shortcharge requirements for robot clip

---

region/maridia/inner-yellow/Kassiuz Room.json

Videos:
- top to bottom: https://videos.maprando.com/video/704
- bottom to top: https://videos.maprando.com/video/702

Kassiuz Room temp blue

---

region/maridia/inner-yellow/Northwest Maridia Bug Room.json

Videos:
- Left side: https://videos.maprando.com/video/705
- Right side: https://videos.maprando.com/video/706

Northwest Maridia Bug Room temp blue

---

region/crateria/east/Bowling Alley Path.json

Videos:
- left-to-right: https://videos.maprando.com/video/734
- right-to-left: https://videos.maprando.com/video/735

Bowling Alley Path temp blue

---

region/maridia/inner-yellow/Bug Sand Hole.json

Videos:
- left-to-right: https://videos.maprando.com/video/699
- right-to-left: https://videos.maprando.com/video/700

Bug Sand Hole temp blue

---

region/norfair/east/Double Chamber.json

Videos:
- In-room runway to leave with temp blue at bottom-left:
- With X-ray:  https://videos.maprando.com/video/739
- Without X-ray or Morph: https://videos.maprando.com/video/738
- In-room runway to leave with temp blue at top-left:
- With HiJump, Spring Ball: https://videos.maprando.com/video/803
- With HiJump, Spring Ball, X-Ray: https://videos.maprando.com/video/804 
- Slow blue jump through bottom-left door to ground, HiJump + spring ball jump to top-left: https://videos.maprando.com/video/737
- Speedy blue jump through bottom-left door, to top-left:
- With HiJump: https://videos.maprando.com/video/801
- With Spring Ball jump: https://videos.maprando.com/video/802
- From top-left to bottom-left: https://videos.maprando.com/video/736

Double Chamber temp blue

---

helpers.json
region/lowernorfair/west/Screw Attack Room.json
region/maridia/inner-pink/Aqueduct.json
region/maridia/inner-pink/Botwoon Hallway.json
tech.json

I don't know many places where this tech would be used besides backing into a corner. There are probably more that should be added later.

Add canMorphTurnaround, Fix Screw speed jump

---

region/norfair/east/Lava Dive Room.json

Videos:
- With X-Ray: https://videos.maprando.com/video/820
- Without X-Ray: https://videos.maprando.com/video/819

Lava Dive temp blue

---

region/norfair/east/Green Bubbles Missile Room.json

Videos:
- left-to-right, with X-Ray: https://videos.maprando.com/video/817
- left-to-right, without X-Ray: https://videos.maprando.com/video/818
- right-to-left, with X-Ray: https://videos.maprando.com/video/816
- right-to-left, without X-Ray: https://videos.maprando.com/video/815

Green Bubbles temp blue

---

region/norfair/east/Nutella Refill.json

Videos:
- left to right: https://videos.maprando.com/video/828
- right to left: https://videos.maprando.com/video/829

Nutella Refill temp blue

---

region/norfair/east/Red Pirate Shaft.json

Video: https://videos.maprando.com/video/836

Red Pirate Shaft temp blue

---

region/norfair/east/Purple Shaft.json

Videos:
- bottom to middle (short runway): https://videos.maprando.com/video/830
- bottom to middle (full runway): https://videos.maprando.com/video/831
- bottom to top (short runway): https://videos.maprando.com/video/832
- bottom to top (full runway): https://videos.maprando.com/video/833
- middle to bottom: https://videos.maprando.com/video/834
- middle to top: https://videos.maprando.com/video/835
As usual, some extra heat frames are added to account for the possibility of entering with lower speed.

Purple Shaft temp blue

---

region/norfair/east/Rising Tide.json

Videos:
- left to right: https://videos.maprando.com/video/873
- right to left: https://videos.maprando.com/video/874
The trickiest part is avoiding getting hit by Dragon projectiles.

Rising Tide temp blue

---

region/lowernorfair/east/Ridley's Room.json
region/maridia/inner-pink/Botwoon's Room.json

This adds back a couple of notables that got missed in PR #1654.

Add a couple notables that got missed in the migration

---

helpers.json
region/crateria/west/Gauntlet Energy Tank Room.json
region/norfair/crocomire/Post Crocomire Farming Room.json
region/norfair/east/Acid Snakes Tunnel.json
region/norfair/east/Bat Cave.json
region/norfair/east/Purple Farming Room.json
region/tourian/main/Blue Hopper Room.json

The blue hopper room can still use a lot of work, but I think this is a step in the right direction

Add missing leaveWithRunway, Blue Hopper Obstacle, h_runOverRespawningEnemies

---

region/norfair/east/Norfair Reserve Tank Room.json

https://videos.maprando.com/video/1097

Norfair Reserve Tank Room -- define Sovas as Obstacle B, strat 32 "Return Carefully (Sovas Cleared)"

---

region/norfair/east/Norfair Reserve Tank Room.json

- Remove screw attack and careful jump from base
- Add no etank room strats
- require weapons with trickyJump in base (kill sovas)

Update Norfair Reserve Tank Room

---

region/brinstar/red/Red Tower.json
region/lowernorfair/east/Ridley's Room.json
region/lowernorfair/west/Acid Statue Room.json
region/maridia/inner-pink/Crab Shaft.json

Just a few random fixes that have been mentioned in the discord recently.

Misc: Walljumpess Ridley, Acid Statue Reserve, Fix Crab Shaft Flash Use

---

region/brinstar/blue/Blue Brinstar Energy Tank Room.json

Video: https://videos.maprando.com/video/1247

Add Blue Brin ETank notable spark

---

region/crateria/east/East Ocean.json

Videos for all these new/updated strats are on https://videos.maprando.com.

East Ocean shinecharge updates

---

region/maridia/inner-pink/Halfie Climb Room.json

Videos for these on the video site: https://videos.maprando.com.

Halfie Climb shinecharges

---

tech.json

This is based on the discussion in #1718.

Add canMidairShinespark as dependency in canShinechargeMovementComplex

---

helpers.json
logicalRequirements.md
region/crateria/central/Crateria Super Room.json
schema/m3-requirements.schema.json
tech.json

This is focused on the possibility of adding pause abuse strats like the given example in Crateria Supers. I'm not very confident on schema changes, so this may or may not be done correctly.

Pause Abuse Crateria Supers Spikes, Add resourceConsumed

---

region/norfair/west/Ice Beam Acid Room.json

The room is asymmetric here because when entering on the left Samus can run onto the Tripper for more speed.
Videos on https://videos.maprando.com

Ice Beam Acid shinesparks

---

region/norfair/west/Ice Beam Gate Room.json

This was shown by somerando in the Discord a while back.
Video: https://videos.maprando.com/video/1332

Ice Beam Gate Room leave shinecharged

---

helpers.json

I felt like it could be nice to have this documented. I'm not sure if it's possible to toggle Screw by spamming right, but Screw is not often important to disable anyways.

Add h_EquipmentScreenFix

---

region/brinstar/blue/Morph Ball Room.json
region/brinstar/red/Caterpillar Room.json
region/norfair/east/Bubble Mountain.json
region/wreckedship/main/Sponge Bath.json

Partially addresses #1267 (Skipped the heated ones)

Add more speedy cross room jumps

---

region/maridia/inner-pink/Botwoon Energy Tank Room.json
region/maridia/inner-pink/Draygon's Room.json
region/maridia/inner-yellow/Northwest Maridia Bug Room.json
region/maridia/inner-yellow/Plasma Room.json
region/maridia/inner-yellow/Plasma Spark Room.json
region/maridia/outer/Crab Hole.json
region/maridia/outer/Fish Tank.json
region/maridia/outer/Main Street.json
region/maridia/outer/Mama Turtle Room.json

Relies on #1731 for `canControlShinesparkEnd`

Reserve Pause Abuse: Remaining Maridia

---

region/tourian/main/Blue Hopper Room.json
region/wreckedship/main/Basement.json

Only going for high hitting enemies. Most enemies here are pretty low damage.
Skipped all of the blue hopper hits that are taken to open the left door with a PB or missiles

Reserve Pause Abuse WS, Tourian

---

region/norfair/west/Ice Beam Snake Room.json
tech.json

Probably the most interesting thing here is the 1 -> 2 strat that sparks out through the door.
The rest of the strats are just walljump-avoiding ones, to spark from the bottom right to the top or middle in a way that is faster (less heat damage) compared to going up the left side of the room.

Ice Beam Snake Room shinesparks

---

region/lowernorfair/east/The Worst Room In The Game.json

Not really planning on doing more heated ones, even though there are still a lot that could be added in LN.

Pause Abuse: WRITG Top Pirate

---

region/tourian/main/Tourian Escape Room 3.json

Tourian Escape 3 R to L canUseIFrames

---

items.json
region/region-readme.md
schema/m3-requirements.schema.json
schema/m3-room.schema.json

A quick clean up of some unnecessary schema properties

Schema Cleanup

---

schema/m3-bossScenarios.schema.json
schema/m3-connection.schema.json
schema/m3-enemies.schema.json
schema/m3-helpers.schema.json
schema/m3-items.schema.json
schema/m3-note.schema.json
schema/m3-requirements.schema.json
schema/m3-room.schema.json
schema/m3-tech.schema.json
schema/m3-weapons.schema.json

Removed all `$id` references in the schema files.
Converted the top level `id` in each schema file to a `$id`.
Is this what was wanted?

Remove $id in schema

---

region/brinstar/red/Caterpillar Room.json
region/maridia/outer/Crab Tunnel.json
region/norfair/crocomire/Grapple Tutorial Room 3.json

This also fixes a typo in a few places.

More ways to open Caterpillar Room green gate with G-mode

---

tech.json

`canTrickyGrappleJump` is setup for only the really tricky stuff.  So base `canGrappleJump` is everything else.
- Through door isn't supported yet
- Escaping water depends, in red fish its not hard but is difficult to control.  In pants room it is extremely hard.

update canGrappleJump note

---

region/brinstar/pink/Spore Spawn Farming Room.json

https://videos.maprando.com/video/1822

Add Roll Under Door notable

---

region/maridia/inner-pink/Aqueduct.json
region/maridia/outer/Fish Tank.json

- I'm not expecting a stutter at Hard
- 4.5 tiles is space to do a 1 tap and release for a good amount of cushion
- DodgewhileShooting added to get past the pirate at the bottom of fish tank

Add leniency runway for fish tank

---

region/crateria/east/Crab Maze.json
region/maridia/inner-pink/Crab Shaft.json

These rooms came up in a seed yesterday.

Add missing Gravity and edit crab farm spots

---

region/maridia/inner-pink/Botwoon Hallway.json

Separated the morph/morphless variants, added more details to each, including Eddie's break spin to position more easily.

Botwoon Hallway Suitless Bootless Update Description

---

region/brinstar/pink/Big Pink.json
region/maridia/inner-pink/Botwoon Hallway.json
region/maridia/inner-pink/East Cactus Alley Room.json
region/maridia/inner-pink/West Cactus Alley Room.json
region/maridia/outer/Mt. Everest.json

Some of the easy fixes from my to-do list that came up recently.
- I thought the East/West Cac Alley notables could both belong in Map Rando's `Hard`
- Prepared Botwoon Hallway clip for `Medium` as well

Easy Misc Fixes

---

region/norfair/crocomire/Post Crocomire Jump Room.json
region/norfair/west/Crocomire Escape.json

Insomniaspeed showed us this one: https://discord.com/channels/1053421401354285129/1053436236628496454/1313884573746069555.
Videos:
- No spring fling: https://videos.maprando.com/video/2451
- With spring fling: https://videos.maprando.com/video/2452

PCJR unmorph bomb boost

---

region/lowernorfair/east/Lower Norfair Fireflea Room.json

This was found by SamLittlehorns. 
Video:
- original video by Sam: https://videos.maprando.com/video/2435
- with optimized shinespark frames: https://videos.maprando.com/video/2453

LN Firefleas X-mode shinespark

---

region/norfair/east/Bubble Mountain.json

This strat didn't seem fair in Basic. Split it off from the base strat since it seems worth having its own note.
Video by Sam: https://videos.maprando.com/video/2424

Split off bubble mountain Frozen Ripper Squeeze

---

region/brinstar/pink/Pink Brinstar Hopper Room.json

I added a tricky jump to using a frozen hopper as it felt relatively hard and unintuitive - I can return it if you'd like. 
Strat 77 was removed (GGG, HiJump, Ice) because it looked like it was covered under strats 10/11 (GGG, Hoppers dead/alive)

Pink Hoppers, Add Hit as Entrance Condition

---

region/maridia/outer/Fish Tank.json
region/maridia/outer/Glass Tunnel.json
region/maridia/outer/Mt. Everest.json
region/region-readme.md
schema/m3-room.schema.json
strats.md
tests/asserts/keywords.py

This requires #1834 to be merged first. Only the last commit on this is new.

Remove Spawn At Schema, etc.

---

region/brinstar/blue/Blue Brinstar Energy Tank Room.json
region/brinstar/blue/Morph Ball Room.json

Somerando(cauuyjdp) reported one of these this morning: https://discord.com/channels/1053421401354285129/1053436236628496454/1318955707223113809
So I scanned through all the rooms affected by Zebes awake and spotted these other ones as well.

Fix some missing zebes awake requirements

---

region/lowernorfair/west/Golden Torizo's Room.json

I'm starting to go through the backlog of videos with Incomplete status, which is now a good way to keep track of a lot of the strats that need to be added. This one had a lot of possible variations so I also created more videos in the process of working them out:
- Space Jump (Golden Torizo Dead): https://videos.maprando.com/video/3000
- Space Jump (Golden Torizo Alive): https://videos.maprando.com/video/2999
- Spring Ball Jump (Equipping HiJump, Golden Torizo Alive): https://videos.maprando.com/video/3001
- Spring Ball Jump (HiJump Equipped, Golden Torizo Alive): https://videos.maprando.com/video/3002
- Springwall (Golden Torizo Alive): https://videos.maprando.com/video/3003
- HiJump Speedy Jump (Golden Torizo Dead): https://videos.maprando.com/video/3004
- HiJump Speedy Jump (Golden …

Golden Torizo R-mode clips

---

region/maridia/inner-pink/Draygon's Room.json
region/maridia/inner-yellow/Plasma Spark Room.json
region/tourian/main/Tourian Escape Room 4.json
region/wreckedship/main/Phantoon's Room.json

- Draygon's Room: Leave With Grapple Teleport (Suitless Bootless, Top Position): https://videos.maprando.com/video/3013
- Plasma Spark Room: Insane Frozen Choot Spring Ball Jump: https://videos.maprando.com/video/73
- Phantoon Microwave: https://videos.maprando.com/video/623
- Tourian Escape Room 4: Frozen Pirates: https://videos.maprando.com/video/3014

Insane Frozen Choot Spring Ball Jump and various other strats

---

region/brinstar/green/Green Brinstar Beetom Room.json

Videos:
- right side: https://videos.maprando.com/video/3038
- left side: https://videos.maprando.com/video/3041

Green Brin Beetom Room moonfall

---

region/norfair/east/Norfair Reserve Tank Room.json

This is just based on the video: https://videos.maprando.com/video/1115. I didn't try it out, so let me know if I missed something.

Norfair Reserve Power Bomb with Double Damage Boost

---

region/norfair/crocomire/Post Crocomire Jump Room.json

https://videos.maprando.com/video/3068
https://videos.maprando.com/video/3067
Some item combinations make it possible to avoid all mella damage, but it is still very difficult in that case.  Without Morph you have to do some serious gymnastics to minimize your hits taken.  `{"obstaclesCleared": ["B"]}`  close to implies you get hit so as to avoid killing the needed Mella but doesn't have a perfect representation.

Update Mella Ice Climb

---

region/norfair/west/Crocomire Speedway.json

One of the right setups (the rest look pretty similar): https://videos.maprando.com/video/3085
If you're interested, here are the two ways I found to get the Multiviola to go up, both times it gets stuck:
- https://videos.maprando.com/video/3088
- https://videos.maprando.com/video/3087

Crocomire Speedway G-Mode Setups

---

region/maridia/inner-yellow/Butterfly Room.json

There is already a strat for wall ice clipping through the door the right. This just adds the corresponding strat on the left.
Video:
- https://videos.maprando.com/video/3104

Butterfly Room left side wall ice clip

---

region/brinstar/pink/Big Pink.json

Videos:
- To node 4: the Middle Doorway (Behind the Power Bomb Blocks)
- Crystal Flash: https://videos.maprando.com/video/3097
- Reo Knockback: https://videos.maprando.com/video/3094
- Reo Platform: https://videos.maprando.com/video/3101
- To node 5: Bottom Middle Door (Blocked by Crumble Blocks)
- Crystal Flash: https://videos.maprando.com/video/3098
- Reo Knockback: https://videos.maprando.com/video/3096
- Reo Platform: https://videos.maprando.com/video/3102

Big Pink: Wall Ice Clip X-Ray Climb

---

region/brinstar/green/Etecoon Energy Tank Room.json

If I remember, BobBob showed us this a long time ago.
Video: https://videos.maprando.com/video/3103

Etecoon ETank Wall Ice Clip X-Ray Climb

---

region/norfair/east/Bubble Mountain.json
region/norfair/west/Crumble Shaft.json
region/norfair/west/Ice Beam Snake Room.json

Sam found that there was a missing G-Mode immobile strat in Bubble Mountain, so I added that as well.

G-Mode Setups - Finish Remaining Upper Norfair

---

region/lowernorfair/east/Red Kihunter Shaft.json

Videos on https://videos.maprando.com.

Red Kihunter Shaft shinecharges

---

region/maridia/outer/Boyon Gate Hall.json
region/maridia/outer/Crab Hole.json

Videos on https://videos.maprando.com.

Boyon Gate and Crab Hole shinecharges

---

region/maridia/outer/Crab Tunnel.json
region/maridia/outer/Fish Tank.json
region/maridia/outer/Glass Tunnel.json
tests/asserts/keywords.py

Videos on https://videos.maprando.com.
Glass Tunnel still needs cross-room temporary blue strats added too. Will come back to that later.

Glass Tunnel shinecharges (etc.) 

---

region/maridia/outer/Main Street.json
region/maridia/outer/West Glass Tube Tunnel.json

Videos on https://videos.maprando.com

Rest of Outer Maridia shinecharges

---

region/maridia/inner-pink/Aqueduct.json
region/maridia/inner-pink/Below Botwoon Energy Tank.json
region/maridia/inner-pink/Botwoon Energy Tank Room.json
region/maridia/inner-pink/Botwoon Hallway.json
region/maridia/inner-pink/Botwoon's Room.json
region/maridia/inner-pink/Colosseum.json

Colosseum is the main room here that was missing lots of strats. I also refined some strats and tightened frames in Aqueduct and a few other rooms.
As usual, videos are on https://videos.maprando.com.

Some Pink Maridia shinecharges

---

helpers.json
region/maridia/inner-pink/Aqueduct.json
region/maridia/inner-pink/Crab Shaft.json
region/maridia/inner-pink/East Sand Hole.json
region/maridia/inner-pink/The Precious Room.json
region/maridia/inner-pink/West Cactus Alley Room.json
region/maridia/inner-yellow/Plasma Spark Room.json
region/maridia/inner-yellow/Pseudo Plasma Spark Room.json
region/maridia/inner-yellow/Watering Hole.json

This turned out to be quite a bit easier than a normal double spring ball jump, but it's obscurity makes it seem fine to share the same tech.
I'll work on Outer and other water rooms next.

Artificial Morph Double Spring, G/P/Y Maridia

---

logicalRequirements.md
region/maridia/outer/Main Street.json
schema/m3-requirements.schema.json
tests/asserts/keywords.py

This was a pain, but I think these strats will be quite impactful. It will be fun to see more seeds have SpeedBooster here.
Some strats looked like they would fit under `canBeVeryPatient`. I didn't want to complicate things yet by thinking about immobile at 3. I'm not great at IBJ, but it looked maybe possible to get PLMs overloaded in time. Starting at the very bottom will maybe make things too tight.

G-Mode Main St Pt 2. Add Many Variations

---

region/brinstar/pink/Big Pink.json
region/crateria/central/Landing Site.json
region/lowernorfair/east/Amphitheatre.json
region/lowernorfair/west/Golden Torizo's Room.json

This is part of #1617 where some complex notables include performing an easier notable.

Add missing implied notable requirements.

---

region/maridia/inner-pink/East Cactus Alley Room.json

#1842 I climbed left wall, unlike in the video.

Refine East Cac Alley left-side X-mode shinecharge

---

region/brinstar/green/Spore Spawn Room.json

I couldn't figure out an xfactor kill, but maybe you could swing particles in just the right way.

Reverse Spore Spawn fight

---

region/brinstar/red/Red Tower.json
region/crateria/east/The Moat.json
region/maridia/inner-green/Pants Room.json
region/maridia/inner-pink/Botwoon Energy Tank Room.json
region/maridia/inner-pink/Colosseum.json
region/maridia/inner-pink/Crab Shaft.json
region/maridia/inner-pink/East Cactus Alley Room.json
region/maridia/inner-pink/Halfie Climb Room.json
region/maridia/inner-pink/West Sand Hole.json
region/maridia/inner-yellow/Kassiuz Room.json
region/maridia/outer/Mt. Everest.json
region/norfair/crocomire/Crocomire's Room.json
region/wreckedship/main/Sponge Bath.json

The Red Tower one is on the border but I really don't want to move it to very hard.

TrickySpringBallJump Pass

---

region/brinstar/blue/Morph Ball Room.json
region/brinstar/green/Etecoon Energy Tank Room.json
region/crateria/east/Crateria Kihunter Room.json

A few quick strats from Sam's video finds

A Few Misc G-Mode Strats

---

region/norfair/east/Double Chamber.json

This was a particularly difficult room, as it's difficult to traverse and the gate, item, and Kago all made it worse.
I think the two nodes ended up being worthwhile. I didn't see a good place to add another, but if you have any ideas for how to clean it up, I could redo the room.

G-Mode: Double Chamber

---

region/norfair/west/Business Center.json

Gaining a shinecharge in-room would also be possible, but I didn't want to do it; could be added later.

Business Center temp blue

---

region/crateria/west/Statues Hallway.json
region/lowernorfair/east/Metal Pirates Room.json
region/maridia/inner-pink/Draygon's Room.json
region/maridia/inner-pink/Halfie Climb Room.json
region/maridia/inner-pink/The Precious Room.json
region/maridia/inner-pink/West Cactus Alley Room.json
region/maridia/outer/Fish Tank.json

This covers most of the applications of using side platforms left-to-right to go up a water room. Crab Shaft and Crab Hole will be done in a separate PR.

Most left-to-right side platform jumps into water

---

region/lowernorfair/west/Fast Ripper Room.json

There is more than can be done with this room but I mostly wanted the easy ripper farm strat to be added.

Add ripper farm while moving strat

---

region/norfair/east/Spiky Acid Snakes Tunnel.json

somerando(cauuyjdp) shared this in the Map Rando Discord today: https://discord.com/channels/1053421401354285129/1053436236628496454/1358104299766419576
Videos:
- left-to-right (showing X position): https://videos.maprando.com/video/5977
- right-to-left (showing X position): https://videos.maprando.com/video/5978
- left-to-right (showing energy): https://videos.maprando.com/video/5997

Spiky Acid Snakes Tunnel X-mode

---

region/brinstar/green/Early Supers Room.json
region/crateria/central/Final Missile Bombway.json
region/lowernorfair/east/Mickey Mouse Room.json
region/lowernorfair/east/Three Musketeers' Room.json
region/maridia/outer/Fish Tank.json
region/maridia/outer/Mt. Everest.json

These are all in Extreme, except the Everest short-charge, which is in Insane.

Removing and refining high-difficulty notables

---

region/brinstar/green/Green Brinstar Main Shaft.json
region/brinstar/green/Green Hill Zone.json
region/brinstar/kraid/Baby Kraid Room.json
region/crateria/central/Flyway.json

This also refines a couple setup notes.

A couple L->R side platform air applications

---

region/brinstar/blue/Blue Brinstar Boulder Room.json
region/brinstar/green/Early Supers Room.json
schema/m3-room.schema.json
strats.md
tests/asserts/keywords.py

This adds a `comeInBlueSpaceJumping` entrance condition, to represent another Early Supers speedball strat.

Blue Boulder and Early Supers side platforms, and comeInBlueSpaceJumping

---

region/brinstar/pink/Waterway Energy Tank Room.json
region/lowernorfair/east/Ridley Tank Room.json
region/norfair/east/Bubble Mountain.json

This finishes off a first pass at left-to-right side platform applications.

Bubble Mountain side platform jumps

---

region/brinstar/red/Below Spazer.json

This is similar to the Big Pink super block speedball, except much easier. Coming in from Lava Dive appears impossible since you can't get enough run speed to make it to the ledge while also getting blue speed.

Below Spazer side platform jumps

---

region/maridia/inner-yellow/Maridia Elevator Room.json

Maridia Elevator Room right-to-top side platform jumps

---

region/brinstar/kraid/Warehouse Energy Tank Room.json
region/wreckedship/main/Bowling Alley.json

Videos:
- From an air room: https://videos.maprando.com/video/6476
- From a water room: https://videos.maprando.com/video/6475

Warehouse E-Tank tricky evade beetoms

---

region/maridia/inner-pink/Aqueduct.json
region/maridia/inner-pink/Botwoon Energy Tank Room.json
region/maridia/inner-yellow/Bug Sand Hole.json
tech.json

https://videos.maprando.com/video/6785
https://videos.maprando.com/video/6786
https://videos.maprando.com/video/6787
https://videos.maprando.com/video/6788
https://videos.maprando.com/video/6114
https://videos.maprando.com/video/6641

Downward G-Mode setups, sand transitions

---

region/lowernorfair/east/Lower Norfair Fireflea Room.json

Surprised this was missing.
Feel free to reclassify these slope tiles.

LN Fireflea shinespark

---

region/brinstar/green/Etecoon Energy Tank Room.json
region/brinstar/kraid/Kraid Eye Door Room.json
region/brinstar/pink/Big Pink.json
region/brinstar/pink/Dachora Room.json
region/crateria/central/Parlor and Alcatraz.json
region/crateria/east/West Ocean.json
region/tourian/main/Metroid Room 2.json
region/tourian/main/Rinka Shaft.json
region/wreckedship/main/Wrecked Ship Main Shaft.json

Also found some missing strats - I'll write them up in an issue

Add canComplexGMode to setups (B, C, T, WS)

---

helpers.json
region/crateria/central/Climb Supers Room.json

This is an attempt to add lenience for the speed keep strats, consistent with the lenience for X-mode and spikesuit.
This also updates the lenience for the X-Mode Blue Suit strats (which are currently Ignored in the randomizer).

Climb Supers speed keep lenience

---

region/wreckedship/main/Attic.json

Surprised the tests wouldn't catch this kind of thing.

Fix kihunter enemy names
